//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC29METAAVPlayerTrackingResources29METAAVPlayerTrackingResources_METAAVPlayerTrackingResources_h
#define _TtC29METAAVPlayerTrackingResources29METAAVPlayerTrackingResources_METAAVPlayerTrackingResources_h
@import Foundation;

@interface _TtC29METAAVPlayerTrackingResources29METAAVPlayerTrackingResources (METAAVPlayerTrackingResources) <_TtP30METAAVResourcesTrackerProtocol13METAAVDecoder_>
/* instance methods */
- (BOOL)allTracksLoaded;
- (void)numVideoTracksWithCompletionHandler:(id /* block */)handler;
- (void)numAudioTracksWithCompletionHandler:(id /* block */)handler;
- (void)videoTracksResolutionsWithCompletionHandler:(id /* block */)handler;
- (id)decoderType;
@end

#endif /* _TtC29METAAVPlayerTrackingResources29METAAVPlayerTrackingResources_METAAVPlayerTrackingResources_h */
