//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC21IGRequestSchedulerKit18IGRequestScheduler_h
#define _TtC21IGRequestSchedulerKit18IGRequestScheduler_h
@import Foundation;

#include "IGNetworkLayer-Protocol.h"

@interface _TtC21IGRequestSchedulerKit18IGRequestScheduler : NSObject<IGNetworkLayer> { // (Swift)
  /* instance variables */
   nextLayer;
   dispatcher;
   payloadConfig;
}

/* instance methods */
- (id)startRequest:(id)request policy:(id)policy callbacks:(id)callbacks;
- (id)init;
@end

#endif /* _TtC21IGRequestSchedulerKit18IGRequestScheduler_h */
