//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC27IGSundialAudioUserEducation38IGSundialAudioLimitedCatalogBannerView_h
#define _TtC27IGSundialAudioUserEducation38IGSundialAudioLimitedCatalogBannerView_h
@import Foundation;

#include "IGBaseView.h"
#include "_TtP27IGSundialAudioUserEducation46IGSundialAudioLimitedCatalogBannerViewDelegate_-Protocol.h"

@interface _TtC27IGSundialAudioUserEducation38IGSundialAudioLimitedCatalogBannerView : IGBaseView { // (Swift)
  /* instance variables */
   isAccountTypeSpecific;
   showDetailedBusinessAccountContent;
   licensedMusicEligibilityState;
   textLabelHeight;
   textView;
}

@property (nonatomic, weak) NSObject<_TtP27IGSundialAudioUserEducation46IGSundialAudioLimitedCatalogBannerViewDelegate_> *delegate;
@property (nonatomic) BOOL shouldUpdateThemeBasedOnTraitCollection;

/* instance methods */
- (id)initWithShouldUpdateThemeBasedOnTraitCollection:(BOOL)collection isAccountTypeSpecific:(BOOL)specific showDetailedBusinessAccountContent:(BOOL)content eligibilityState:(long long)state;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)setWithIsAccountTypeSpecific:(BOOL)specific showDetailedBusinessAccountContent:(BOOL)content licensedMusicEligibilityState:(long long)state;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
@end

#endif /* _TtC27IGSundialAudioUserEducation38IGSundialAudioLimitedCatalogBannerView_h */
