//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC26IGSundialDataCreationLayer14SharingOptions_h
#define _TtC26IGSundialDataCreationLayer14SharingOptions_h
@import Foundation;

@class NSArray;

@interface _TtC26IGSundialDataCreationLayer14SharingOptions : NSObject // (Swift)

@property (nonatomic) BOOL disableLikeAndViewCounts;
@property (nonatomic) BOOL disableComments;
@property (nonatomic) BOOL enableGifting;
@property (nonatomic) BOOL enableThirdPartyDownloads;
@property (nonatomic) BOOL templateOptOutEnabled;
@property (nonatomic) BOOL shareToFeed;
@property (nonatomic) BOOL shareToSubscribers;
@property (nonatomic, copy) NSArray *templateReusableClipsIndices;

/* class methods */
+ (id)defaults;

/* instance methods */
- (id)initWithDisableLikeAndViewCounts:(BOOL)counts disableComments:(BOOL)comments enableGifting:(BOOL)gifting enableThirdPartyDownloads:(BOOL)downloads templateOptOutEnabled:(BOOL)enabled templateReusableClipsIndices:(id)indices shareToFeed:(BOOL)feed shareToSubscribers:(BOOL)subscribers;
- (id)init;
@end

#endif /* _TtC26IGSundialDataCreationLayer14SharingOptions_h */
