//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC18IGPushLoggingSwift21IGNotificationLogging_IGPushLoggingSwift_h
#define _TtC18IGPushLoggingSwift21IGNotificationLogging_IGPushLoggingSwift_h
@import Foundation;

@interface _TtC18IGPushLoggingSwift21IGNotificationLogging (IGPushLoggingSwift)
/* class methods */
+ (void)logReceivedRealtimeInAppNotificationWithContentID:(id)id mentionedContentIDs:(id)ids mentionedUserIDs:(id)ids messageID:(id)id ndid:(id)ndid notificationType:(id)type recipientIGID:(long long)igid senderIGID:(id)igid behavior:(long long)behavior objective:(long long)objective landingPath:(id)path source:(long long)source logger:(id)logger containerModule:(id)module appState:(id)state;
+ (void)logDismissedRealtimeInAppNotificationWithContentID:(id)id mentionedContentIDs:(id)ids mentionedUserIDs:(id)ids messageID:(id)id ndid:(id)ndid notificationType:(id)type recipientIGID:(long long)igid senderIGID:(id)igid behavior:(long long)behavior objective:(long long)objective landingPath:(id)path source:(long long)source logger:(id)logger containerModule:(id)module appState:(id)state;
+ (void)logClickedRealtimeInAppNotificationWithContentID:(id)id mentionedContentIDs:(id)ids mentionedUserIDs:(id)ids messageID:(id)id ndid:(id)ndid notificationType:(id)type recipientIGID:(long long)igid senderIGID:(id)igid behavior:(long long)behavior objective:(long long)objective landingPath:(id)path source:(long long)source logger:(id)logger containerModule:(id)module appState:(id)state;
+ (void)logWillDisplayRealtimeInAppNotificationWithContentID:(id)id mentionedContentIDs:(id)ids mentionedUserIDs:(id)ids messageID:(id)id ndid:(id)ndid notificationType:(id)type recipientIGID:(long long)igid senderIGID:(id)igid behavior:(long long)behavior objective:(long long)objective landingPath:(id)path source:(long long)source logger:(id)logger containerModule:(id)module appState:(id)state;
+ (void)logExpandedContentRealtimeInAppNotificationWithContentID:(id)id mentionedContentIDs:(id)ids mentionedUserIDs:(id)ids messageID:(id)id ndid:(id)ndid notificationType:(id)type recipientIGID:(long long)igid senderIGID:(id)igid behavior:(long long)behavior objective:(long long)objective landingPath:(id)path source:(long long)source logger:(id)logger containerModule:(id)module appState:(id)state;
@end

#endif /* _TtC18IGPushLoggingSwift21IGNotificationLogging_IGPushLoggingSwift_h */
