//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBAnalyticsSamplingStatsCollector_h
#define FBAnalyticsSamplingStatsCollector_h
@import Foundation;

@class NSString;
@protocol FBAnalyticsSamplingStatsCollectorDelegateProtocol, FBReliabilityStatisticsCounterStorage;

@interface FBAnalyticsSamplingStatsCollector : NSObject {
  /* instance variables */
  NSObject<FBAnalyticsSamplingStatsCollectorDelegateProtocol> *_delegate;
  NSObject<FBReliabilityStatisticsCounterStorage> *_counterStorage;
  NSString *_libVersion;
  NSString *_timeStampKeyForUserDefault;
  double _lastFlushTimestamp;
}

/* class methods */
+ (void)setupWithDelegate:(id)delegate;
+ (void)setupForNewSamplingLibraryWithDelegate:(id)delegate;
+ (void)setupForConfigRefactoringExperimentWithDelegate:(id)delegate;
+ (id)sharedStatsCollector;
+ (id)sharedStatsCollectorForNewSamplingLibrary;
+ (id)sharedStatsCollectorForConfigRefactoringExperiment;

/* instance methods */
- (id)initWithDelegate:(id)delegate storageFileName:(id)name timeStampKeyForUserDefault:(id)default libVersion:(id)version;
- (void)recordSamplingConfigDownloadCount;
- (void)recordSamplingConfigDownloadSize:(int)size;
- (void)recordSamplingConfigPersistenceCount;
- (void)maybeFlushStats;
- (void)_flushStats;
- (void)_resetCounterStorage;
- (id)_reliabilityStatsForCounters:(id)counters;
- (id)_counterStorageFilePathWithFileName:(id)name;
@end

#endif /* FBAnalyticsSamplingStatsCollector_h */
