//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBARNativeUIControlServiceRawEditableTextDelegate_Protocol_h
#define FBARNativeUIControlServiceRawEditableTextDelegate_Protocol_h
@import Foundation;

@protocol FBARNativeUIControlServiceRawEditableTextDelegate <NSObject>
/* instance methods */
- (void)nativeUIControlServiceForEffectDescriptor:(id)descriptor enterRawTextEditModeWithCurrentText:(id)text isFirstEdit:(BOOL)edit textChangedCallback:(id /* block */)callback exitCallback:(id /* block */)callback;
- (void)nativeUIControlServiceExitRawTextEditModeForEffectDescriptor:(id)descriptor;
@end

#endif /* FBARNativeUIControlServiceRawEditableTextDelegate_Protocol_h */
