//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBMessageHeartPowerupCoordinator_h
#define FBMessageHeartPowerupCoordinator_h
@import Foundation;

#include "FBParticleLayer.h"
#include "FBPerlinNoise.h"
#include "NSObject-Protocol.h"

@class CAGradientLayer, NSMutableArray, NSString, UIImage, UIImpactFeedbackGenerator, UIView;
@protocol FBMessagePowerupDelegate;

@interface FBMessageHeartPowerupCoordinator : NSObject<NSObject> {
  /* instance variables */
  UIView *_messageForegroundView;
  UIView *_messageBackgroundView;
  UIView *_textViewBackgroundView;
  CAGradientLayer *_backgroundGradientLayer;
  FBParticleLayer *_heart1;
  FBParticleLayer *_heart2;
  FBParticleLayer *_heart3;
  FBParticleLayer *_heart4;
  FBParticleLayer *_heart5;
  FBParticleLayer *_heart6;
  UIImage *_heartImage;
  unsigned long long _numberOfFloatingHeartAnimationsCompleted;
  BOOL _playingTapAnimation;
  NSMutableArray *_idleHearts;
  UIImpactFeedbackGenerator *_feedbackGenerator;
  BOOL _keyboardAppearing;
  FBPerlinNoise *_perlinNoise;
  NSObject<FBMessagePowerupDelegate> *_delegate;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMessagePowerupDelegate:(id)delegate heartImage:(id)image;
- (void)layoutEffect;
- (void)resetAnimation;
- (void)playAnimationWithThreadForegroundView:(id)view threadBackgroundView:(id)view composerMinY:(double)y keyframesDelegate:(id)delegate useHapticFeedback:(BOOL)feedback;
- (BOOL)shouldBringMessageCellToFrontOfMessageList;
- (void)configureWithViewModel:(struct { double x0; id x1; BOOL x2; })model;
- (id)_addEmojiParticleLayerForImage:(id)image inFrontOfMessage:(BOOL)message scale:(double)scale rotation:(double)rotation;
- (void)_animateFloatingHeart:(id)heart scaleDuringFloating:(BOOL)floating delay:(double)delay rotationAxisOffset:(double)offset threadForegroundView:(id)view threadBackgroundView:(id)view releaseBlock:(id /* block */)block completionBlock:(id /* block */)block;
- (void)_applicationWillEnterForeground:(id)foreground;
- (void)_keyboardWillShow:(id)show;
- (void)_keyboardDidShow:(id)show;
@end

#endif /* FBMessageHeartPowerupCoordinator_h */
