//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBMessagingMailboxBootstrapProviders_h
#define FBMessagingMailboxBootstrapProviders_h
@import Foundation;

@interface FBMessagingMailboxBootstrapProviders : NSObject

@property (readonly, nonatomic) id /* block */ configurationProvider;
@property (readonly, nonatomic) id /* block */ credentialsProvider;
@property (readonly, nonatomic) id /* block */ authDataProvider;
@property (readonly, nonatomic) id /* block */ dbStoreURLProvider;
@property (readonly, nonatomic) id /* block */ mediaStoreURLProvider;
@property (readonly, nonatomic) id /* block */ databaseConfigProvider;
@property (readonly, nonatomic) id /* block */ mediaManagerProvider;
@property (readonly, nonatomic) id /* block */ mediaSendManagerConfigProvider;
@property (readonly, nonatomic) id /* block */ mediaDecodePluginsProvider;
@property (readonly, nonatomic) id /* block */ dasmConfigProvider;
@property (readonly, nonatomic) id /* block */ willInitializeActionsProvider;
@property (readonly, nonatomic) id /* block */ willActivateActionsProvider;
@property (readonly, nonatomic) id /* block */ didActivateActionsProvider;
@property (readonly, nonatomic) id /* block */ willDeactivateActionsProvider;
@property (readonly, nonatomic) id /* block */ didDeactivateActionsProvider;
@property (readonly, nonatomic) id /* block */ fatalErrorHandlerProvider;
@property (readonly, nonatomic) id /* block */ willSwitchAccountActionsProvider;
@property (readonly, nonatomic) id /* block */ databaseConfigureCallback;
@property (readonly, nonatomic) id /* block */ mcpAppObjectRegistrationProvider;

/* instance methods */
- (id)initWithConfigurationProvider:(id /* block */)provider credentialsProvider:(id /* block */)provider authDataProvider:(id /* block */)provider dbStoreURLProvider:(id /* block */)urlprovider mediaStoreURLProvider:(id /* block */)urlprovider databaseConfigProvider:(id /* block */)provider mediaManagerProvider:(id /* block */)provider mediaSendManagerConfigProvider:(id /* block */)provider mediaDecodePluginsProvider:(id /* block */)provider dasmConfigProvider:(id /* block */)provider willInitializeActionsProvider:(id /* block */)provider willActivateActionsProvider:(id /* block */)provider didActivateActionsProvider:(id /* block */)provider willDeactivateActionsProvider:(id /* block */)provider didDeactivateActionsProvider:(id /* block */)provider fatalErrorHandlerProvider:(id /* block */)provider willSwitchAccountActionsProvider:(id /* block */)provider databaseConfigureCallback:(id /* block */)callback mcpAppObjectRegistrationProvider:(id /* block */)provider;
@end

#endif /* FBMessagingMailboxBootstrapProviders_h */
