//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBPinchGestureRecognizer_h
#define FBPinchGestureRecognizer_h
@import Foundation;

#include "UIPinchGestureRecognizer.h"

@interface FBPinchGestureRecognizer : UIPinchGestureRecognizer {
  /* instance variables */
  BOOL _beginsImmediately;
}

@property (nonatomic) unsigned long long maximumNumberOfTouches;

/* instance methods */
- (id)init;
- (id)initWithTarget:(id)target action:(SEL)action;
- (void)touchesBegan:(id)began withEvent:(id)event;
@end

#endif /* FBPinchGestureRecognizer_h */
