//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBSDKLibAnalyzer_h
#define FBSDKLibAnalyzer_h
@import Foundation;

@interface FBSDKLibAnalyzer : NSObject
/* class methods */
+ (void)initialize;
+ (id)getMethodsTable:(id)table frameworks:(id)frameworks;
+ (id)symbolicateCallstack:(id)callstack methodMapping:(id)mapping;
+ (id)_getClassNames:(id)names frameworks:(id)frameworks;
+ (id)_getClassesFrom:(id)from prefixes:(id)prefixes;
+ (void)_addClass:(Class)class isClassMethod:(BOOL)method;
+ (id)_getAddress:(id)address;
+ (id)_getOffset:(id)offset secondString:(id)string;
+ (id)_searchMethod:(id)method sortedAllAddress:(id)address;
@end

#endif /* FBSDKLibAnalyzer_h */
