//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBVideoAutoImpressionManager_h
#define FBVideoAutoImpressionManager_h
@import Foundation;

#include "FBTimer.h"
#include "FBVideoAutoImpressionLoggingSessionDelegate-Protocol.h"

@class NSHashTable, NSMapTable, NSString;

@interface FBVideoAutoImpressionManager : NSObject<FBVideoAutoImpressionLoggingSessionDelegate> {
  /* instance variables */
  FBTimer *_viewCheckTimer;
}

@property (retain, nonatomic) NSMapTable *loggingMap;
@property (retain, nonatomic) NSHashTable *listeners;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)addUpdateListener:(id)listener;
- (void)addPlaybackContextProvider:(id)provider gnvProvider:(id)provider;
- (id)_playbackContextProviderWithVideoView:(id)view;
- (void)loggingSession:(id)session didVideoViewEnter:(id)enter withPercentVisible:(double)visible;
- (void)loggingSession:(id)session didVideoViewExit:(id)exit;
- (void)loggingSession:(id)session didVideoViewUpdate:(id)update withPercentVisible:(double)visible;
@end

#endif /* FBVideoAutoImpressionManager_h */
