//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBWatchdogTimerContext_h
#define FBWatchdogTimerContext_h
@import Foundation;

@class NSFileManager;

@interface FBWatchdogTimerContext : NSObject {
  /* instance variables */
  BOOL _shouldRun;
  BOOL _shouldLog;
  BOOL _checked;
  NSFileManager *_fileManager;
  struct mutex { struct _opaque_pthread_mutex_t { long long __sig; char x[56] __opaque; } __m_; } _mutex;
}

/* class methods */
+ (id)sharedContext;

/* instance methods */
- (id)initWithFileManager:(id)manager;
- (void)_setShouldLogStallAssertionsInProduction:(BOOL)production;
- (void)disableWatchdogInProduction;
@end

#endif /* FBWatchdogTimerContext_h */
