//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FNFDecompressionSessionDebuggerForAVC1_h
#define FNFDecompressionSessionDebuggerForAVC1_h
@import Foundation;

@class NSMutableDictionary, NSString;
@protocol {map<unsigned long long, opaqueCMSampleBuffer *, std::less<unsigned long long>, std::allocator<std::pair<const unsigned long long, opaqueCMSampleBuffer *>>>="__tree_"{__tree<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::__map_value_compare<unsigned long long, std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::less<unsigned long long>>, std::allocator<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>>>="__begin_node_"^v"__pair1_"{__compressed_pair<std::__tree_end_node<std::__tree_node_base<void *> *>, std::allocator<std::__tree_node<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, void *>>>="__value_"{__tree_end_node<std::__tree_node_base<void *> *>="__left_"^v}}"__pair3_"{__compressed_pair<unsigned long, std::__map_value_compare<unsigned long long, std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::less<unsigned long long>>>="__value_"Q}}};

@interface FNFDecompressionSessionDebuggerForAVC1 : NSObject {
  /* instance variables */
  struct CGSize { double width; double height; } _inputSize;
  NSString *_codec;
  struct map<unsigned long long, opaqueCMSampleBuffer *, std::less<unsigned long long>, std::allocator<std::pair<const unsigned long long, opaqueCMSampleBuffer *>>> { struct __tree<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::__map_value_compare<unsigned long long, std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::less<unsigned long long>>, std::allocator<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>>> { void *__begin_node_; struct __compressed_pair<std::__tree_end_node<std::__tree_node_base<void *> *>, std::allocator<std::__tree_node<std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, void *>>> { struct __tree_end_node<std::__tree_node_base<void *> *> { void *__left_; } __value_; } __pair1_; struct __compressed_pair<unsigned long, std::__map_value_compare<unsigned long long, std::__value_type<unsigned long long, opaqueCMSampleBuffer *>, std::less<unsigned long long>>> { unsigned long long __value_; } __pair3_; } __tree_; } _samples;
  NSMutableDictionary *_debugInfos;
}

/* instance methods */
- (id)initWithFormat:(struct opaqueCMFormatDescription *)format;
- (void)dealloc;
- (void)incrementSessionCount;
- (void)decrementSessionCount;
- (void)addSample:(struct opaqueCMSampleBuffer *)sample index:(unsigned long long)index debugInfo:(id)info;
- (void)removeSampleAt:(unsigned long long)at;
- (struct opaqueCMSampleBuffer *)sampleAt:(unsigned long long)at;
- (id)debugInfoAt:(unsigned long long)at;
- (void)reportWarning:(id)warning sample:(struct opaqueCMSampleBuffer *)sample isFirstFrame:(BOOL)frame supplemental:(id)supplemental;
- (void)reportError:(int)error sample:(struct opaqueCMSampleBuffer *)sample sampleIndex:(unsigned long long)index isFirstFrame:(BOOL)frame supplemental:(id)supplemental;
@end

#endif /* FNFDecompressionSessionDebuggerForAVC1_h */
