//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IG4BAnalyticsEvent_h
#define IG4BAnalyticsEvent_h
@import Foundation;

@class NSArray, NSDictionary, NSNumber, NSString;

@interface IG4BAnalyticsEvent : NSObject {
  /* instance variables */
  NSNumber *_availableOptionsCount;
  NSString *_consumerUserID;
  NSString *_facebookPageID;
  NSNumber *_hasFetchedAll;
}

@property (readonly, copy, nonatomic) NSArray *availableOptions;
@property (readonly, copy, nonatomic) NSString *component;
@property (readonly, copy, nonatomic) NSDictionary *configurations;
@property (readonly, copy, nonatomic) NSDictionary *defaultValues;
@property (readonly, copy, nonatomic) NSString *errorMessage;
@property (readonly, copy, nonatomic) NSString *event;
@property (readonly, copy, nonatomic) NSDictionary *selectedValues;
@property (readonly, copy, nonatomic) NSString *step;
@property (readonly, copy, nonatomic) NSString *errorIdentifier;
@property (readonly, copy, nonatomic) NSString *action;
@property (readonly, copy, nonatomic) NSString *locationID;
@property (readonly, copy, nonatomic) NSString *mediaID;
@property (readonly, copy, nonatomic) NSNumber *position;
@property (readonly, copy, nonatomic) NSDictionary *extraData;

/* instance methods */
@end

#endif /* IG4BAnalyticsEvent_h */
