//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAccountTypeCell_h
#define IGAccountTypeCell_h
@import Foundation;

#include "UICollectionViewCell.h"
#include "IGAccountTypeViewModel.h"
#include "IGOptionSelectionLargeCardView.h"

@protocol IGAccountTypeCellDelegate;

@interface IGAccountTypeCell : UICollectionViewCell {
  /* instance variables */
  IGOptionSelectionLargeCardView *_cardView;
  IGAccountTypeViewModel *_viewModel;
  NSObject<IGAccountTypeCellDelegate> *_delegate;
}

/* instance methods */
- (void)_selectButtonTapped;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)layoutSubviews;
@end

#endif /* IGAccountTypeCell_h */
