//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAddAccountIntentTarget_h
#define IGAddAccountIntentTarget_h
@import Foundation;

#include "FBIntentTarget-Protocol.h"
#include "IGMainAppSurfaceIntent.h"
#include "IGRegistrationIntentCollectionContext.h"

@class NSString;

@interface IGAddAccountIntentTarget : NSObject<FBIntentTarget>

@property (readonly, nonatomic) long long entryPoint;
@property (readonly, nonatomic) BOOL startRegistrationFlow;
@property (readonly, nonatomic) IGRegistrationIntentCollectionContext *registrationIntentCollectionContext;
@property (readonly, nonatomic) IGMainAppSurfaceIntent *cancelSwitchDestinationAppSurface;
@property (readonly, nonatomic) IGMainAppSurfaceIntent *postLoginDestinationAppSurface;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithEntryPoint:(long long)point startRegistrationFlow:(BOOL)flow registrationIntentCollectionContext:(id)context cancelSwitchDestinationAppSurface:(id)surface postLoginDestinationAppSurface:(id)surface;
@end

#endif /* IGAddAccountIntentTarget_h */
