//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAdPlatformComponentsManager_h
#define IGAdPlatformComponentsManager_h
@import Foundation;

#include "IGAdPlatformToolbox.h"

@class NSMutableDictionary;
@protocol IGAdFetcherManagerDelegate, IGAdInsertionBrandSafetyDataSource, IGAdInsertionDataSource, IGAdInsertionDelegate, IGAdInsertionMediaTrackerDelegate, IGAdInsertionMediaViewTrackerDataSource;

@interface IGAdPlatformComponentsManager : NSObject {
  /* instance variables */
  NSMutableDictionary *_adPlatformComponentsMap;
  unsigned long long _currentEntryPoint;
  IGAdPlatformToolbox *_adPlatformToolbox;
  unsigned long long _insertionSurface;
  NSObject<IGAdInsertionMediaTrackerDelegate> *_mediaTrackerDelegate;
  NSObject<IGAdInsertionMediaViewTrackerDataSource> *_mediaTrackerDataSource;
  NSObject<IGAdFetcherManagerDelegate> *_adFetcherManagerDelegate;
  NSObject<IGAdInsertionDataSource> *_adPlatformDataSource;
  NSObject<IGAdInsertionDelegate> *_adPlatformDelegate;
  NSObject<IGAdInsertionBrandSafetyDataSource> *_adInsertionBrandSafetyDataSource;
}

/* instance methods */
- (id)initWithAdPlatformToolbox:(id)toolbox mediaTrackerDelegate:(id)delegate mediaTrackerDataSource:(id)source adFetcherManagerDelegate:(id)delegate adPlatformDataSource:(id)source adPlatformDelegate:(id)delegate adInsertionBrandSafetyDataSource:(id)source;
@end

#endif /* IGAdPlatformComponentsManager_h */
