//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAREffectListDownloader_h
#define IGAREffectListDownloader_h
@import Foundation;

#include "FBARTextureCapabilitiesIGL.h"
#include "IGAPIClient-Protocol.h"
#include "IGAREffectFlmConsentManager.h"
#include "IGAREffectListDownloaderConfig.h"
#include "IGAREffectListModel.h"
#include "IGAREffectRemoveController.h"
#include "IGAREffectSaveController.h"
#include "IGAssetModelStorage.h"
#include "IGAssetRetryHelper.h"
#include "IGCameraEffectCollectionDataSourceListener-Protocol.h"
#include "IGCameraEffectsByIDProvider.h"
#include "IGCameraLogger.h"
#include "IGGraphQLService.h"
#include "IGNetworkSource.h"
#include "IGNetworkSourceDelegate-Protocol.h"
#include "IGNetworkSourcePolicyDelegate-Protocol.h"
#include "IGUserLauncherSet-Protocol.h"

@class NSString;
@protocol IGAREffectListDownloaderDelegate, IGGraphQLCache;

@interface IGAREffectListDownloader : NSObject<IGCameraEffectCollectionDataSourceListener, IGNetworkSourceDelegate, IGNetworkSourcePolicyDelegate> {
  /* instance variables */
  NSObject<IGAREffectListDownloaderDelegate> *_delegate;
  NSObject<IGUserLauncherSet> *_launcherSet;
  IGAssetModelStorage *_assetModelStorage;
  struct IGAssetNetworkerRetryParams { long long maxRetries; long long minTimeBetweenRetries; long long maxTimeBetweenRetries; } _retryParameters;
  IGAssetRetryHelper *_retryHelper;
  IGNetworkSource *_networkSource;
  IGAREffectListDownloaderConfig *_config;
  IGAREffectRemoveController *_removeController;
  int _requestInstanceKey;
  IGCameraLogger *_cameraLogger;
  IGAREffectSaveController *_saveController;
  FBARTextureCapabilitiesIGL *_textureCapabilities;
  NSString *_userPK;
  IGCameraEffectsByIDProvider *_targetDataProvider;
  IGGraphQLService *_graphQLService;
  NSObject<IGAPIClient> *_networker;
  IGAREffectFlmConsentManager *_flmConsentManager;
  NSObject<IGGraphQLCache> *_graphQLDiskCache;
  NSString *_shaderDeviceKey;
  BOOL _isEffectsByIdRequest;
}

@property (readonly, nonatomic) IGAREffectListModel *effectListModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithLauncherSet:(id)set userPK:(id)pk networker:(id)networker assetModelStorage:(id)storage retryParameters:(struct IGAssetNetworkerRetryParams { long long x0; long long x1; long long x2; })parameters delegate:(id)delegate config:(id)config removeController:(id)controller saveController:(id)controller graphQLService:(id)qlservice graphQLDiskCache:(id)cache cameraLogger:(id)logger flmConsentManager:(id)manager;
- (void)performRetryEventWithID:(id)id;
- (id)networkSource:(id)source requestWithMaxID:(id)id isPrefetch:(BOOL)prefetch requestTag:(id)tag;
- (void)networkSource:(id)source didFetchObject:(id)object request:(id)request httpResponse:(id)response isPrefetch:(BOOL)prefetch isFromCache:(BOOL)cache requestTag:(id)tag;
- (void)networkSource:(id)source didFetchMoreWithObject:(id)object request:(id)request httpResponse:(id)response isPrefetch:(BOOL)prefetch isFromCache:(BOOL)cache requestTag:(id)tag;
- (void)networkSource:(id)source didFailWithError:(id)error request:(id)request httpResponse:(id)response isPrefetch:(BOOL)prefetch requestTag:(id)tag;
- (id)networkSource:(id)source policyForFetch:(BOOL)fetch;
- (void)setTarget:(id)target;
- (void)unremoveEffectIDFromList:(id)list;
- (void)cameraEffectCollectionDataSource:(id)source didUpdateUsingPage:(id)page resultSource:(long long)source;
- (void)cameraEffectCollectionDataSource:(id)source didFailWithError:(id)error resultSource:(long long)source;
@end

#endif /* IGAREffectListDownloader_h */
