//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAudioModelsPaginatedList_h
#define IGAudioModelsPaginatedList_h
@import Foundation;

#include "IGAsyncTask.h"
#include "IGAudioModelsPaginatedListPage.h"
#include "IGUserSession.h"
#include "NSCopying-Protocol.h"

@class NSMutableArray, NSString;
@protocol IGAudioModelsPaginatedListDelegate;

@interface IGAudioModelsPaginatedList : NSObject<NSCopying> {
  /* instance variables */
  IGAudioModelsPaginatedListPage *_firstPage;
  IGAudioModelsPaginatedListPage *_currentPage;
  IGAsyncTask *_nextPageRequest;
  IGUserSession *_userSession;
  NSString *_productName;
  NSMutableArray *_allModels;
  NSMutableArray *_modelsToRender;
  NSMutableArray *_filterCurrentPageModels;
  NSString *_unavailableSongsMessage;
  NSString *_licensedMusicEligibilityState;
  long long _filteredTypes;
}

@property (readonly, nonatomic) unsigned long long count;
@property (weak, nonatomic) NSObject<IGAudioModelsPaginatedListDelegate> *delegate;

/* instance methods */
- (id)initWithUserSession:(id)session firstPage:(id)page productName:(id)name;
- (id)objectAtIndexedSubscript:(unsigned long long)subscript;
- (id)subarrayWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* IGAudioModelsPaginatedList_h */
