//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAudioBrowserTabController_h
#define IGAudioBrowserTabController_h
@import Foundation;

#include "UIViewController.h"
#include "IGAudioBrowserArtistSpotlightCellModel.h"
#include "IGAudioBrowserArtistSpotlightView.h"
#include "IGAudioBrowserLogger-Protocol.h"
#include "IGAudioBrowserTabBar.h"
#include "IGGestureHandler-Protocol.h"
#include "IGMediaTextButton.h"
#include "IGPageViewController.h"
#include "IGPageViewControllerDataSource-Protocol.h"
#include "IGPageViewControllerDelegate-Protocol.h"
#include "IGStoryMusicBrowserNavigationBar.h"
#include "IGUserSession.h"

@class CALayer, NSArray, NSString;
@protocol IGAudioBrowserTabControllerDelegate;

@interface IGAudioBrowserTabController : UIViewController<IGPageViewControllerDelegate, IGPageViewControllerDataSource, IGGestureHandler> {
  /* instance variables */
  NSArray *_contentViewControllers;
  unsigned long long _initialIndex;
  IGUserSession *_userSession;
  NSObject<IGAudioBrowserLogger> *_logger;
  IGAudioBrowserArtistSpotlightView *_spotlightView;
  IGAudioBrowserTabBar *_tabBar;
  CALayer *_tabBarUnderlineSeparator;
  IGPageViewController *_pageViewController;
  IGMediaTextButton *_savedButton;
  IGStoryMusicBrowserNavigationBar *_navigationBar;
  BOOL _browserTabNavigationBarHidden;
  BOOL _savedButtonHidden;
  IGAudioBrowserArtistSpotlightCellModel *_spotlightCellModel;
}

@property (weak, nonatomic) NSObject<IGAudioBrowserTabControllerDelegate> *delegate;
@property (nonatomic) long long theme;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContentViewControllers:(id)controllers initialIndex:(unsigned long long)index userSession:(id)session logger:(id)logger;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)musicBrowserTabBar:(id)bar didTapOnTabAtIndex:(long long)index;
- (void)pageViewControllerDidScroll:(id)scroll;
- (BOOL)pageViewController:(id)controller touchesShouldCancelInContentView:(id)view;
- (BOOL)pageViewControllerShouldStopSwiping:(id)swiping gestureRecognizer:(id)recognizer;
- (long long)numberOfPagesForPageViewController:(id)controller;
- (id)pageViewController:(id)controller controllerForIndex:(long long)index;
- (BOOL)canRespondToGesture:(id)gesture;
- (struct { double x0; BOOL x1; })navigationAnimationTraits;
- (void)_didTapSavedButton;
- (void)didTapNavigationBar:(id)bar;
- (void)_didTapBackButton:(id)button;
- (void)spotlightView:(id)view didTapAudioPageForAudioTrack:(id)track pivotPageSessionId:(id)id;
@end

#endif /* IGAudioBrowserTabController_h */
