//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGBeforeAndAfterStickerCreationViewController_h
#define IGBeforeAndAfterStickerCreationViewController_h
@import Foundation;

#include "UIViewController.h"
#include "IGBeforeAndAfterStickerView.h"
#include "IGGradientView.h"
#include "IGKeyboardObserver.h"
#include "IGKeyboardObserverHideDelegate-Protocol.h"
#include "IGKeyboardObserverShowDelegate-Protocol.h"
#include "IGPassthroughView.h"
#include "IGPromptlessPromptStickerView.h"
#include "IGStickerDiceInputAccessoryView.h"
#include "IGStickerEditingHeaderView.h"
#include "IGStickerEditingHeaderViewDismissalDelegate-Protocol.h"
#include "IGStoryGalleryViewController.h"
#include "IGStoryGalleryViewControllerDelegate-Protocol.h"
#include "IGStoryStickerEditingViewControllerProtocol-Protocol.h"
#include "IGUserSession.h"

@class NSArray, NSString, UITapGestureRecognizer, UIView;
@protocol IGBeforeAndAfterStickerCreationViewControllerDelegate;

@interface IGBeforeAndAfterStickerCreationViewController : UIViewController<IGStickerEditingHeaderViewDismissalDelegate, IGStoryGalleryViewControllerDelegate, IGKeyboardObserverShowDelegate, IGKeyboardObserverHideDelegate, IGStoryStickerEditingViewControllerProtocol> {
  /* instance variables */
  IGUserSession *_userSession;
  IGBeforeAndAfterStickerView *_beforeStickerView;
  IGBeforeAndAfterStickerView *_afterStickerView;
  IGPromptlessPromptStickerView *_promptStickerView;
  IGPassthroughView *_contentWrapperView;
  IGStickerEditingHeaderView *_headerView;
  UIView *_dimmingView;
  UITapGestureRecognizer *_tapGesture;
  IGKeyboardObserver *_keyboardObserver;
  BOOL _stickerWasNewlyCreated;
  BOOL _tappedCancelButton;
  IGStoryGalleryViewController *_storyGalleryViewController;
  IGGradientView *_legibilityGradient;
  IGStickerDiceInputAccessoryView *_diceAccessoryView;
  NSArray *_prompts;
  long long _promptIndex;
  BOOL _hasInitiallyLaidOutStickers;
  BOOL _editing;
  IGBeforeAndAfterStickerView *_currentStickerViewForMediaPicker;
  long long _initialEditingState;
}

@property (weak, nonatomic) NSObject<IGBeforeAndAfterStickerCreationViewControllerDelegate> *delegate;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } contentRegion;
@property (nonatomic) double contentRegionCornerRadius;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSArray *backgroundViews;
@property (readonly, nonatomic) UIView *editableStickerView;
@property (readonly, nonatomic) double editableStickerScaleWhileEditing;
@property (readonly, nonatomic) BOOL editableStickerViewIsNewlyCreated;
@property (readonly, nonatomic) BOOL shouldDisableZoomTransitionOnEditStart;
@property (readonly, nonatomic) BOOL shouldDiscardStickerOnDismissal;
@property (readonly, nonatomic) NSString *stickerEditSessionLoggingId;
@optional
@property (readonly, nonatomic) NSArray *secondaryEditableStickerViews;

/* instance methods */
- (id)initWithBeforeStickerView:(id)view afterStickerView:(id)view promptStickerView:(id)view prompts:(id)prompts userSession:(id)session;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)appear;
- (void)viewWillDisappear:(BOOL)disappear;
- (void)viewDidLayoutSubviews;
- (void)_didTapBackground:(id)background;
- (void)beforeAndAfterStickerViewDidTap:(id)tap;
- (void)beforeAndAfterStickerViewDidReturn:(id)return;
- (void)storyGalleryViewController:(id)controller didSelectAssets:(id)assets;
- (void)storyGalleryViewController:(id)controller didSelectCameraCell:(id)cell;
- (void)storyGalleryViewController:(id)controller didSetMultiSelectEnabled:(BOOL)enabled animated:(BOOL)animated;
- (void)storyGalleryViewController:(id)controller didSelectDraft:(id)draft withDraftGallery:(id)gallery;
- (void)storyGalleryViewControllerDidUpdateGalleryPermissions:(id)permissions;
- (void)storyGalleryViewController:(id)controller didShareToStory:(long long)story exitPoint:(long long)point directRecipients:(id)recipients storyModelArray:(id)array metadataArray:(id)array;
- (void)storyGalleryViewControllerDidChangeAlbum:(id)album;
- (void)storyGalleryViewController:(id)controller didSelectImage:(id)image;
- (void)stickerEditingHeaderViewDidTapToDismiss:(id)dismiss withDismissalSource:(long long)source;
- (void)diceInputAccessoryViewDidTapDice:(id)dice;
- (void)keyboardObserver:(id)observer keyboardWillShowWithBeginFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame endFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame duration:(double)duration curve:(long long)curve;
- (void)keyboardObserverKeyboardDidShow:(id)show;
- (void)keyboardObserver:(id)observer keyboardWillHideWithBeginFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame endFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame duration:(double)duration curve:(long long)curve;
- (void)keyboardObserverKeyboardDidHide:(id)hide;
- (BOOL)canRespondToGesture:(id)gesture;
@end

#endif /* IGBeforeAndAfterStickerCreationViewController_h */
