//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGBezierSubpathEnumerationContext_h
#define IGBezierSubpathEnumerationContext_h
@import Foundation;

@class UIBezierPath;

@interface IGBezierSubpathEnumerationContext : NSObject {
  /* instance variables */
  BOOL _stop;
  BOOL _currentPathHasContent;
  id /* block */ _enumerationBlock;
  UIBezierPath *_currentPath;
}

/* instance methods */
@end

#endif /* IGBezierSubpathEnumerationContext_h */
