//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGCoreGraphicsKeyframesNode_h
#define IGCoreGraphicsKeyframesNode_h
@import Foundation;

#include "IGCoreGraphicsNode.h"
#include "NSSecureCoding-Protocol.h"

@class CALayer;

@interface IGCoreGraphicsKeyframesNode : IGCoreGraphicsNode<NSSecureCoding> {
  /* instance variables */
  CALayer *_layer;
}

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithKeyframesView:(id)view;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (void)drawInContext:(struct CGContext *)context;
@end

#endif /* IGCoreGraphicsKeyframesNode_h */
