//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectTypingStatus_h
#define IGDirectTypingStatus_h
@import Foundation;

@class NSDate, NSString;

@interface IGDirectTypingStatus : NSObject {
  /* instance variables */
  long long _typingStatusType;
}

@property (readonly, nonatomic) NSString *threadId;
@property (readonly, nonatomic) NSString *userPk;
@property (readonly, nonatomic) NSDate *sentDate;
@property (readonly, nonatomic) BOOL isActive;
@property (readonly, nonatomic) double lifetime;

/* instance methods */
- (id)initWithThreadId:(id)id userPk:(id)pk sentDate:(id)date isActive:(BOOL)active lifetime:(double)lifetime typingStatusType:(long long)type;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* IGDirectTypingStatus_h */
