//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectThreadSubscriptionUpdateReason_h
#define IGDirectThreadSubscriptionUpdateReason_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "IGDirectMutationOptimisticUpdateInfo.h"
#include "IGDirectPublishedThreadSubscriptionUpdateReason.h"

@interface IGDirectThreadSubscriptionUpdateReason : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  IGDirectPublishedThreadSubscriptionUpdateReason *_threadUpdated;
  IGDirectMutationOptimisticUpdateInfo *_optimisticStateUpdated_updateReason;
}

/* class methods */
+ (id)optimisticStateUpdatedWithUpdateReason:(id)reason;
+ (id)threadUpdated:(id)updated;

/* instance methods */
@end

#endif /* IGDirectThreadSubscriptionUpdateReason_h */
