//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectPhoto_h
#define IGDirectPhoto_h
@import Foundation;

#include "IGAPIMediaOverlayPayloadSchema.h"
#include "IGDirectItemIdBasedImageURLProcessor.h"
#include "IGDirectMediaResolverContext.h"
#include "IGDirectMessageAuxiliaryContent.h"
#include "IGDirectMessagePaidPartnershipMetadata.h"
#include "IGDirectMessageReplyable-Protocol.h"
#include "IGDirectPowerupsMetadata.h"
#include "IGDirectUIMessage.h"
#include "IGDirectUIMessageProviding-Protocol.h"
#include "IGPhoto.h"

@class NSData, NSNumber, NSString;

@interface IGDirectPhoto : NSObject<IGDirectUIMessageProviding, IGDirectMessageReplyable> {
  /* instance variables */
  NSNumber *_isFilmstripSeen;
}

@property (readonly, nonatomic) IGDirectUIMessage *message;
@property (readonly, nonatomic) NSData *imageData;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } size;
@property (readonly, nonatomic) IGDirectMediaResolverContext *mediaResolverContext;
@property (readonly, nonatomic) IGAPIMediaOverlayPayloadSchema *mediaOverlayInfo;
@property (readonly, nonatomic) IGPhoto *photo;
@property (readonly, nonatomic) IGDirectPowerupsMetadata *powerupsMetadata;
@property (readonly, nonatomic) IGDirectMessageAuxiliaryContent *auxiliaryContent;
@property (readonly, nonatomic) IGDirectMessagePaidPartnershipMetadata *paidPartnershipMetadata;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) IGDirectItemIdBasedImageURLProcessor *previewImageURLProcessor;

/* instance methods */
- (id)initWithMessage:(id)message imageData:(id)data photo:(id)photo mediaResolverContext:(id)context size:(struct CGSize { double x0; double x1; })size isFilmstripSeen:(id)seen paidPartnershipMetadata:(id)metadata mediaOverlayInfo:(id)info;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mediaViewerSpecifier;
- (id)replyMediaViewerSpecifier;
- (unsigned long long)messageType;
- (id)contentTypeString;
- (id)messageId;
- (id)replyable;
- (BOOL)hideInThread;
- (id)actionSummaryProvider;
- (id)replyableConfigurationMedia;
- (long long)replyableConfigurationMediaViewMode;
- (long long)replyType;
- (BOOL)isEqual:(id)equal;
@end

#endif /* IGDirectPhoto_h */
