//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectRecipientInterestBasedChatsDataManager_h
#define IGDirectRecipientInterestBasedChatsDataManager_h
@import Foundation;

#include "IGAPIClient-Protocol.h"
#include "IGDirectRecipientInterestBasedChatsFetcher.h"
#include "IGDiskManager.h"
#include "IGUser.h"
#include "IGUserLauncherSetProviding-Protocol.h"

@class NSArray, NSMutableDictionary;
@protocol IGDirectChannelsDataManagerAnnouncer, IGDirectRecipientInterestBasedDataManagerDelegate;

@interface IGDirectRecipientInterestBasedChatsDataManager : NSObject {
  /* instance variables */
  NSArray *_activeChannelRankViewTypes;
  IGDiskManager *_diskManager;
  IGUser *_currentSender;
  IGDirectRecipientInterestBasedChatsFetcher *_fetcher;
  NSMutableDictionary *_channelsOnDiskStorage;
  NSMutableDictionary *_channelsInMemoryCache;
  NSObject<IGUserLauncherSetProviding> *_featureSets;
  NSObject<IGAPIClient> *_networker;
  NSObject<IGDirectChannelsDataManagerAnnouncer> *_announcer;
}

@property (weak, nonatomic) NSObject<IGDirectRecipientInterestBasedDataManagerDelegate> *delegate;

/* instance methods */
- (id)initWithActiveChannelRankViewTypes:(id)types diskManager:(id)manager currentSender:(id)sender userStore:(id)store mediaStore:(id)store networker:(id)networker featureSets:(id)sets;
- (void)_writeUpdatedCollectonToStorageWithRankViewIdentifier:(id)identifier updatedCollection:(id)collection;
- (void)_logChannelReadFromDisk:(id)disk rankViewIdentifier:(id)identifier;
- (void)_logChannelFetchedFromNetwork:(id)network rankViewIdentifier:(id)identifier;
- (void)_logChannelViewToRefresh:(id)refresh;
- (id)_channelViewsToRefresh;
- (void)_handleChannelsFetchedFromServer:(id)server expectedExpirationDateByRankViewIdentifiers:(id)identifiers;
- (void)markChannelInvitationVisibilityForThreadId:(id)id hidden:(BOOL)hidden;
- (void)addListener:(id)listener;
- (void)removeListener:(id)listener;
@end

#endif /* IGDirectRecipientInterestBasedChatsDataManager_h */
