//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectAvatarView_h
#define IGDirectAvatarView_h
@import Foundation;

#include "UIView.h"
#include "IGDirectAvatarDotView.h"
#include "IGDirectAvatarState.h"
#include "IGDirectAvatarViewSpec.h"
#include "IGProfilePictureImageView.h"
#include "IGRingViewSpec.h"
#include "IGStoryGradientRingView.h"
#include "IGStoryViewerEntryView-Protocol.h"

@class CAShapeLayer, NSArray, NSString, UIView;
@protocol IGDirectAvatarViewDelegate;

@interface IGDirectAvatarView : UIView<IGStoryViewerEntryView> {
  /* instance variables */
  long long _currentlyDisplayedDotSpecTickCount;
  IGDirectAvatarDotView *_dotView;
  IGDirectAvatarDotView *_dotView2;
  NSArray *_dotSpecs;
  UIView *_profileImageContainerView;
  IGProfilePictureImageView *_frontProfileView;
  IGProfilePictureImageView *_backProfileView;
  CAShapeLayer *_innerFrontRing;
  CAShapeLayer *_innerBackRing;
  CAShapeLayer *_innerBackProfileMask;
  IGStoryGradientRingView *_frontGradientRing;
  IGStoryGradientRingView *_backGradientRing;
  CAShapeLayer *_frontGradientRingMask;
  CAShapeLayer *_backGradientRingMask;
  IGDirectAvatarViewSpec *_spec;
  CAShapeLayer *_dotMaskLayer;
  IGRingViewSpec *_outterRingSpec;
  NSString *_firstUserPk;
  NSString *_secondUserPk;
}

@property (retain, nonatomic) IGDirectAvatarState *state;
@property (nonatomic) BOOL loggingEnabled;
@property (weak, nonatomic) NSObject<IGDirectAvatarViewDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithSpec:(id)spec loggingEnabled:(BOOL)enabled;
- (id)initWithSpec:(id)spec;
- (void)configureWithSpec:(id)spec;
- (void)startLoading;
- (void)layoutSubviews;
- (void)_dotViewTapped;
- (void)setLoading:(BOOL)loading;
- (id)profilePicture;
- (id)gradientRingView;
- (id)previewImageView;
- (id)accessoryView;
@end

#endif /* IGDirectAvatarView_h */
