//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectDefaultThreadServiceRequestProvider_h
#define IGDirectDefaultThreadServiceRequestProvider_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString;

@interface IGDirectDefaultThreadServiceRequestProvider : NSObject<NSObject>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)urlRequestForCreateThreadWithUserIds:(id)ids name:(id)name source:(id)source adId:(id)id threadType:(unsigned long long)type completion:(id /* block */)completion;
@end

#endif /* IGDirectDefaultThreadServiceRequestProvider_h */
