//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectOutgoingMessageContentMatcher_h
#define IGDirectOutgoingMessageContentMatcher_h
@import Foundation;

@interface IGDirectOutgoingMessageContentMatcher : NSObject
/* class methods */
+ (id)match:(id)match text:(id /* block */)text like:(id /* block */)like reshare:(id /* block */)reshare link:(id /* block */)link media:(id /* block */)media sticker:(id /* block */)sticker cameraEffectPreview:(id /* block */)preview forward:(id /* block */)forward pollMessage:(id /* block */)message pollMessageInteraction:(id /* block */)interaction prompt:(id /* block */)prompt promptContribution:(id /* block */)contribution sharedAlbum:(id /* block */)album;
@end

#endif /* IGDirectOutgoingMessageContentMatcher_h */
