//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectComposerLayoutSpec_h
#define IGDirectComposerLayoutSpec_h
@import Foundation;

#include "IGDirectComposerAttachmentViewSpec.h"
#include "IGDirectComposerButtonGroupConfig.h"

@class NSMutableArray, NSString, UIColor;

@interface IGDirectComposerLayoutSpec : NSObject

@property (readonly, nonatomic) IGDirectComposerAttachmentViewSpec *attachmentViewSpec;
@property (readonly, nonatomic) IGDirectComposerButtonGroupConfig *leftButtonGroup;
@property (readonly, nonatomic) IGDirectComposerButtonGroupConfig *leftOvalInsetButtonGroup;
@property (readonly, nonatomic) IGDirectComposerButtonGroupConfig *rightOvalInsetButtonGroup;
@property (readonly, nonatomic) IGDirectComposerButtonGroupConfig *rightButtonGroup;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } ovalInset;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } composerInsets;
@property (readonly, nonatomic) UIColor *activeCaretTintColor;
@property (readonly, nonatomic) NSString *placeholderText;
@property (readonly, nonatomic) NSString *placeholderAccessibilityText;
@property (readonly, nonatomic) long long placeholderLineBreakMode;
@property (readonly, nonatomic) BOOL placeholderGradientTruncationViewVisible;
@property (readonly, nonatomic) unsigned long long placeholderPresenceStyle;
@property (readonly, nonatomic) NSMutableArray *overflowButtonMenuItemGroup;

/* instance methods */
- (id)initWithAttachmentViewSpec:(id)spec leftButtonGroup:(id)group leftOvalInsetButtonGroup:(id)group rightOvalInsetButtonGroup:(id)group rightButtonGroup:(id)group ovalInset:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })inset composerInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })insets activeCaretTintColor:(id)color placeholderText:(id)text placeholderAccessibilityText:(id)text placeholderLineBreakMode:(long long)mode placeholderGradientTruncationViewVisible:(BOOL)visible placeholderPresenceStyle:(unsigned long long)style overflowButtonMenuItemGroup:(id)group;
@end

#endif /* IGDirectComposerLayoutSpec_h */
