//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectMessageCellThemeCache_h
#define IGDirectMessageCellThemeCache_h
@import Foundation;

#include "IGDirectMessageCellThemeWriting-Protocol.h"

@class NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface IGDirectMessageCellThemeCache : NSObject<IGDirectMessageCellThemeWriting> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_queue;
  NSDictionary *_internalThreadMessageAppearanceCache;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithQueue:(id)queue;
- (id)themeForCacheKey:(id)key;
- (void)writeMessageCellTheme:(id)theme forCacheKey:(id)key;
@end

#endif /* IGDirectMessageCellThemeCache_h */
