//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectE2EEIncomingPayloadHandler_h
#define IGDirectE2EEIncomingPayloadHandler_h
@import Foundation;

@interface IGDirectE2EEIncomingPayloadHandler : NSObject
/* class methods */
+ (BOOL)handleIncomingPayloadWithContext:(struct __MEMDecryptedPayloadContext *)context userSession:(id)session accountSession:(struct __MCIAccountSession *)session serializedData:(struct __MCFData *)data;
+ (BOOL)handleIncomingPlaceholderWithThreadId:(struct __MEMThreadID *)id userSession:(id)session accountSession:(struct __MCIAccountSession *)session messageId:(struct __MCFString *)id timestampInSec:(long long)sec placeholderType:(int)type senderJID:(struct __WCFDeviceJID *)jid;
+ (BOOL)handleIncomingAdminMessageWithContext:(struct __MEMDeviceAdminMessagePayloadContext *)context userSession:(id)session accountSession:(struct __MCIAccountSession *)session;
@end

#endif /* IGDirectE2EEIncomingPayloadHandler_h */
