//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDSHeadlineViewHeader_h
#define IGDSHeadlineViewHeader_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "IGImageSpecifier.h"
#include "IGProfileImage.h"

@class UIImage, UIView;

@interface IGDSHeadlineViewHeader : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  UIImage *_image;
  IGProfileImage *_profileImage;
  IGImageSpecifier *_imageSpecifier;
  unsigned long long _icon;
  UIView *_customView_view;
  long long _customView_sizingMode;
}

/* class methods */
+ (id)customViewWithView:(id)view sizingMode:(long long)mode;
+ (id)icon:(unsigned long long)icon;
+ (id)image:(id)image;
+ (id)imageSpecifier:(id)specifier;
+ (id)profileImage:(id)image;

/* instance methods */
@end

#endif /* IGDSHeadlineViewHeader_h */
