//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGGradientView_h
#define IGGradientView_h
@import Foundation;

#include "UIView.h"
#include "IGGradient.h"

@class NSArray;

@interface IGGradientView : UIView

@property (retain, nonatomic) IGGradient *gradient;
@property (retain, nonatomic) NSArray *colors;
@property (nonatomic) long long gradientDirection;
@property (retain, nonatomic) NSArray *locations;

/* class methods */
+ (Class)layerClass;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame gradient:(id)gradient;
- (void)traitCollectionDidChange:(id)change;
@end

#endif /* IGGradientView_h */
