//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGImageRenderSource_h
#define IGImageRenderSource_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "NSCoding-Protocol.h"

@class NSNumber, NSString, UIImage;

@interface IGImageRenderSource : FBIvarBasedEqualityObject<NSCoding> {
  /* instance variables */
  unsigned long long _subtype;
  UIImage *_image_image;
  struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _image_cropRect;
  NSNumber *_image_originalIsHDR;
  NSNumber *_image_originalHDRGainMapVersion;
  NSString *_photoAsset_assetLocalIdentifier;
  struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _photoAsset_downscaledImageCropRect;
  struct CGSize { double width; double height; } _photoAsset_downscaledImageSize;
  BOOL _photoAsset_isDraft;
  NSString *_fileRelativePath_imageDataFileRelativePath;
  NSString *_fileRelativePath_filename;
  struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _fileRelativePath_fileCropRect;
}

/* class methods */
+ (id)fileRelativePathWithImageDataFileRelativePath:(id)path filename:(id)filename fileCropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
+ (id)imageWithImage:(id)image cropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect originalIsHDR:(id)hdr originalHDRGainMapVersion:(id)version;
+ (id)photoAssetWithAssetLocalIdentifier:(id)identifier downscaledImageCropRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect downscaledImageSize:(struct CGSize { double x0; double x1; })size isDraft:(BOOL)draft;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* IGImageRenderSource_h */
