//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGLocationMainFeedDataController_h
#define IGLocationMainFeedDataController_h
@import Foundation;

#include "IGAPILocationDict.h"
#include "IGDiscoveryGridDataValidationBehavior.h"
#include "IGSessionTracker.h"
#include "IGUserSession.h"
#include "NSObject-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol IGLocationMainFeedDataControllerDelegate;

@interface IGLocationMainFeedDataController : NSObject<NSObject> {
  /* instance variables */
  IGAPILocationDict *_location;
  NSString *_fbPlaceID;
  IGUserSession *_userSession;
  IGDiscoveryGridDataValidationBehavior *_validationBehavior;
  NSMutableDictionary *_locationFeedTypeToSingleDataControllerMap;
  NSObject<IGLocationMainFeedDataControllerDelegate> *_locationDataControllerDelegate;
}

@property (readonly, nonatomic) IGSessionTracker *sessionTracker;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithLocation:(id)location userSession:(id)session validationBehavior:(id)behavior fbPlaceID:(id)id;
- (void)locationMainFeedSingleDataController:(id)controller didCompleteRequestForMainFeedType:(long long)type withDataStore:(id)store isLoadMore:(BOOL)more;
- (void)locationMainFeedSingleDataController:(id)controller didFetchLocation:(id)location;
- (void)locationMainFeedSingleDataController:(id)controller didFailWithError:(id)error;
@end

#endif /* IGLocationMainFeedDataController_h */
