//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGLUImageSourceSplitFilter_h
#define IGLUImageSourceSplitFilter_h
@import Foundation;

#include "ImageSourceFilter.h"
#include "IGLUImageSourceFilter.h"

@interface IGLUImageSourceSplitFilter : ImageSourceFilter {
  /* instance variables */
  IGLUImageSourceFilter *_leftFilter;
  IGLUImageSourceFilter *_rightFilter;
  double _leftRatio;
}

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithLeftFilter:(id)filter rightFilter:(id)filter leftRatio:(double)ratio;
- (id)imageSourceProcessorWithContext:(id)context error:(id *)error;
- (BOOL)supportsHDR;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })minFrameDuration:(struct { long long x0; int x1; unsigned int x2; long long x3; })duration;
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* IGLUImageSourceSplitFilter_h */
