//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGMainAppSurfaceIntentMatcher_h
#define IGMainAppSurfaceIntentMatcher_h
@import Foundation;

@interface IGMainAppSurfaceIntentMatcher : NSObject
/* class methods */
+ (id)match:(id)match timeline:(id /* block */)timeline explore:(id /* block */)explore discoverVideo:(id /* block */)video posting:(id /* block */)posting news:(id /* block */)news shareSheet:(id /* block */)sheet mediaShareSheet:(id /* block */)sheet profile:(id /* block */)profile settings:(id /* block */)settings storiesCamera:(id /* block */)camera cameraEffectPreview:(id /* block */)preview liveCamera:(id /* block */)camera reelsCamera:(id /* block */)camera directInbox:(id /* block */)inbox directInboxCamera:(id /* block */)camera directPendingInbox:(id /* block */)inbox directNew:(id /* block */)new directThread:(id /* block */)thread directInvitesForChannels:(id /* block */)channels directNotes:(id /* block */)notes channelComment:(id /* block */)comment promptXMACamera:(id /* block */)xmacamera menu:(id /* block */)menu professionalDashboard:(id /* block */)dashboard yourActivity:(id /* block */)activity discoveryMap:(id /* block */)map friendsMap:(id /* block */)map threadsSearch:(id /* block */)search threadsActivity:(id /* block */)activity opalProfile:(id /* block */)profile notePromptResponses:(id /* block */)responses extensionSharing:(id /* block */)sharing;
@end

#endif /* IGMainAppSurfaceIntentMatcher_h */
