//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGMediaUploadPerformanceLogger_h
#define IGMediaUploadPerformanceLogger_h
@import Foundation;

@class NSMutableDictionary;

@interface IGMediaUploadPerformanceLogger : NSObject {
  /* instance variables */
  NSMutableDictionary *_postIdToPerformanceMarker;
  int _markerID;
}

/* instance methods */
- (id)initWithType:(unsigned long long)type;
@end

#endif /* IGMediaUploadPerformanceLogger_h */
