//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGNetegoAdPlatformSponsoredItemWrapper_h
#define IGNetegoAdPlatformSponsoredItemWrapper_h
@import Foundation;

#include "IGAdGapRuleEnforceable-Protocol.h"
#include "IGAdPlatformGapRules.h"
#include "IGAdPlatformSponsoredItemInfoProviding-Protocol.h"
#include "IGNetegoItem-Protocol.h"
#include "IGUnitItemInformationProviding-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSString;

@interface IGNetegoAdPlatformSponsoredItemWrapper : NSObject<IGAdPlatformSponsoredItemInfoProviding, IGUnitItemInformationProviding, IGAdGapRuleEnforceable, NSCopying> {
  /* instance variables */
  NSObject<IGNetegoItem> *_netegoItem;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) IGAdPlatformGapRules *gapRules;

/* instance methods */
- (id)initWithNetegoItem:(id)item;
- (id)unitItemId;
- (unsigned long long)unitItemType;
- (unsigned long long)serverViewStateItemType;
- (long long)priorityIndex;
- (long long)targetInsertionPosition;
- (id)adPlatformSponsoredItemId;
- (id)adPlatformMetadata;
- (id)adPlatformInvalidationInfo;
- (id)invalidationRules;
- (id)mediaPk;
- (id)adTrackingToken;
- (id)adPodId;
- (long long)indexInAdPod;
- (long long)numAdsInAdPod;
- (void)clearAdPodInfo;
- (id)instantiatedAtDate;
- (id)inventorySource;
- (unsigned long long)deliveryContext;
- (id)appId;
- (id)adExpiryTimestamp;
- (id)adRefreshThresholdTimestamp;
- (long long)adRefreshTTLInSecs;
- (BOOL)isEligibleForCrossSessionCarryOver;
- (long long)multiAdsType;
- (BOOL)shouldBeReportedToAdAndNetegoRequestInformation;
- (BOOL)hasMobileAppInstallObjective;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)setResponseDictionary:(id)dictionary;
- (id)responseDictionary;
@end

#endif /* IGNetegoAdPlatformSponsoredItemWrapper_h */
