//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGPostExternalShareLogger_h
#define IGPostExternalShareLogger_h
@import Foundation;

#include "FBMediaUploadFlowLogger.h"
#include "IGPostLoggingContext.h"
#include "IGPostSessionLogger.h"
#include "IGPostShareLogger.h"

@class NSString;
@protocol IGPostExternalShareLoggerDelegate;

@interface IGPostExternalShareLogger : NSObject {
  /* instance variables */
  long long _shareType;
  NSString *_shareId;
  IGPostLoggingContext *_loggingContext;
  IGPostShareLogger *_shareLogger;
  IGPostSessionLogger *_sessionLogger;
  FBMediaUploadFlowLogger *_fbLogger;
  NSObject<IGPostExternalShareLoggerDelegate> *_delegate;
}

/* class methods */
+ (id)externalShareLoggerWithWaterfall:(id)waterfall shareId:(id)id dataType:(long long)type entryPointType:(long long)type shareIntent:(id)intent analyticsModule:(id)module accountType:(long long)type videoRenderQueue:(id)queue logger:(id)logger launcherSet:(id)set delegate:(id)delegate;

/* instance methods */
- (id)initWithShareWithShareType:(long long)type shareId:(id)id loggingContext:(id)context logger:(id)logger delegate:(id)delegate launcherSet:(id)set;
- (void)logPublishInvoke;
- (void)logPublishSuccessWithMediaId:(id)id;
- (void)logPublishFailureWithError:(id)error mediaId:(id)id;
- (void)logShareCancelledForReason:(id)reason;
@end

#endif /* IGPostExternalShareLogger_h */
