//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGQuizStickerOptionIndexAccessoryView_h
#define IGQuizStickerOptionIndexAccessoryView_h
@import Foundation;

#include "UIView.h"
#include "IGGradientView.h"

@class CAShapeLayer, NSArray, UILabel, UIView;

@interface IGQuizStickerOptionIndexAccessoryView : UIView {
  /* instance variables */
  CAShapeLayer *_placeholderCircleLayer;
  UILabel *_placeholderIndexLabel;
  IGGradientView *_normalGradientView;
  UIView *_normalGradientMaskView;
  CAShapeLayer *_normalGradientMaskCircle;
  UILabel *_normalGradientMaskLabel;
  IGGradientView *_filledGradientView;
  CAShapeLayer *_filledGradientMaskCircle;
  UILabel *_filledGradientLabel;
  NSArray *_colorSchemeColors;
}

@property (nonatomic) long long index;
@property (nonatomic) unsigned long long style;

/* instance methods */
- (id)init;
- (void)layoutSubviews;
@end

#endif /* IGQuizStickerOptionIndexAccessoryView_h */
