//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGResharedPhotoStickerModel_h
#define IGResharedPhotoStickerModel_h
@import Foundation;

#include "FBXPostingNativeFeature.h"
#include "IGPhoto.h"
#include "IGResharedMediaStickerAttachmentSpec.h"
#include "IGStickerModelType-Protocol.h"
#include "IGUser.h"
#include "NSSecureCoding-Protocol.h"

@class NSArray, NSString, NSURL, UIImage;

@interface IGResharedPhotoStickerModel : NSObject<NSSecureCoding, IGStickerModelType> {
  /* instance variables */
  BOOL _hideUserAttribution;
  BOOL _isIneligibleForFBShare;
  BOOL _isSuggestedStory;
  BOOL _isTapToAdvanceEnabled;
  FBXPostingNativeFeature *_iGToFBEligiblityID;
  IGUser *_reactionRecipient;
}

@property (readonly, copy, nonatomic) NSString *pk;
@property (readonly, copy, nonatomic) NSURL *userProfilePictureUrl;
@property (readonly, copy, nonatomic) NSString *username;
@property (readonly, nonatomic) NSURL *mediaImageUrl;
@property (readonly, nonatomic) UIImage *localImage;
@property (readonly, nonatomic) double aspectRatio;
@property (readonly, nonatomic) IGUser *user;
@property (readonly, nonatomic) IGPhoto *previewPhoto;
@property (readonly, nonatomic) BOOL isResharedMediaIdOwnedByViewer;
@property (readonly, nonatomic) IGResharedMediaStickerAttachmentSpec *attachmentSpec;
@property (readonly, nonatomic) long long stickerStyle;
@property (readonly, nonatomic) NSArray *availableStyles;
@property (readonly, nonatomic) NSString *caption;
@property (readonly, nonatomic) BOOL includeInRecent;
@property (nonatomic) BOOL isBoostEligible;
@property (copy, nonatomic) NSString *stickerSection;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithPk:(id)pk userProfilePictureUrl:(id)url username:(id)username mediaImageUrl:(id)url localImage:(id)image aspectRatio:(double)ratio user:(id)user previewPhoto:(id)photo hideUserAttribution:(BOOL)attribution attachmentSpec:(id)spec isIneligibleForFBShare:(BOOL)fbshare iGToFBEligiblityID:(id)id isResharedMediaIdOwnedByViewer:(BOOL)viewer reactionRecipient:(id)recipient stickerStyle:(long long)style availableStyles:(id)styles isSuggestedStory:(BOOL)story isTapToAdvanceEnabled:(BOOL)enabled caption:(id)caption;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* IGResharedPhotoStickerModel_h */
