//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSearchTypeaheadCacheDataSource_h
#define IGSearchTypeaheadCacheDataSource_h
@import Foundation;

#include "IGKeywordsBootstrapHelper.h"
#include "IGUserListLocalDataSource.h"
#include "IGUserSession.h"
#include "NSObject-Protocol.h"

@class NSString;

@interface IGSearchTypeaheadCacheDataSource : NSObject<NSObject> {
  /* instance variables */
  IGUserSession *_userSession;
  unsigned long long _searchType;
  unsigned long long _cacheMaxResultCount;
  IGKeywordsBootstrapHelper *_keywordsBootstrapHelper;
  IGUserListLocalDataSource *_localUserDataSource;
  BOOL _doNotDelayKeywordBootstrapMatches;
}

@property (nonatomic) unsigned long long searchSet;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session searchType:(unsigned long long)type cacheMaxResultCount:(unsigned long long)count isParallelTypeaheadEnabled:(BOOL)enabled;
- (id)cachedItemsForSearchText:(id)text;
- (id)onDeviceSuggestionsItemsForSearchText:(id)text;
- (id)cachedItemsForSearchText:(id)text serverResultsExist:(BOOL)exist;
- (id)cachedItemsAllowedForDelayWithSearchText:(id)text;
- (long long)typeaheadClientCacheSourceType;
- (BOOL)isDelayEnabled;
@end

#endif /* IGSearchTypeaheadCacheDataSource_h */
