//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGShareServiceConfigureManager_h
#define IGShareServiceConfigureManager_h
@import Foundation;

#include "IGAnalyticsStructuredLogger.h"
#include "IGBusinessFacebookConnectOrClaimPageFlowDelegate-Protocol.h"
#include "IGScopedListener-Protocol.h"
#include "IGUserSession.h"

@class NSString;
@protocol IGBusinessFacebookConnectOrClaimPageFlowPresenting, IGShareServiceConfigureManagerDelegate;

@interface IGShareServiceConfigureManager : NSObject<IGBusinessFacebookConnectOrClaimPageFlowDelegate, IGScopedListener> {
  /* instance variables */
  NSObject<IGBusinessFacebookConnectOrClaimPageFlowPresenting> *_connectPageFlow;
  long long _connectPageFlowSurface;
  IGAnalyticsStructuredLogger *_logger;
  long long _fxcalAddAccountFlowEntryPoint;
  NSString *_fxcalEntryPoint;
}

@property (readonly, nonatomic) IGUserSession *userSession;
@property (nonatomic) long long presentationStyle;
@property (weak, nonatomic) NSObject<IGShareServiceConfigureManagerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session;
- (void)_reloadData;
- (void)reauthFinishedForService:(long long)service;
- (void)reauthStartedForService:(long long)service;
- (void)reauthLoginNeededForService:(long long)service;
- (void)_onFacebookCurrentUserInfoLoaded;
- (void)_onFacebookHardLinked:(id)linked;
- (void)businessFacebookConnectPageFlow:(id)flow didFailWithError:(id)error;
- (void)businessFacebookConnectPageFlow:(id)flow didFinishAction:(long long)action;
- (void)businessFacebookConnectPageFlowDidDismiss:(id)dismiss;
- (void)igFacebookServiceHelperDidUpdateFacebookDestination:(id)destination;
- (void)igFacebookServiceHelperDidUpdateStoriesAutosettings:(id)autosettings isOn:(BOOL)on;
- (void)igFacebookServiceHelperDidUpdateReelsAdvancedSettings:(id)settings isOn:(BOOL)on shareMode:(unsigned long long)mode;
- (void)igFacebookServiceHelper:(id)helper didCloseAccountsCenterWithOpenEntrypoint:(id)entrypoint;
- (void)igFacebookServiceHelperDidUpdateFacebookCrossPostingDestinationPostAccountLink:(id)link;
@end

#endif /* IGShareServiceConfigureManager_h */
