//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGStoryItemHeaderBadgeSpec_h
#define IGStoryItemHeaderBadgeSpec_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"

@class NSArray, UIColor, UIImage;

@interface IGStoryItemHeaderBadgeSpec : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  UIImage *_multiAuthorStory_image;
  NSArray *_threadsStatus_statusEmojis;
  UIColor *_threadsStatus_backgroundColor;
  double _threadsStatus_fontSize;
}

/* class methods */
+ (id)multiAuthorStoryWithImage:(id)image;
+ (id)threadsStatusWithStatusEmojis:(id)emojis backgroundColor:(id)color fontSize:(double)size;

/* instance methods */
@end

#endif /* IGStoryItemHeaderBadgeSpec_h */
