//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGStoryMusicBrowserScrollableTabController_h
#define IGStoryMusicBrowserScrollableTabController_h
@import Foundation;

#include "UIViewController.h"
#include "IGAudioBrowserLogger-Protocol.h"
#include "IGCreationScrollableTabBar.h"
#include "IGGestureHandler-Protocol.h"
#include "IGPageViewController.h"
#include "IGPageViewControllerDataSource-Protocol.h"
#include "IGPageViewControllerDelegate-Protocol.h"
#include "IGUserSession.h"

@class NSArray, NSMutableDictionary, NSString;
@protocol IGAudioBrowserTabControllerDelegate;

@interface IGStoryMusicBrowserScrollableTabController : UIViewController<IGPageViewControllerDelegate, IGPageViewControllerDataSource, IGGestureHandler> {
  /* instance variables */
  NSArray *_contentViewControllers;
  NSMutableDictionary *_musicListTasks;
  unsigned long long _initialIndex;
  IGUserSession *_userSession;
  NSObject<IGAudioBrowserLogger> *_logger;
  IGCreationScrollableTabBar *_tabBar;
  IGPageViewController *_pageViewController;
}

@property (weak, nonatomic) NSObject<IGAudioBrowserTabControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContentViewControllers:(id)controllers prefetchedTracks:(id)tracks initialIndex:(unsigned long long)index userSession:(id)session logger:(id)logger;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)creationTabBar:(id)bar didSelectItemAtIndex:(long long)index;
- (void)pageViewControllerDidScroll:(id)scroll;
- (BOOL)pageViewController:(id)controller touchesShouldCancelInContentView:(id)view;
- (BOOL)pageViewControllerShouldStopSwiping:(id)swiping gestureRecognizer:(id)recognizer;
- (long long)numberOfPagesForPageViewController:(id)controller;
- (id)pageViewController:(id)controller controllerForIndex:(long long)index;
- (void)pageViewController:(id)controller didChangeCurrentViewController:(id)controller toController:(id)controller atIndex:(long long)index;
- (BOOL)canRespondToGesture:(id)gesture;
- (struct { double x0; BOOL x1; })navigationAnimationTraits;
@end

#endif /* IGStoryMusicBrowserScrollableTabController_h */
