//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGUploadVideoItem_h
#define IGUploadVideoItem_h
@import Foundation;

#include "FBValueObject.h"
#include "FBMediaUploadProtocolProvider-Protocol.h"
#include "IGImageUploadSource.h"
#include "IGVideoSource.h"
#include "IGVideoTranscodeOptions.h"
#include "NSCoding-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSDictionary, NSNumber, NSString;

@interface IGUploadVideoItem : FBValueObject<NSCopying, NSCoding>

@property (readonly, copy, nonatomic) IGVideoSource *videoSource;
@property (readonly, copy, nonatomic) IGVideoTranscodeOptions *transcodeOptions;
@property (readonly, copy, nonatomic) NSString *videoSegmentsOutputFolderPath;
@property (readonly, copy, nonatomic) NSString *mediaExportPath;
@property (readonly, copy, nonatomic) IGImageUploadSource *coverPhotoImageSource;
@property (readonly, nonatomic) BOOL useFirstFrameForCoverPhoto;
@property (readonly, copy, nonatomic) NSString *uploadId;
@property (readonly, copy, nonatomic) NSDictionary *uploadParams;
@property (readonly, copy, nonatomic) NSDictionary *additionalHeaders;
@property (readonly, copy, nonatomic) NSString *mediaKey;
@property (readonly, nonatomic) BOOL shouldMeasureQuality;
@property (readonly, copy, nonatomic) NSNumber *overrideSkipStatusCheck;
@property (readonly, nonatomic) NSObject<FBMediaUploadProtocolProvider> *uploadProtocolProvider;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithVideoSource:(id)source transcodeOptions:(id)options videoSegmentsOutputFolderPath:(id)path mediaExportPath:(id)path coverPhotoImageSource:(id)source useFirstFrameForCoverPhoto:(BOOL)photo uploadId:(id)id uploadParams:(id)params additionalHeaders:(id)headers mediaKey:(id)key shouldMeasureQuality:(BOOL)quality overrideSkipStatusCheck:(id)check uploadProtocolProvider:(id)provider;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* IGUploadVideoItem_h */
