//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGUserScopedObjects_IGLocationManager_h
#define IGUserScopedObjects_IGLocationManager_h
@import Foundation;

#include "IGAnalyticsEventLoggingProtocol-Protocol.h"
#include "IGThreadedLocationManager.h"
#include "NSObject-Protocol.h"

@class CLLocation, NSDate, NSString, NSTimer;
@protocol {atomic<CLAuthorizationStatus>="__a_"{__cxx_atomic_impl<CLAuthorizationStatus, std::__cxx_atomic_base_impl<CLAuthorizationStatus>>="__a_value"Ai}}, {atomic<bool>="__a_"{__cxx_atomic_impl<bool, std::__cxx_atomic_base_impl<bool>>="__a_value"AB}};

@interface IGUserScopedObjects (IGLocationManager)
/* instance methods */
- (id)locationManager;
@end

#endif /* IGUserScopedObjects_IGLocationManager_h */
