//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGVideoPlayerDisplayedFrameGenerator_h
#define IGVideoPlayerDisplayedFrameGenerator_h
@import Foundation;

#include "FNFPlayerDisplayEngine-Protocol.h"

@protocol OS_dispatch_queue;

@interface IGVideoPlayerDisplayedFrameGenerator : NSObject {
  /* instance variables */
  NSObject<FNFPlayerDisplayEngine> *_displayEngine;
  NSObject<OS_dispatch_queue> *_renderFrameQueue;
}

/* instance methods */
- (id)initWithDisplayEngine:(id)engine;
- (void)currentFrameWithCompletion:(id /* block */)completion;
- (id)_renderFrameQueue;
- (id)_context;
@end

#endif /* IGVideoPlayerDisplayedFrameGenerator_h */
