//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef KFCALayerImpl_h
#define KFCALayerImpl_h
@import Foundation;

#include "KFECSToolbox.h"

@class NSMutableArray, NSMutableSet;
@protocol CALayer<KFCALayerProtocol;

@interface KFCALayerImpl : NSObject {
  /* instance variables */
  unsigned long long _supportedProperties;
  NSMutableSet *_tags;
  NSMutableArray *_pendingCAActions;
  KFECSToolbox *_toolbox;
  CALayer<KFCALayerProtocol> *_layer;
}

@property (nonatomic) unsigned long long activeProperties;

/* instance methods */
- (id)initWithSupportedProperties:(unsigned long long)properties layer:(id)layer toolbox:(id)toolbox;
- (void)addTag:(id)tag;
- (BOOL)hasTag:(id)tag;
- (void)addCAAnimation:(id)caanimation;
- (void)callCABlock:(id /* block */)cablock;
- (void)setCAScalarValue:(double)value forProperty:(unsigned long long)property;
- (void)setCAPointValue:(struct CGPoint { double x0; double x1; })value forProperty:(unsigned long long)property;
- (void)setCAObjectValue:(id)value forProperty:(unsigned long long)property;
- (void)setCARectValue:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })value forProperty:(unsigned long long)property;
- (void)setCAPathValue:(struct CGPath *)value forProperty:(unsigned long long)property;
- (void)setCAIntegerValue:(unsigned long long)value forProperty:(unsigned long long)property;
- (void)applyPendingCAValues;
@end

#endif /* KFCALayerImpl_h */
