//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef LSKeychainItemController_h
#define LSKeychainItemController_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString;

@interface LSKeychainItemController : NSObject<NSObject> {
  /* instance variables */
  BOOL _isSynchronizable;
}

@property (readonly, copy, nonatomic) NSString *serviceID;
@property (readonly, copy, nonatomic) NSString *userID;
@property (readonly, copy, nonatomic) NSString *accessGroup;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keychainWithService:(id)service;

/* instance methods */
- (id)initWithServiceID:(id)id accessGroup:(id)group userID:(id)id isSynchronizable:(BOOL)synchronizable;
- (id)initWithServiceID:(id)id accessGroup:(id)group userID:(id)id;
- (id)initSynchronizableItemWithServiceID:(id)id accessGroup:(id)group userID:(id)id;
- (id)initWithService:(id)service appBundle:(id)bundle userID:(id)id;
- (void)createItem:(id)item withTargetQueue:(id)queue onSuccess:(id /* block */)success onError:(id /* block */)error;
- (void)loadItemWithTargetQueue:(id)queue onSuccess:(id /* block */)success onError:(id /* block */)error;
- (void)saveItem:(id)item withTargetQueue:(id)queue onSuccess:(id /* block */)success onError:(id /* block */)error;
- (void)updateItem:(id /* block */)item withTargetQueue:(id)queue onSuccess:(id /* block */)success onError:(id /* block */)error;
- (void)removeItemWithTargetQueue:(id)queue onSuccess:(id /* block */)success onError:(id /* block */)error;
- (BOOL)createItem:(id)item error:(id *)error;
- (BOOL)saveItem:(id)item error:(id *)error;
- (id)loadItem:(id *)item;
- (BOOL)updateItem:(id /* block */)item error:(id *)error;
- (BOOL)removeItem:(id *)item;
- (BOOL)limitToOneResult;
- (BOOL)supportsServicesWithMultipleAccounts;
- (BOOL)isSynchronizable;
- (id)keychainDictionaryForData:(id)data error:(id *)error;
- (id)dataForKeychainResult:(id)result error:(id *)error;
@end

#endif /* LSKeychainItemController_h */
