//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef MBAMailbox_h
#define MBAMailbox_h
@import Foundation;

@interface MBAMailbox : NSObject {
  /* instance variables */
  struct __MCFRuntimeBase { unsigned long long _cfisa; struct __MCFRuntimeBaseData { unsigned char x[4] _cfinfo; unsigned int _rc; } _cfbasedata; } _base;
  struct __MCISystemSession * _systemSession;
  struct __MCIAccountSession * _accountSession;
  struct __MCIAuthDataContext * _authDataContext;
  struct __MCIDatabaseHealthMonitor * _databaseHealthMonitor;
  struct __MCFDictionary * _ephemeralTaskObserverMap;
  struct __MCFDictionary * _extensionCache;
  struct __MCINetworkSession * _networkSession;
  int _state;
  struct __MCFDictionary * _taskObserverMap;
  struct __MCASlimMailbox * _slimMailbox;
  struct MCFWeakMCAMailbox * _weakSelf;
  unsigned char _databaseOpened;
  unsigned char _syncAfterDatabaseOpened;
  void * _databaseErrorHandlerContext;
  undefined * _databaseErrorHandler;
  struct __MCFString * _syncSchemaVersionId;
  struct __MCFString * _syncClientVersion;
  struct __MCIJobScheduler * _jobScheduler;
  struct __MCDDasmConfig * _dasmConfig;
  struct __MCDMediaSendManager * _mediaSendManager;
  struct __MCIExperimentCache * _experimentCache;
  undefined * _experimentStoreCacheLoader;
  unsigned char _loadExperimentCache;
  undefined * _eventSampleRatesConfigLoader;
  struct __MCFURL * _echoStorageDirURL;
  struct __MCDSync * _sync;
  struct __MCFArray * _syncGroupAllowlist;
  struct __MCFArray * _delayedSyncGroups;
  unsigned char _disableTaskProcessing;
  unsigned char _delayTaskProcessing;
  unsigned char _taskProcessingScheduled;
  void * _taskCompletionObserver;
  void * _databaseMetricsBackgroundObserver;
  struct __MCFDictionary * _taskCompletionNotificationScopeMappings;
  struct __MCFNumber * _cacheSize;
  unsigned char _useAllowlistV2;
  unsigned char _useDelayedGroupsV2;
  unsigned char _forceDisableVaulting;
  int _clientType;
  int _initialAppState;
  int _currentAppState;
  long long _lastAppForegroundedTimestampMs;
  unsigned char _echoWalModeEnabled;
  int _syncMode;
  unsigned char _shouldSkipSyncWhenForegrounded;
  unsigned char _isSyncPerfOptimizationEnabled;
  struct __MCIPrivacyContext * _privacyContextForAllTransports;
  void * _placeHolder;
  unsigned char _reverbInitializerComplete;
}

@end

#endif /* MBAMailbox_h */
