//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef MessagePackPacker_h
#define MessagePackPacker_h
@import Foundation;

@interface MessagePackPacker : NSObject
/* class methods */
+ (void)packNumber:(id)number into:(struct msgpack_packer *)into;
+ (void)packObject:(id)object into:(struct msgpack_packer *)into;
+ (id)createPackedData:(id)data;
@end

#endif /* MessagePackPacker_h */
