//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef NSDictionary_SafeAccess_h
#define NSDictionary_SafeAccess_h
@import Foundation;

@interface NSDictionary (SafeAccess)
/* instance methods */
- (id)ig_objectForKeyOrNil:(id)nil;
- (void)ig_withObjectForKeyOrNil:(id)nil ignoreIfMissing:(BOOL)missing perform:(id /* block */)perform;
- (BOOL)ig_boolForKey:(id)key;
- (BOOL)ig_boolForKey:(id)key defaultValue:(BOOL)value;
- (float)ig_floatForKey:(id)key defaultValue:(float)value;
- (double)ig_doubleForKey:(id)key defaultValue:(double)value;
- (long long)ig_integerForKey:(id)key defaultValue:(long long)value;
- (id)ig_stringForKeyOrNil:(id)nil;
- (id)ig_stringForKey:(id)key defaultValue:(id)value;
- (id)ig_arrayForKeyOrNil:(id)nil;
- (id)ig_dictionaryForKeyOrNil:(id)nil;
- (id)ig_dictionaryForKey:(id)key defaultValue:(id)value;
- (id)ig_urlForKeyOrNil:(id)nil;
- (id)ig_objectForKeyPath:(id)path error:(id *)error;
@end

#endif /* NSDictionary_SafeAccess_h */
