//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef VideoViewabilityTracker_h
#define VideoViewabilityTracker_h
@import Foundation;

#include "FBPoller-Protocol.h"
#include "VideoViewabilityInfoListenerAnnouncer.h"
#include "VideoViewabilityReport.h"
#include "VideoViewabilityTrackerProtocol-Protocol.h"

@class NSString;
@protocol VideoViewabilityDelegate, VideoViewabilitySourceDelegate;

@interface VideoViewabilityTracker : NSObject<VideoViewabilityTrackerProtocol> {
  /* instance variables */
  NSObject<FBPoller> *_poller;
  VideoViewabilityInfoListenerAnnouncer *_viewabilityInfoListenerAnnouncer;
  double _viewabilityErrorRate;
  VideoViewabilityReport *_viewabilityReport;
}

@property (weak, nonatomic) NSObject<VideoViewabilitySourceDelegate> *viewabilityCalculationSource;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) NSObject<VideoViewabilityDelegate> *delegate;

/* instance methods */
- (id)initWithPoller:(id)poller videoViewabilityErrorRate:(double)rate;
- (id)videoViewability;
- (void)startTracker;
- (void)stopTracker;
- (void)addInfoListener:(id)listener;
- (void)removeInfoListener:(id)listener;
- (void)poll;
- (void)_updateViewability;
@end

#endif /* VideoViewabilityTracker_h */
