//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialInterestTargetingLogger_h
#define IGSundialInterestTargetingLogger_h
@import Foundation;

@class IGCameraLogger, NSString;

@interface IGSundialInterestTargetingLogger : NSObject {
  /* instance variables */
  IGCameraLogger *_cameraLogger;
  NSString *_interestTargetingSessionId;
  long long _mediaSource;
}

/* instance methods */
- (id)initWithCameraLogger:(id)logger interestTargetingSessionId:(id)id mediaSource:(long long)source;
@end

#endif /* IGSundialInterestTargetingLogger_h */
