//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialGridRemixFeedNetworkSource_h
#define IGSundialGridRemixFeedNetworkSource_h
@import Foundation;

#include "IGSundialFeedNetworkSource.h"
#include "IGSundialGridRemixPageMetadata.h"

@interface IGSundialGridRemixFeedNetworkSource : IGSundialFeedNetworkSource {
  /* instance variables */
  IGSundialGridRemixPageMetadata *_remixPageMetadata;
}

/* instance methods */
- (void)updateModelsFromParsedResponse:(id)response requestConfig:(id)config;
@end

#endif /* IGSundialGridRemixFeedNetworkSource_h */
