//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialShoppingTagProductManager_h
#define IGSundialShoppingTagProductManager_h
@import Foundation;

#include "IGSundialShoppingTagProductManagerDelegate-Protocol.h"
#include "IGTaggingLogger.h"
#include "NSObject-Protocol.h"

@class IGNavigationController, IGShoppingTaggingPermissionsHelper, IGSundialShoppingCapabilities, IGSundialShoppingMetadata, IGTaggingProductUserFlowLogger, IGUser, IGUserSession, NSArray, NSString;

@interface IGSundialShoppingTagProductManager : NSObject<NSObject> {
  /* instance variables */
  IGUserSession *_userSession;
  IGSundialShoppingCapabilities *_sundialShoppingCapabilities;
  IGShoppingTaggingPermissionsHelper *_shoppingTaggingPermissionsHelper;
  NSString *_shoppingTaggingSessionId;
  NSString *_analyticsModule;
  IGTaggingLogger *_taggingLogger;
  IGTaggingProductUserFlowLogger *_taggingProductUserFlowLogger;
  NSArray *_suggestedProducts;
}

@property (weak, nonatomic) NSObject<IGSundialShoppingTagProductManagerDelegate> *delegate;
@property (weak, nonatomic) IGNavigationController *navigationController;
@property (retain, nonatomic) IGUser *sponsorPartner;
@property (retain, nonatomic) IGSundialShoppingMetadata *shoppingMetadata;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session navigationController:(id)controller sundialShoppingCapabilities:(id)capabilities taggingSessionId:(id)id shoppingMetadata:(id)metadata sponsorPartner:(id)partner analyticsModule:(id)module taggingLogger:(id)logger taggingProductUserFlowLogger:(id)logger;
- (id)descriptionText;
- (void)productTaggingFlowPresenterDidCancel:(id)cancel sessionID:(id)id;
- (void)productTaggingFlowPresenter:(id)presenter didSelectTaggedProductItems:(id)items merchantID:(id)id productMerchantIDs:(id)ids sessionID:(id)id productSelectionBehavior:(id)behavior productIdToCollectionInfoMap:(id)map;
- (void)productTaggingFlowPresenter:(id)presenter didSelectProductCollection:(id)collection merchantID:(id)id productMerchantIDs:(id)ids sessionID:(id)id;
- (void)shoppingTaggingPermissionsHelper:(id)helper didUpdateTaggingPermissionsStatus:(long long)status;
- (void)shoppingTaggingPermissionsHelper:(id)helper didUpdateResponse:(id)response;
@end

#endif /* IGSundialShoppingTagProductManager_h */
