//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialViewerImmersiveTagsPhotoView_h
#define IGSundialViewerImmersiveTagsPhotoView_h
@import Foundation;

#include "IGPassthroughView.h"
#include "IGFeedTagsProvider-Protocol.h"
#include "IGObjectInTagDisplayView.h"
#include "NSObject-Protocol.h"

@class IGTagHintDisplayView, NSArray, NSString;

@interface IGSundialViewerImmersiveTagsPhotoView : IGPassthroughView<NSObject> {
  /* instance variables */
  IGObjectInTagDisplayView *_inTagView;
  IGTagHintDisplayView *_tagHintDisplayView;
  NSArray *_tagGroups;
  struct recursive_mutex { struct _opaque_pthread_mutex_t { long long __sig; char x[56] __opaque; } __m_; } _tagGroupsMutex;
  NSObject<IGFeedTagsProvider> *_tagsProvider;
  BOOL _isPeekingTagHintDots;
  BOOL _isShowingTags;
  BOOL _hasDelayedMetadata;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (BOOL)hasProductTags;
- (BOOL)hasUserTags;
- (void)showTagHintDotsWithShowDelay:(double)delay hideDelay:(double)delay;
- (void)clearTagHintDots;
- (void)hideAllOverlays;
- (void)showTags:(BOOL)tags animated:(BOOL)animated tagVisibilityChangeReason:(unsigned long long)reason;
- (void)setTagViewDelegate:(id)delegate;
- (void)tagHintDisplayViewTagTapped:(id)tapped;
- (void)_onTagGroupWasEdited:(id)edited;
@end

#endif /* IGSundialViewerImmersiveTagsPhotoView_h */
