//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialViewerAttributeModelMatcher_h
#define IGSundialViewerAttributeModelMatcher_h
@import Foundation;

@interface IGSundialViewerAttributeModelMatcher : NSObject
/* class methods */
+ (id)match:(id)match audio:(id /* block */)audio contentAppreciation:(id /* block */)appreciation effects:(id /* block */)effects event:(id /* block */)event horizonWorlds:(id /* block */)worlds location:(id /* block */)location stickerResults:(id /* block */)results template:(id /* block */)template thirdPartyApp:(id /* block */)app viewPeople:(id /* block */)people viewProducts:(id /* block */)products wearables:(id /* block */)wearables sponsoredText:(id /* block */)text giphyVideo:(id /* block */)video audioControlButton:(id /* block */)button cutoutSticker:(id /* block */)sticker linkedHighlight:(id /* block */)highlight metaVerifiedLink:(id /* block */)link appStoreRatingReviews:(id /* block */)reviews businessCategory:(id /* block */)category businessRatingReviews:(id /* block */)reviews registeredNonprofit:(id /* block */)nonprofit genAITransparency:(id /* block */)aitransparency creatorPick:(id /* block */)pick addYours:(id /* block */)yours;
@end

#endif /* IGSundialViewerAttributeModelMatcher_h */
