//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC37IGImmersiveFeedComponentConfiguration35ImmersiveFeedComponentConfiguration_h
#define _TtC37IGImmersiveFeedComponentConfiguration35ImmersiveFeedComponentConfiguration_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"
#include "IGImmersiveFeedComponentConfigurationType-Protocol.h"

@class NSString;

@interface _TtC37IGImmersiveFeedComponentConfiguration35ImmersiveFeedComponentConfiguration : _TtCs12_SwiftObject<IGImmersiveFeedComponentConfigurationType> // (Swift)

@property (nonatomic, readonly) NSString *sessionID;

/* instance methods */
- (id)additionalViewpointActionsForAllMedia:(id)media;
- (id)additionalViewpointActionsForSoloMedia:(id)media;
- (id)additionalViewpointActionsForCarouselMedia:(id)media at:(long long)at;
@end

#endif /* _TtC37IGImmersiveFeedComponentConfiguration35ImmersiveFeedComponentConfiguration_h */
