//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC17IGMediaKitLogging16IGMediaKitLogger_h
#define _TtC17IGMediaKitLogging16IGMediaKitLogger_h
@import Foundation;

@interface _TtC17IGMediaKitLogging16IGMediaKitLogger : NSObject { // (Swift)
  /* instance variables */
   eventLogger;
   eventConfig;
   userSession;
   entryPoint;
   mkSessionId;
   hasLoggingSessionStarted;
   mkId;
}

/* instance methods */
- (id)initWithUserSession:(id)session entryPoint:(unsigned long long)point mkSessionId:(id)id mkId:(id)id analyticsModule:(id)module;
- (void)logEvent:(long long)event withExtraData:(id)data;
- (void)logEvent:(long long)event forSection:(long long)section withExtraData:(id)data;
- (void)logError:(long long)error withIdentifier:(long long)identifier errorMessage:(id)message extraData:(id)data;
- (id)init;
@end

#endif /* _TtC17IGMediaKitLogging16IGMediaKitLogger_h */
