//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC13IGProfileWall28IGProfileWallReplyController_h
#define _TtC13IGProfileWall28IGProfileWallReplyController_h
@import Foundation;

@interface _TtC13IGProfileWall28IGProfileWallReplyController : NSObject { // (Swift)
  /* instance variables */
   userSession;
   profileUser;
   currentNote;
   viewController;
   analyticsModule;
   $__lazy_storage_$_replyToAuthorPresenter;
}

/* instance methods */
- (id)init;
@end

#endif /* _TtC13IGProfileWall28IGProfileWallReplyController_h */
