//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC24IGDirectDetailMembersKit46IGDirectThreadDetailsMembersListViewController_IGDirectDetailMembersKit10_h
#define _TtC24IGDirectDetailMembersKit46IGDirectThreadDetailsMembersListViewController_IGDirectDetailMembersKit10_h
@import Foundation;

@interface _TtC24IGDirectDetailMembersKit46IGDirectThreadDetailsMembersListViewController (IGDirectDetailMembersKit10) <IGDirectThreadDetailUserCellDelegate>
/* instance methods */
- (void)threadDetailUserCellDidTapAdminButtonForUserViewModel:(id)model;
- (void)threadDetailUserCellDidTapRemoveButtonForUserViewModel:(id)model;
- (void)threadDetailUserCellDidTapUserForUserKey:(id)key;
- (void)threadDetailUserCellDidTapAvatarForUserKey:(id)key;
- (void)threadDetailUserCellDidTapMessageButton:(id)button;
- (void)threadDetailUserCellDidTapSeeChannelButton:(id)button completionHandler:(id /* block */)handler;
@end

#endif /* _TtC24IGDirectDetailMembersKit46IGDirectThreadDetailsMembersListViewController_IGDirectDetailMembersKit10_h */
