//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC17IGFriendsMapNotes50IGFriendsMapNotesClusterFloatingGridViewController_IGFriendsMapNotes2_h
#define _TtC17IGFriendsMapNotes50IGFriendsMapNotesClusterFloatingGridViewController_IGFriendsMapNotes2_h
@import Foundation;

@interface _TtC17IGFriendsMapNotes50IGFriendsMapNotesClusterFloatingGridViewController (IGFriendsMapNotes2) <UICollectionViewDelegateFlowLayout>
/* instance methods */
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)view layout:(id)layout insetForSectionAtIndex:(long long)index;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout sizeForItemAtIndexPath:(id)path;
@end

#endif /* _TtC17IGFriendsMapNotes50IGFriendsMapNotesClusterFloatingGridViewController_IGFriendsMapNotes2_h */
