//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC32IGBrandedContentDisclosureFlowV246IGBrandedContentDisclosureReviewViewController_h
#define _TtC32IGBrandedContentDisclosureFlowV246IGBrandedContentDisclosureReviewViewController_h
@import Foundation;

#include "IGViewController.h"

@interface _TtC32IGBrandedContentDisclosureFlowV246IGBrandedContentDisclosureReviewViewController : IGViewController { // (Swift)
  /* instance variables */
   delegate;
   userSession;
   bcMedia;
   mediaType;
   priorModule;
   fromActionSheet;
   isEditMode;
   areProjectsAvailable;
   messageService;
   shareSheet;
   isEditingStoryWithTappableElements;
   adCodeNetworkHelper;
   toastPresenter;
   collectionView;
   $__lazy_storage_$_listAdapter;
   $__lazy_storage_$_projectPickerController;
   adCode;
   shouldAdCodeToggleOn;
   isPaidPartnership;
   isBCAdsPermissionOn;
   isResharing;
   brandedContentSponsoredTags;
   projectMetadata;
   audienceRestrictions;
   hidePartnershipAdCode;
   copyFromTapOnCode;
   copyFromCopyButton;
   pplToggleViewModel;
   adsBoostToggleViewModel;
   audienceRestrictionsViewModel;
   partnershipAdCodeToggleViewModel;
}

/* instance methods */
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)appear;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)disappear;
- (void)configureNavBar;
- (void)didTapBack;
- (void)didTapCancel;
- (void)didTapDone;
- (id)initWithAnalyticsModule:(id)module performanceListener:(id)listener;
@end

#endif /* _TtC32IGBrandedContentDisclosureFlowV246IGBrandedContentDisclosureReviewViewController_h */
