//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC46IGPreferredBusinessesLinkAccountViewController46IGPreferredBusinessesLinkAccountViewController_IGPreferredBusinessesLinkAccountViewController_h
#define _TtC46IGPreferredBusinessesLinkAccountViewController46IGPreferredBusinessesLinkAccountViewController_IGPreferredBusinessesLinkAccountViewController_h
@import Foundation;

@interface _TtC46IGPreferredBusinessesLinkAccountViewController46IGPreferredBusinessesLinkAccountViewController (IGPreferredBusinessesLinkAccountViewController) <IGBrowserViewControllerDelegate>
/* instance methods */
- (void)browserViewControllerDidFinishWithURL:(id)url dismissWithMethod:(unsigned long long)method;
- (void)browserViewControllerDidFinishWithSessionID:(id)id landingPageInteractable:(BOOL)interactable;
- (void)browserViewController:(id)controller loadingProgressChanged:(double)changed;
- (void)browserViewController:(id)controller URLChanged:(id)urlchanged;
- (void)browserViewControllerWillCloseBrowser:(id)browser;
- (id)browserViewControllerPresenter;
- (void)browserViewController:(id)controller didScrollWebViewScrollView:(id)view;
- (void)browserViewController:(id)controller didRequestPopupForNavigationAction:(id)action;
- (void)browserViewControllerDidRequestMinimizeToPeek:(id)peek;
- (void)browserViewControllerDidCompleteInitialLoading;
- (void)browserViewControllerDidBecomeInteractive;
@end

#endif /* _TtC46IGPreferredBusinessesLinkAccountViewController46IGPreferredBusinessesLinkAccountViewController_IGPreferredBusinessesLinkAccountViewController_h */
