//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC32IGDirectDetailRedesignHeaderItem51IGDirectThreadDetailsCustomGroupPhotoViewController_IGDirectDetailRedesignHeaderItem1_h
#define _TtC32IGDirectDetailRedesignHeaderItem51IGDirectThreadDetailsCustomGroupPhotoViewController_IGDirectDetailRedesignHeaderItem1_h
@import Foundation;

@interface _TtC32IGDirectDetailRedesignHeaderItem51IGDirectThreadDetailsCustomGroupPhotoViewController (IGDirectDetailRedesignHeaderItem1) <IGProfilePictureHelperDelegate>
/* instance methods */
- (void)profilePictureHelper:(id)helper didFinishDownloadingProfilePicture:(id)picture fromOption:(long long)option;
- (void)profilePictureHelperRemovePictureButtonTapped:(id)tapped;
- (BOOL)profilePictureHelperShouldShowRemovePicture:(id)picture;
@end

#endif /* _TtC32IGDirectDetailRedesignHeaderItem51IGDirectThreadDetailsCustomGroupPhotoViewController_IGDirectDetailRedesignHeaderItem1_h */
