//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC27IGFeedItemPhotoCellDelegate31IGFeedItemPhotoCellDelegateImpl_IGFeedItemPhotoCellDelegate1_h
#define _TtC27IGFeedItemPhotoCellDelegate31IGFeedItemPhotoCellDelegateImpl_IGFeedItemPhotoCellDelegate1_h
@import Foundation;

@interface _TtC27IGFeedItemPhotoCellDelegate31IGFeedItemPhotoCellDelegateImpl (IGFeedItemPhotoCellDelegate1) <IGFloatingSocialContextActionHandlerDelegate>
/* instance methods */
- (void)floatingSocialContextActionHandler:(id)handler didTapCommentSocialContextWithCommentID:(id)id media:(id)media;
- (void)floatingSocialContextActionHandler:(id)handler handleLikersListNavigationWithMedia:(id)media;
@end

#endif /* _TtC27IGFeedItemPhotoCellDelegate31IGFeedItemPhotoCellDelegateImpl_IGFeedItemPhotoCellDelegate1_h */
