//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_h
#define _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGTitleAndToggleCellDelegate-Protocol.h"

@interface _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController : IGViewController<IGListAdapterDataSource, IGTitleAndToggleCellDelegate> { // (Swift)
  /* instance variables */
   privacySettings;
   userSession;
   $__lazy_storage_$_listAdapter;
   $__lazy_storage_$_collectionView;
   activityIndicator;
   isTypingIndicatorsEnabled;
}

/* instance methods */
- (id)initWithUserSession:(id)session;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)appear;
- (void)viewDidLayoutSubviews;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (void)titleAndToggleCell:(id)cell didSwitchValueTo:(BOOL)to;
- (void)titleAndToggleCell:(id)cell didTapOnString:(id)string URL:(id)url;
- (id)initWithAnalyticsModule:(id)module performanceListener:(id)listener;
@end

#endif /* _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_h */
