//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC27IGProfileHeaderLinksManager27IGProfileHeaderLinksManager_IGProfileHeaderLinksManager1_h
#define _TtC27IGProfileHeaderLinksManager27IGProfileHeaderLinksManager_IGProfileHeaderLinksManager1_h
@import Foundation;

@interface _TtC27IGProfileHeaderLinksManager27IGProfileHeaderLinksManager (IGProfileHeaderLinksManager1) <IGProfileMultipleChannelsSheetViewControllerDelegate>
/* instance methods */
- (void)channelsSheetViewControllerDidTapChannelAtIndex:(long long)index;
- (void)channelSheetViewControllerDidTapChannelWithChannelInfo:(id)info;
@end

#endif /* _TtC27IGProfileHeaderLinksManager27IGProfileHeaderLinksManager_IGProfileHeaderLinksManager1_h */
