//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC6BCNBio27BCNBioImagePickerController_BCNBio_h
#define _TtC6BCNBio27BCNBioImagePickerController_BCNBio_h
@import Foundation;

@interface _TtC6BCNBio27BCNBioImagePickerController (BCNBio) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
/* instance methods */
- (void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
- (void)imagePickerControllerDidCancel:(id)cancel;
@end

#endif /* _TtC6BCNBio27BCNBioImagePickerController_BCNBio_h */
