//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC21IGContactImportPrompt35IGContactImportPromptViewController_h
#define _TtC21IGContactImportPrompt35IGContactImportPromptViewController_h
@import Foundation;

#include "IGViewController.h"

@interface _TtC21IGContactImportPrompt35IGContactImportPromptViewController : IGViewController { // (Swift)
  /* instance variables */
   delegate;
   userSession;
   module;
   model;
   config;
   imageView;
   titleTextView;
   subtitleTextView;
   $__lazy_storage_$_contentView;
   $__lazy_storage_$_actionButtonsView;
   contactsHelper;
}

@property (nonatomic, readonly) long long preferredStatusBarStyle;

/* instance methods */
- (void)viewDidLoad;
- (BOOL)prefersNavigationBarHidden;
- (BOOL)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (id)initWithAnalyticsModule:(id)module performanceListener:(id)listener;
@end

#endif /* _TtC21IGContactImportPrompt35IGContactImportPromptViewController_h */
