//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC15ShopifyCheckout20CheckoutStatePayload_h
#define _TtC15ShopifyCheckout20CheckoutStatePayload_h
@import Foundation;

@class NSArray, NSString;

@interface _TtC15ShopifyCheckout20CheckoutStatePayload : NSObject // (Swift)

@property (nonatomic, readonly) NSString *flowType;
@property (nonatomic, readonly) _TtC15ShopifyCheckout8CartInfo *cart;
@property (nonatomic, readonly) _TtC15ShopifyCheckout9BuyerInfo *buyer;
@property (nonatomic, readonly) NSArray *deliveries;

/* instance methods */
- (id)initWithFlowType:(id)type cart:(id)cart buyer:(id)buyer deliveries:(id)deliveries;
- (id)init;
@end

#endif /* _TtC15ShopifyCheckout20CheckoutStatePayload_h */
