//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC11BCNAYMFUnit15BCNAYMFCardCell_h
#define _TtC11BCNAYMFUnit15BCNAYMFCardCell_h
@import Foundation;

#include "IGBaseCollectionViewCell.h"

@interface _TtC11BCNAYMFUnit15BCNAYMFCardCell : IGBaseCollectionViewCell {
  /* instance variables */
   user;
   delegate;
   analyticsModule;
   $__lazy_storage_$_titleLabel;
   $__lazy_storage_$_subtitleLabel;
   $__lazy_storage_$_profilePicture;
   $__lazy_storage_$_verifiedBadgeView;
   followController;
   $__lazy_storage_$_followButton;
   $__lazy_storage_$_dismissButton;
   $__lazy_storage_$_facepileView;
}

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)prepareForReuse;
@end

#endif /* _TtC11BCNAYMFUnit15BCNAYMFCardCell_h */
