//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC34IGDirectSnoozedMessageThreadHelper34IGDirectSnoozedMessageThreadHelper_h
#define _TtC34IGDirectSnoozedMessageThreadHelper34IGDirectSnoozedMessageThreadHelper_h
@import Foundation;

@class NSArray;

@interface _TtC34IGDirectSnoozedMessageThreadHelper34IGDirectSnoozedMessageThreadHelper : NSObject // (Swift)

@property (nonatomic, readonly) _TtC46IGDirectThreadSnoozedMessagesButtonCoordinator46IGDirectThreadSnoozedMessagesButtonCoordinator *snoozedMessagesButtonCoordinator;
@property (nonatomic, copy) NSArray *snoozedMessages;
@property (nonatomic, copy) NSArray *snoozeUnsnoozeMessageIdsInProgress;
@property (nonatomic) BOOL openedReelsViewerFromSnooze;

/* instance methods */
- (id)initWithSnoozedMessagesButtonCoordinator:(id)coordinator;
- (void)setSnoozedReelMessages:(id)messages;
- (void)removeSnoozedReelMessage:(id)message;
- (void)addSnoozeUnsnoozeMessageIdInProgress:(id)progress;
- (void)removeSnoozeUnsnoozeMessageIdInProgress:(id)progress;
- (id)init;
@end

#endif /* _TtC34IGDirectSnoozedMessageThreadHelper34IGDirectSnoozedMessageThreadHelper_h */
