//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC18BCNExternalSharing35BCNExternalSharingSectionController_BCNExternalSharing_h
#define _TtC18BCNExternalSharing35BCNExternalSharingSectionController_BCNExternalSharing_h
@import Foundation;

@interface _TtC18BCNExternalSharing35BCNExternalSharingSectionController (BCNExternalSharing) <IGListSectionContext>
/* instance methods */
- (void)invalidateLayout;
- (void)reloadSectionAnimated:(BOOL)animated;
- (id)cellForCellController:(id)controller;
- (id)navState;
@end

#endif /* _TtC18BCNExternalSharing35BCNExternalSharingSectionController_BCNExternalSharing_h */
