//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC35IGFeedOpenCarouselCreatorExperience41IGFeedOpenCarouselPivotPageViewController_h
#define _TtC35IGFeedOpenCarouselCreatorExperience41IGFeedOpenCarouselPivotPageViewController_h
@import Foundation;

#include "IGViewController.h"

@interface _TtC35IGFeedOpenCarouselCreatorExperience41IGFeedOpenCarouselPivotPageViewController : IGViewController { // (Swift)
  /* instance variables */
   userSession;
   analyticsModule;
   originalCarouselMediaId;
   originalCarouselMedia;
   $__lazy_storage_$_feedViewController;
   selectedItems;
   approveLimit;
   approveItemsCnt;
   errorMsgIdentifier;
   headerView;
   isBottomButtonsViewVisible;
   $__lazy_storage_$_bottomButtonsView;
   $__lazy_storage_$_bottomButtonsBackgroundView;
}

/* instance methods */
- (id)initWithUserSession:(id)session originalCarouselMediaId:(id)id originalCarouselMedia:(id)media originalCarouselAuthor:(id)author submittersList:(id)list promptText:(id)text approveLimit:(long long)limit;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)appear;
- (BOOL)prefersNavigationBarDividerHidden;
- (void)didTapBackButton;
- (void)didTapMoreButton;
- (id)initWithAnalyticsModule:(id)module performanceListener:(id)listener;
@end

#endif /* _TtC35IGFeedOpenCarouselCreatorExperience41IGFeedOpenCarouselPivotPageViewController_h */
