//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC42IGSundialStackedTimelineAdjustmentControls55IGSundialStackedTimelineAdjustmentControlsSelectionView_IGSundialStackedTimelineAdjustmentControls2_h
#define _TtC42IGSundialStackedTimelineAdjustmentControls55IGSundialStackedTimelineAdjustmentControlsSelectionView_IGSundialStackedTimelineAdjustmentControls2_h
@import Foundation;

@interface _TtC42IGSundialStackedTimelineAdjustmentControls55IGSundialStackedTimelineAdjustmentControlsSelectionView (IGSundialStackedTimelineAdjustmentControls2) <UIScrollViewDelegate>
/* instance methods */
- (void)scrollViewWillEndDragging:(id)dragging withVelocity:(struct CGPoint { double x0; double x1; })velocity targetContentOffset:(struct CGPoint { double x0; double x1; } *)offset;
- (void)scrollViewDidEndScrollingAnimation:(id)animation;
- (void)scrollViewDidScroll:(id)scroll;
- (void)scrollViewWillBeginDragging:(id)dragging;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(BOOL)decelerate;
@end

#endif /* _TtC42IGSundialStackedTimelineAdjustmentControls55IGSundialStackedTimelineAdjustmentControlsSelectionView_IGSundialStackedTimelineAdjustmentControls2_h */
