//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC39IGContentNoteDetailsIntentTargetHandler32ContentNoteDetailsViewController_IGContentNoteDetailsIntentTargetHandler_h
#define _TtC39IGContentNoteDetailsIntentTargetHandler32ContentNoteDetailsViewController_IGContentNoteDetailsIntentTargetHandler_h
@import Foundation;

@interface _TtC39IGContentNoteDetailsIntentTargetHandler32ContentNoteDetailsViewController (IGContentNoteDetailsIntentTargetHandler) <IGListAdapterDataSource>
/* instance methods */
- (id)objectsForListAdapter:(id)adapter;
- (id)emptyViewForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
@end

#endif /* _TtC39IGContentNoteDetailsIntentTargetHandler32ContentNoteDetailsViewController_IGContentNoteDetailsIntentTargetHandler_h */
