//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC21IGSundialMidCardSwift47IGSundialMidCardCollectionViewPreviewController_h
#define _TtC21IGSundialMidCardSwift47IGSundialMidCardCollectionViewPreviewController_h
@import Foundation;

#include "IGViewController.h"
#include "_TtP21IGSundialMidCardSwift32IGSundialMidCardCellConfigurable_-Protocol.h"
#include "_TtP21IGSundialMidCardSwift41IGSundialMidCardPreviewControllerDelegate_-Protocol.h"

@interface _TtC21IGSundialMidCardSwift47IGSundialMidCardCollectionViewPreviewController : IGViewController { // (Swift)
  /* instance variables */
   cellIdentifierString;
   collectionView;
   playbackCoordinator;
   medias;
   ctaInfos;
   videoClickedInfos;
   overlayType;
   userSession;
   analyticsModule;
   viewerSessionId;
   previousLoggedMediaId;
}

@property (nonatomic, weak) NSObject<_TtP21IGSundialMidCardSwift41IGSundialMidCardPreviewControllerDelegate_> *delegate;
@property (nonatomic, weak) NSObject<_TtP21IGSundialMidCardSwift32IGSundialMidCardCellConfigurable_> *cellConfiguringDelegate;

/* instance methods */
- (id)initWithMedias:(id)medias ctaInfos:(id)infos videoClickedInfos:(id)infos overlayType:(long long)type userSession:(id)session analyticsModule:(id)module viewerSessionId:(id)id;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (id)initWithAnalyticsModule:(id)module performanceListener:(id)listener;
@end

#endif /* _TtC21IGSundialMidCardSwift47IGSundialMidCardCollectionViewPreviewController_h */
