//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC28IGFeedOpenCarouselComponents41IGFeedOpenCarouselAddToPostMediaIndicator_h
#define _TtC28IGFeedOpenCarouselComponents41IGFeedOpenCarouselAddToPostMediaIndicator_h
@import Foundation;

#include "UIControl.h"
#include "_TtP28IGFeedOpenCarouselComponents49IGFeedOpenCarouselAddToPostMediaIndicatorDelegate_-Protocol.h"

@interface _TtC28IGFeedOpenCarouselComponents41IGFeedOpenCarouselAddToPostMediaIndicator : UIControl { // (Swift)
  /* instance variables */
   $__lazy_storage_$_indicatorLabel;
   $__lazy_storage_$_indicatorIconView;
   $__lazy_storage_$_indicatorTapGestureRecognizer;
}

@property (nonatomic, weak) NSObject<_TtP28IGFeedOpenCarouselComponents49IGFeedOpenCarouselAddToPostMediaIndicatorDelegate_> *delegate;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCoder:(id)coder;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)didTapOnIndicator:(id)indicator;
@end

#endif /* _TtC28IGFeedOpenCarouselComponents41IGFeedOpenCarouselAddToPostMediaIndicator_h */
