//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_IGDirectPrivacySettingsKit_h
#define _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_IGDirectPrivacySettingsKit_h
@import Foundation;

@interface _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController (IGDirectPrivacySettingsKit) <IGDSListSectionControllerDataSource>
/* instance methods */
- (id)listSectionController:(id)controller headerForObject:(id)object;
- (id)listSectionController:(id)controller viewModelsForObject:(id)object;
- (id)listSectionController:(id)controller footerForObject:(id)object;
@end

#endif /* _TtC26IGDirectPrivacySettingsKit52IGDirectTypingIndicatorsAccountSettingViewController_IGDirectPrivacySettingsKit_h */
