//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef BKBloksMediaPickerViewControllerDelegate_h
#define BKBloksMediaPickerViewControllerDelegate_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString;

@interface BKBloksMediaPickerViewControllerDelegate : NSObject<NSObject> {
  /* instance variables */
  id /* block */ _mediaSelectedBlock;
  id /* block */ _phAssetSelectedBlock;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithCompletionBlock:(id /* block */)block didSelectPHAsset:(id /* block */)phasset;
- (void)coverMediaPicker:(id)picker didSelectGuideMedia:(id)media;
- (void)coverMediaPicker:(id)picker didSelectPHAsset:(id)phasset;
- (void)coverMediaPickerDidCancel:(id)cancel;
@end

#endif /* BKBloksMediaPickerViewControllerDelegate_h */
