//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef BKToast_h
#define BKToast_h
@import Foundation;

@class NSArray, NSObject, UIView;

@interface BKToast : NSObject {
  /* instance variables */
  BOOL _isMini;
  NSObject *_toastID;
  double _presentAnimationDuration;
  double _dismissAnimationDuration;
  id /* block */ _onShowBlock;
  id /* block */ _onClickBlock;
  id /* block */ _onDismissBlock;
  NSArray *_showAnimationControlPoints;
  NSArray *_dismissAnimationControlPoints;
}

@property (readonly, nonatomic) UIView *view;
@property (readonly, nonatomic) long long position;
@property (readonly, nonatomic) double duration;
@property (readonly, nonatomic) BOOL showAboveKeyboard;

/* instance methods */
- (id)initWithView:(id)view toastID:(id)id isMini:(BOOL)mini position:(long long)position duration:(double)duration presentAnimationDuration:(double)duration dismissAnimationDuration:(double)duration onShow:(id /* block */)show onClick:(id /* block */)click onDismiss:(id /* block */)dismiss showAnimationControlPoints:(id)points dismissAnimationControlPoints:(id)points showAboveKeyboard:(BOOL)keyboard;
- (void)_onClick;
@end

#endif /* BKToast_h */
