//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FB_RTCVideoRendererAdapter_h
#define FB_RTCVideoRendererAdapter_h
@import Foundation;

#include "FB_RTCVideoRenderer-Protocol.h"

@protocol {unique_ptr<webrtc_legacy::VideoRendererAdapter, std::default_delete<webrtc_legacy::VideoRendererAdapter>>="__ptr_"{__compressed_pair<webrtc_legacy::VideoRendererAdapter *, std::default_delete<webrtc_legacy::VideoRendererAdapter>>="__value_"^{VideoRendererAdapter}}};

@interface FB_RTCVideoRendererAdapter : NSObject {
  /* instance variables */
  struct unique_ptr<webrtc_legacy::VideoRendererAdapter, std::default_delete<webrtc_legacy::VideoRendererAdapter>> { struct __compressed_pair<webrtc_legacy::VideoRendererAdapter *, std::default_delete<webrtc_legacy::VideoRendererAdapter>> { struct VideoRendererAdapter *__value_; } __ptr_; } _adapter;
}

@property (readonly, nonatomic) NSObject<FB_RTCVideoRenderer> *videoRenderer;
@property (readonly, nonatomic) void * nativeVideoRenderer;

/* instance methods */
- (id)initWithNativeRenderer:(id)renderer;
@end

#endif /* FB_RTCVideoRendererAdapter_h */
