//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBPayIAWPaymentContainer_h
#define FBPayIAWPaymentContainer_h
@import Foundation;

#include "FBValueObject.h"
#include "NSCoding-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSString;

@interface FBPayIAWPaymentContainer : FBValueObject<NSCopying, NSCoding>

@property (readonly, copy, nonatomic) NSString *containerId;
@property (readonly, copy, nonatomic) NSString *mode;
@property (readonly, copy, nonatomic) NSString *containerData;
@property (readonly, copy, nonatomic) NSString *containerType;

/* class methods */
+ (id)valueWithJSONDictionary:(id)jsondictionary error:(id *)error;

/* instance methods */
- (id)initWithContainerId:(id)id mode:(id)mode containerData:(id)data containerType:(id)type;
@end

#endif /* FBPayIAWPaymentContainer_h */
