//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBPayComponentInlineCellContextView_h
#define FBPayComponentInlineCellContextView_h
@import Foundation;

#include "UIView.h"
#include "FBPayComponentInlineCellContextViewViewConfig.h"
#include "FBPayComponentInlineCellContextViewViewModel.h"

@class NSMutableArray, UILabel, UIView;
@protocol FBPayComponentInlineCellContextViewTapInlineCellLabelDelegate, FBPayViewStyleConfiguring;

@interface FBPayComponentInlineCellContextView : UIView {
  /* instance variables */
  FBPayComponentInlineCellContextViewViewModel *_contextViewViewModel;
  NSObject<FBPayViewStyleConfiguring> *_viewStyleConfiguration;
  FBPayComponentInlineCellContextViewViewConfig *_contextViewConfig;
  UILabel *_firstLineLabel;
  UILabel *_secondLineLabel;
  UILabel *_thirdLineLabel;
  UILabel *_fourthLineLabel;
  UILabel *_nullStateLabel;
  UILabel *_errorStateLabel;
  UIView *_imageView;
  UIView *_shimmerView;
  unsigned long long _lineOfShimmerings;
  double _spacingBetweenLabelAndLeadingEdge;
  NSMutableArray *_constraints;
}

@property (weak, nonatomic) NSObject<FBPayComponentInlineCellContextViewTapInlineCellLabelDelegate> *delegate;

/* instance methods */
- (id)init;
- (void)_didTapAPMChangeMethodButton;
- (BOOL)isAccessibilityElement;
- (id)accessibilityLabel;
@end

#endif /* FBPayComponentInlineCellContextView_h */
