//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBReactPerfLoggerFlagViewManager_h
#define FBReactPerfLoggerFlagViewManager_h
@import Foundation;

#include "RCTViewManager.h"

@interface FBReactPerfLoggerFlagViewManager : RCTViewManager
/* class methods */
+ (id)moduleName;
+ (id)propConfigShadow_flagId;
+ (id)propConfigShadow_extraData;

/* instance methods */
- (id)shadowView;
- (id)view;
@end

#endif /* FBReactPerfLoggerFlagViewManager_h */
