//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBRMVViewModeAction_h
#define FBRMVViewModeAction_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "FBRMVViewModeActionAR.h"
#include "FBRMVViewModeActionAR3D.h"
#include "FBRMVViewModeActionVideoStream.h"

@interface FBRMVViewModeAction : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  FBRMVViewModeActionAR *_aR_action;
  FBRMVViewModeActionAR3D *_aR3D_action;
  FBRMVViewModeActionVideoStream *_videoStream_action;
}

/* class methods */
+ (id)aR3DWithAction:(id)action;
+ (id)aRWithAction:(id)action;
+ (id)videoStreamWithAction:(id)action;

/* instance methods */
- (void)matchAR:(id /* block */)ar aR3D:(id /* block */)d videoStream:(id /* block */)stream;
@end

#endif /* FBRMVViewModeAction_h */
