//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBSymmetricDecryptionInput_h
#define FBSymmetricDecryptionInput_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "FBSymmetricEncryptionAESInput.h"

@class NSData, NSFileHandle;

@interface FBSymmetricDecryptionInput : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  FBSymmetricEncryptionAESInput *_algorithmAESModeGCM_input;
  NSData *_algorithmAESModeGCM_aad;
  NSData *_algorithmAESModeGCM_mac;
  FBSymmetricEncryptionAESInput *_algorithmAESModeGCMFileStream_aesInput;
  NSData *_algorithmAESModeGCMFileStream_aad;
  NSFileHandle *_algorithmAESModeGCMFileStream_input;
  long long _algorithmAESModeGCMFileStream_inputFileLength;
  NSFileHandle *_algorithmAESModeGCMFileStream_output;
  FBSymmetricEncryptionAESInput *_algorithmAESModeCTR;
  FBSymmetricEncryptionAESInput *_algorithmAESModeCBC;
}

/* class methods */
+ (id)algorithmAESModeCBC:(id)cbc;
+ (id)algorithmAESModeCTR:(id)ctr;
+ (id)algorithmAESModeGCMFileStreamWithAesInput:(id)input aad:(id)aad input:(id)input inputFileLength:(long long)length output:(id)output;
+ (id)algorithmAESModeGCMWithInput:(id)input aad:(id)aad mac:(id)mac;

/* instance methods */
- (void)matchAlgorithmAESModeGCM:(id /* block */)gcm algorithmAESModeGCMFileStream:(id /* block */)stream algorithmAESModeCTR:(id /* block */)ctr algorithmAESModeCBC:(id /* block */)cbc;
@end

#endif /* FBSymmetricDecryptionInput_h */
