//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FBVideoBroadcastSessionDelegate_Protocol_h
#define FBVideoBroadcastSessionDelegate_Protocol_h
@import Foundation;

@protocol FBVideoBroadcastSessionDelegate <NSObject>
/* instance methods */
- (void)broadcastSessionDidConnect:(id)connect withSpeedTestStatus:(struct FBNetworkSpeedTestStatus { int x0; double x1; unsigned long long x2; id x3; BOOL x4; })status;
- (void)broadcastSessionDidFinishRecording:(id)recording withResult:(id)result;
- (void)broadcastSessionDidDisconnectNetwork:(id)network withEndOfStreamError:(id)error;
- (void)broadcastSessionDidFail:(id)fail withLoggingInfo:(struct FBVideoBroadcastSessionLoggingInfo { id x0; id x1; BOOL x2; })info;
- (void)broadcastSessionDidLoseConnection:(id)connection error:(id)error;
- (void)broadcastSessionSendDidTimeout:(id)timeout;
- (void)broadcastSession:(id)session didDropPackets:(struct shared_ptr<std::vector<facebook::mobile::xplat::livestreaming::DroppedFrame>> { void * x0; struct __shared_weak_count * x1; })packets dropReason:(id)reason;
- (void)broadcastSession:(id)session didDropFrameWithType:(id)type pts:(struct { long long x0; int x1; unsigned int x2; long long x3; })pts dropReason:(id)reason;
- (void)broadcastSession:(id)session setAccumulatedStreamGapSeconds:(id)seconds;
- (void)broadcastSession:(id)session didChangeBaseTimestamp:(struct { long long x0; int x1; unsigned int x2; long long x3; })timestamp;
- (void)broadcastSessionDidProcessAudio:(id)audio;
- (void)broadcastSession:(id)session completedSpeedTestWithStatus:(struct FBNetworkSpeedTestStatus { int x0; double x1; unsigned long long x2; id x3; BOOL x4; })status;
- (void)broadcastSession:(id)session didUpdateStreamingInfo:(struct Info { struct Optional<std::string> { struct StorageNonTriviallyDestructible { union { char x0; struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct __compressed_pair<std::basic_string<char>::__rep, std::allocator<char>> { struct __rep { union { struct __long { char * x0; unsigned long long x1; unsigned int x2 :63; unsigned int x3 :1; } x0; struct __short { char x0[23] unsigned char x1[0] unsigned int x2 :7; unsigned int x3 :1; } x1; struct __raw { unsigned long long x0[3] } x2; } x0; } x0; } x0; } x1; } x0; BOOL x1; } x0; } x0; struct basic_string<char, std::char_traits<char>, std::allocator<char>> { struct __compressed_pair<std::basic_string<char>::__rep, std::allocator<char>> { struct __rep { union { struct __long { char * x0; unsigned long long x1; unsigned int x2 :63; unsigned int x3 :1; } x0; struct __short { char x0[23] unsigned char x1[0] unsigned int x2 :7; unsigned int x3 :1; } x1; struct __raw { unsigned long long x0[3] } x2; } x0; } x0; } x0; } x1; })info;
- (void)broadcastSession:(id)session didUpdateFlowState:(long long)state;
- (void)broadcastSession:(id)session didUpdateDebugInfo:(id)info;
- (void)broadcastSessionDidReceiveEventMessageAck:(id)ack;
- (void)broadcastSessionShowUserActionableMessage:(int)message;
- (BOOL)broadcastSessionShouldAdjustTimer:(id)timer;
@end

#endif /* FBVideoBroadcastSessionDelegate_Protocol_h */
