//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef FNFMp4SegmentGenerator_h
#define FNFMp4SegmentGenerator_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;
@protocol FNFProxyServerDataConsumer, FNFSegmentCaching, OS_dispatch_queue;

@interface FNFMp4SegmentGenerator : NSObject<NSObject> {
  /* instance variables */
  NSObject<FNFProxyServerDataConsumer> *_dataConsumer;
  NSObject<FNFSegmentCaching> *_cache;
  NSMutableDictionary *_mp4DataSegments;
  NSMutableArray *_mp4DataSegmentIndice;
  NSMutableSet *_completedSegments;
  NSMutableDictionary *_mp4DataRepresentationHeaders;
  NSMutableDictionary *_mp4DataSegmentMetadata;
  NSMutableDictionary *_mp4SegmentDurations;
  int _videoSegmentCount;
  NSMutableDictionary *_mp4DataSegmentsForAudio;
  NSMutableArray *_mp4DataSegmentIndiceForAudio;
  NSMutableSet *_completedSegmentsForAudio;
  NSMutableDictionary *_mp4DataRepresentationHeadersForAudio;
  NSMutableDictionary *_mp4DataSegmentMetadataForAudio;
  NSMutableDictionary *_mp4SegmentDurationsForAudio;
  int _audioSegmentCount;
  NSMutableArray *_abrEntities;
  NSString * _servingRepresentationIds[3];
  NSObject<OS_dispatch_queue> *_dispatchQueue;
  NSString *_identifier;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDataConsumer:(id)consumer identifier:(id)identifier;
- (void)frameDidBecomeAvailable:(struct opaqueCMSampleBuffer *)available sequenceIndex:(unsigned int)index isLastFrameOfSegment:(BOOL)segment;
- (void)flush;
- (void)_flushVideo;
- (BOOL)videoBufferIsFull;
- (void)frameDidBecomeAvailable:(struct AudioStreamBasicDescription { double x0; unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; })available frameMetadata:(struct FNFInceptionFrameMetadata { unsigned int x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; struct { long long x0; int x1; unsigned int x2; long long x3; } x2; unsigned int x3; BOOL x4; })metadata frame:(id)frame;
- (void)_flushAudio;
- (BOOL)audioBufferIsFull;
- (void)_insertData:(id)data withSegment:(int)segment forTrack:(long long)track;
- (void)_cleanupSegmentAtIndex:(int)index forTrack:(long long)track;
- (id)readDataForTrack:(long long)track segment:(long long)segment offset:(long long)offset completed:(BOOL *)completed;
- (id)_representationIdForSegment:(long long)segment track:(long long)track;
- (void)_cleanupSegmentsBeforeIndex:(int)index track:(long long)track;
- (id)readHeaderDataForTrack:(long long)track representationId:(id)id;
- (id)abrEntitiesForTrack:(long long)track;
- (double)segmentDurationForTrack:(long long)track atIndex:(int)index;
- (int)segmentCountForTrack:(long long)track;
- (void)representationDidChangeForTrack:(long long)track representationId:(id)id representationHeader:(id)header;
- (void)_representationDidChangeForTrack:(long long)track representationId:(id)id representationHeader:(id)header;
- (void)segmentHeaderDidBecomeAvailableForTrack:(long long)track sequenceIndex:(unsigned int)index segmentHeader:(id)header representationId:(id)id;
- (void)_segmentHeaderDidBecomeAvailableForTrack:(long long)track sequenceIndex:(unsigned int)index segmentHeader:(id)header representationId:(id)id;
- (void)_addABREntityWithRepresentationId:(id)id sequenceIndex:(unsigned int)index;
@end

#endif /* FNFMp4SegmentGenerator_h */
