//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAccountStatusIntentTarget_h
#define IGAccountStatusIntentTarget_h
@import Foundation;

#include "FBIntentTarget-Protocol.h"

@class NSString;

@interface IGAccountStatusIntentTarget : NSObject<FBIntentTarget>

@property (readonly, nonatomic) NSString *locationKey;
@property (readonly, nonatomic) NSString *analyticsModule;
@property (readonly, nonatomic) NSString *sessionID;
@property (readonly, nonatomic) NSString *groupFbid;
@property (readonly, nonatomic) id /* block */ onDismiss;
@property (readonly, nonatomic) NSString *enforcementID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithLocationKey:(id)key analyticsModule:(id)module sessionID:(id)id groupFbid:(id)fbid onDismiss:(id /* block */)dismiss enforcementID:(id)id;
@end

#endif /* IGAccountStatusIntentTarget_h */
