//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGBloksSimpleActionPresentableViewerDelegate_h
#define IGBloksSimpleActionPresentableViewerDelegate_h
@import Foundation;

#include "NSObject-Protocol.h"

@class BKLispyEnvironment, BKLispyExpression, NSString;

@interface IGBloksSimpleActionPresentableViewerDelegate : NSObject<NSObject> {
  /* instance variables */
  BKLispyExpression *_onFinishExpression;
  BKLispyEnvironment *_environment;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithOnFinishExpression:(id)expression environment:(id)environment;
- (void)simpleActionPresentableViewerDidFinish:(id)finish fromPageId:(id)id pageTimeSpent:(double)spent didCompleteSurvey:(BOOL)survey;
- (void)simpleActionPresentableViewerWillFinish:(id)finish;
@end

#endif /* IGBloksSimpleActionPresentableViewerDelegate_h */
