//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGContentSchedulingPublishErrorViewController_h
#define IGContentSchedulingPublishErrorViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGGestureHandler-Protocol.h"

@class IGBottomButtonsView, IGMedia, IGNavigationBar, IGUserSession, NSString, UILabel;

@interface IGContentSchedulingPublishErrorViewController : IGViewController<IGGestureHandler> {
  /* instance variables */
  IGUserSession *_userSession;
  IGMedia *_scheduledMedia;
  IGNavigationBar *_navigationBar;
  UILabel *_messageLabel;
  IGBottomButtonsView *_bottomButtonsView;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session scheduledMedia:(id)media;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (BOOL)canRespondToGesture:(id)gesture;
@end

#endif /* IGContentSchedulingPublishErrorViewController_h */
