//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGConsentFlowHostControllerV2_h
#define IGConsentFlowHostControllerV2_h
@import Foundation;

#include "UIViewController.h"
#include "ConsentFlowContainerDismissDelegate-Protocol.h"
#include "ConsentLoadingView.h"
#include "IGConsentFlowLauncher.h"
#include "IGConsentFlowStateManager.h"
#include "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface IGConsentFlowHostControllerV2 : UIViewController<ConsentFlowContainerDismissDelegate, UIViewControllerTransitioningDelegate> {
  /* instance variables */
  NSString *_initialFlowName;
  NSString *_source;
  NSString *_deviceId;
  NSString *_extraParam;
  NSString *_appId;
  BOOL _hasLaunchedFlow;
  NSString *_currentFlowName;
  NSString *_triggerKey;
  IGConsentFlowLauncher *_consentFlowLaucher;
  NSMutableArray *_containers;
  ConsentLoadingView *_loadingView;
  id /* block */ _onCloseIAWLink;
  BOOL _shouldEnableTransitionImprovement;
  BOOL _isFlowBeingClosed;
  IGConsentFlowStateManager *_consentStateManager;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFlowName:(id)name source:(id)source deviceId:(id)id extraParam:(id)param appId:(id)id triggerKey:(id)key consentFlowLauncher:(id)launcher;
- (void)viewDidAppear:(BOOL)appear;
- (void)viewWillDisappear:(BOOL)disappear;
- (void)showLoadingSpinner;
- (void)addScreenViewController:(id)controller;
- (void)dismissScreen:(id /* block */)screen;
- (void)addDialogViewController:(id)controller;
- (void)dismissDialogViewController:(id /* block */)controller;
- (void)dismissBottomSheetController:(id /* block */)controller;
- (void)addBottomSheetController:(id)controller;
- (void)presentIAWLink:(id)iawlink userSession:(id)session onClose:(id /* block */)close;
- (id)animationControllerForPresentedController:(id)controller presentingController:(id)controller sourceController:(id)controller;
- (id)animationControllerForDismissedController:(id)controller;
- (void)lastContainerDismissedSelf;
- (void)browserControllerDidDismissWithUrl:(id)url;
- (void)browserControllerDidChangeUrl:(id)url;
- (void)didRequestPopupForNavigationAction:(id)action;
@end

#endif /* IGConsentFlowHostControllerV2_h */
