//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGCustomFilterEditorViewController_h
#define IGCustomFilterEditorViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGCustomFeedFilterHeaderView.h"
#include "IGGestureHandler-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGListAdapterDelegate-Protocol.h"
#include "IGSearchBarDelegate-Protocol.h"
#include "IGUserList.h"
#include "IGUserListNetworkDataSourceDelegate-Protocol.h"
#include "IGUserListSectionControllerSelectionDelegate-Protocol.h"

@class FBTimer, IGBasicListViewController, IGFullscreenSearchTransitionController, IGFullscreenSearchViewController, IGSearchBar, IGUserListNetworkDataSource, IGUserSession, NSArray, NSMutableSet, NSOrderedSet, NSString;

@interface IGCustomFilterEditorViewController : IGViewController<IGSearchBarDelegate, IGListAdapterDelegate, IGListAdapterDataSource, IGUserListNetworkDataSourceDelegate, IGUserListSectionControllerSelectionDelegate, IGGestureHandler> {
  /* instance variables */
  IGUserList *_userList;
  IGUserSession *_userSession;
  IGCustomFeedFilterHeaderView *_headerView;
  IGSearchBar *_searchBar;
  IGBasicListViewController *_currentFilterListViewController;
  IGFullscreenSearchViewController *_fullScreenSearchViewController;
  IGFullscreenSearchTransitionController *_searchTransitionController;
  IGUserListNetworkDataSource *_searchDataSource;
  NSArray *_displayedSearchUsers;
  FBTimer *_backoffTimer;
  IGUserListNetworkDataSource *_followingListDataSource;
  IGUserList *_editedUserList;
  NSMutableSet *_loadedUserIDs;
  NSOrderedSet *_suggestedUserIDs;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session userList:(id)list;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)appear;
- (void)viewDidLayoutSubviews;
- (BOOL)canRespondToGesture:(id)gesture;
- (void)_saveAndExitTapped;
- (void)_deleteTapped;
- (void)_addTapped;
- (void)_searchCancelTapped;
- (void)customFeedFilterHeaderViewTextFieldDidChange:(id)change toString:(id)string;
- (void)searchBar:(id)bar didChangeSearchText:(id)text;
- (void)searchBarDidTapReturnKey:(id)key;
- (BOOL)searchBarShouldBeginEditing:(id)editing;
- (id)emptyViewForListAdapter:(id)adapter;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (void)listAdapter:(id)adapter didEndDisplayingObject:(id)object atIndex:(long long)index;
- (void)listAdapter:(id)adapter willDisplayObject:(id)object atIndex:(long long)index;
- (void)_dismissSearch;
- (void)userListSectionControllerDidDeselectUser:(id)user;
- (void)userListSectionControllerDidSelectUser:(id)user;
- (void)dataSourceDidStartLoading:(id)loading;
- (void)dataSourceDidFailLoad:(id)load;
- (void)dataSourceDidFinishLoading:(id)loading;
@end

#endif /* IGCustomFilterEditorViewController_h */
