//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectAudioMessageBubbleViewModel_h
#define IGDirectAudioMessageBubbleViewModel_h
@import Foundation;

#include "FBValueObject.h"
#include "IGUserLauncherSetProviding-Protocol.h"
#include "NSCoding-Protocol.h"
#include "NSCopying-Protocol.h"

@class IGAudioProgressViewModel, IGDirectAudio, IGDirectGradientTintableTintConfig, IGDirectMessageBubbleStyle, NSString;

@interface IGDirectAudioMessageBubbleViewModel : FBValueObject<NSCopying, NSCoding>

@property (readonly, copy, nonatomic) IGDirectMessageBubbleStyle *bubbleStyle;
@property (readonly, copy, nonatomic) NSString *contentType;
@property (readonly, nonatomic) double contentWidth;
@property (readonly, nonatomic) double contentHeight;
@property (readonly, copy, nonatomic) IGDirectAudio *audio;
@property (readonly, copy, nonatomic) IGAudioProgressViewModel *audioProgressViewModel;
@property (readonly, copy, nonatomic) IGDirectGradientTintableTintConfig *iconTintConfig;
@property (readonly, nonatomic) struct CGSize { double x0; double x1; } iconSize;
@property (readonly, nonatomic) NSObject<IGUserLauncherSetProviding> *featureSetProvider;

/* instance methods */
- (id)initWithBubbleStyle:(id)style contentType:(id)type contentWidth:(double)width contentHeight:(double)height audio:(id)audio audioProgressViewModel:(id)model iconTintConfig:(id)config iconSize:(struct CGSize { double x0; double x1; })size featureSetProvider:(id)provider;
@end

#endif /* IGDirectAudioMessageBubbleViewModel_h */
