//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectInboxSearchUnconnectedChannelsDisclosureViewController_h
#define IGDirectInboxSearchUnconnectedChannelsDisclosureViewController_h
@import Foundation;

#include "UIViewController.h"
#include "IGGestureHandler-Protocol.h"

@class NSString, UILabel;

@interface IGDirectInboxSearchUnconnectedChannelsDisclosureViewController : UIViewController<IGGestureHandler> {
  /* instance variables */
  UILabel *_titleLabel;
  UILabel *_bodyLabel;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithLauncherSetProvider:(id)provider;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (BOOL)canRespondToGesture:(id)gesture;
- (struct CGSize { double x0; double x1; })preferredContentSize;
@end

#endif /* IGDirectInboxSearchUnconnectedChannelsDisclosureViewController_h */
