//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectLiveLocationMapAnnotation_h
#define IGDirectLiveLocationMapAnnotation_h
@import Foundation;

#include "MKPointAnnotation.h"

@class IGUser, NSString;

@interface IGDirectLiveLocationMapAnnotation : MKPointAnnotation

@property (retain, nonatomic) IGUser *user;
@property (retain, nonatomic) NSString *identifier;

/* instance methods */
- (id)initWithCoordinate:(struct CLLocationCoordinate2D { double x0; double x1; })coordinate;
@end

#endif /* IGDirectLiveLocationMapAnnotation_h */
