//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectGroupsCreationFlowSelectorViewController_h
#define IGDirectGroupsCreationFlowSelectorViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGDirectGroupsCreationCoordinatorControlling-Protocol.h"
#include "IGDirectGroupsCreationFlowContext.h"
#include "IGGestureHandler-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"

@class IGListAdapter, NSString, UICollectionView;

@interface IGDirectGroupsCreationFlowSelectorViewController : IGViewController<IGListAdapterDataSource, IGGestureHandler> {
  /* instance variables */
  UICollectionView *_collectionView;
  IGListAdapter *_listAdapter;
  IGDirectGroupsCreationFlowContext *_context;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) NSObject<IGDirectGroupsCreationCoordinatorControlling> *coordinator;

/* class methods */
+ (BOOL)isValidForContext:(id)context;

/* instance methods */
- (id)initWithContext:(id)context;
- (long long)preferredTabBarBehavior;
- (BOOL)prefersNavigationBarDividerHidden;
- (id)viewController;
- (id)stepName;
- (long long)presentationStyle;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)appear;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (void)_backButtonTapped;
- (BOOL)canRespondToGesture:(id)gesture;
@end

#endif /* IGDirectGroupsCreationFlowSelectorViewController_h */
