//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDiscoveryChannelSectionController_h
#define IGDiscoveryChannelSectionController_h
@import Foundation;

#include "IGListSectionController.h"
#include "IGDiscoveryGridHiddenStateHelper.h"
#include "IGFeedPreviewableSectionController-Protocol.h"

@class IGDiscoveryGridItem, IGDiscoveryTopicModel, IGPlaybackCoordinator, IGUserSession, NSString;
@protocol IGDiscoveryChannelSectionControllerSelectionDelegate, IGDiscoveryGridLoggingProvider, IGDiscoverySectionLoggingProvider, IGGridItemPositionProvider;

@interface IGDiscoveryChannelSectionController : IGListSectionController<IGFeedPreviewableSectionController> {
  /* instance variables */
  IGUserSession *_userSession;
  IGDiscoveryGridItem *_gridItem;
  IGPlaybackCoordinator *_playbackCoordinator;
  struct IGGridLayoutConfiguration { double interitemSpacing; struct UIEdgeInsets { double top; double left; double bottom; double right; } insets; double mediasPerRow; double aspectRatio; double cellCornerRadius; } _layoutConfig;
  NSObject<IGDiscoverySectionLoggingProvider> *_discoveryLoggingProvider;
  NSObject<IGDiscoveryChannelSectionControllerSelectionDelegate> *_selectionDelegate;
  NSObject<IGGridItemPositionProvider> *_gridPositionProvider;
  IGDiscoveryTopicModel *_topic;
  IGDiscoveryGridHiddenStateHelper *_hiddenStateHelper;
  unsigned long long _loggingScheme;
  NSObject<IGDiscoveryGridLoggingProvider> *_gridLoggingProvider;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithLayoutConfig:(struct IGGridLayoutConfiguration { double x0; struct UIEdgeInsets { double x0; double x1; double x2; double x3; } x1; double x2; double x3; double x4; })config userSession:(id)session playbackCoordinator:(id)coordinator discoveryLoggingProvider:(id)provider selectionDelegate:(id)delegate loggingScheme:(unsigned long long)scheme gridPositionProvider:(id)provider gridLoggingProvider:(id)provider topic:(id)topic;
- (id)cellForItemAtIndex:(long long)index;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)index;
- (void)didUpdateToObject:(id)object;
- (void)didSelectItemAtIndex:(long long)index;
- (void)presentFeedPreviewableItem;
@end

#endif /* IGDiscoveryChannelSectionController_h */
