//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectMsysSafetyNoticesMegaphoneLogger_h
#define IGDirectMsysSafetyNoticesMegaphoneLogger_h
@import Foundation;

#include "IGAnalyticsEventLoggingProtocol-Protocol.h"
#include "IGGenericMegaphoneLogger-Protocol.h"

@class IGDirectMsysConfirmedThreadIdentifier, IGDirectMsysMessagingMailbox, IGUserSession, NSString;

@interface IGDirectMsysSafetyNoticesMegaphoneLogger : NSObject<IGGenericMegaphoneLogger> {
  /* instance variables */
  IGUserSession *_userSession;
  NSObject<IGAnalyticsEventLoggingProtocol> *_logger;
  IGDirectMsysConfirmedThreadIdentifier *_threadIdentifier;
  NSString *_analyticsModule;
  NSString *_sessionId;
  IGDirectMsysMessagingMailbox *_mailboxProvider;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session threadIdentifier:(id)identifier analyticsModule:(id)module sessionId:(id)id mailboxProvider:(id)provider;
- (void)logMegaphoneWasSeen:(id)seen;
- (void)logMegaphoneDismissed:(id)dismissed;
- (void)logMegaphoneButtonTapped:(id)tapped onButton:(id)button;
@end

#endif /* IGDirectMsysSafetyNoticesMegaphoneLogger_h */
