//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectQuotedReplyQuotedMessageViewModelContent_h
#define IGDirectQuotedReplyQuotedMessageViewModelContent_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "IGDirectAnimatedMediaMessageBubbleViewModel.h"
#include "IGDirectAudioMessageBubbleViewModel.h"
#include "IGDirectContextReplyBubbleContentViewModel.h"
#include "IGDirectExpiredPlaceholderMessageViewModel.h"
#include "IGDirectHscrollXMAMessageSingleItemViewModel.h"
#include "IGDirectLayeredXMAMessageBubbleViewModel.h"
#include "IGDirectMediaPileViewModel.h"
#include "IGDirectPhotoMessageBubbleViewModel.h"
#include "IGDirectPortraitXMAMessageBubbleViewModel.h"
#include "IGDirectStoryMessageBubbleViewModel.h"
#include "IGDirectSundialMessageBubbleViewModel.h"
#include "IGDirectTextMessageBubbleViewModel.h"
#include "IGDirectVideoMessageBubbleViewModel.h"
#include "IGDirectVisualMessagePreviewBubbleViewModel.h"
#include "IGDirectVisualMessageTombstoneBubbleViewModel.h"

@class IGMedia, NSOrderedSet, NSString;

@interface IGDirectQuotedReplyQuotedMessageViewModelContent : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  IGDirectTextMessageBubbleViewModel *_text_textMessageBubbleViewModel;
  IGDirectPhotoMessageBubbleViewModel *_photo_quotedPhotoMessageBubbleViewModel;
  long long _photo_mediaType;
  NSString *_photo_mediaId;
  IGDirectVideoMessageBubbleViewModel *_video_quotedVideoMessageBubbleViewModel;
  long long _video_mediaType;
  NSString *_video_mediaId;
  IGDirectAudioMessageBubbleViewModel *_audio_audioMessageBubbleViewModel;
  IGDirectPhotoMessageBubbleViewModel *_post_quotedPhotoMessageBubbleViewModel;
  IGMedia *_post_media;
  long long _post_mediaType;
  NSString *_post_mediaId;
  NSString *_post_postItemPk;
  IGDirectVisualMessagePreviewBubbleViewModel *_visualMessagePreview_quotedVisualMessagePreviewBubbleViewModel;
  NSOrderedSet *_visualMessagePreview_unseenVisualMessages;
  IGDirectVisualMessageTombstoneBubbleViewModel *_visualMessageTombstone_visualMessageTombstoneBubbleViewModel;
  NSOrderedSet *_visualMessageTombstone_unseenVisualMessages;
  IGDirectSundialMessageBubbleViewModel *_sundial_quotedSundialBubbleViewModel;
  IGDirectPortraitXMAMessageBubbleViewModel *_portraitXma_portraitXmaBubbleViewModel;
  IGDirectLayeredXMAMessageBubbleViewModel *_layeredXma_layeredXmaBubbleViewModel;
  IGDirectStoryMessageBubbleViewModel *_story_quotedStoryMessageViewModel;
  IGDirectAnimatedMediaMessageBubbleViewModel *_animatedMedia_quotedAnimatedMediaMessageViewModel;
  IGDirectHscrollXMAMessageSingleItemViewModel *_hscrollXma_hscrollXmaViewModel;
  IGDirectMediaPileViewModel *_mediaPile_quotedMediaPileViewModel;
  IGDirectAnimatedMediaMessageBubbleViewModel *_avatarSticker_avatarMessageBubbleViewModel;
  IGDirectContextReplyBubbleContentViewModel *_selfieReaction_quotedContextReplyBubbleContentViewModel;
  IGMedia *_selfieReaction_media;
  IGDirectExpiredPlaceholderMessageViewModel *_expiredPlaceholder_quotedExpiredPlaceholderMessageViewModel;
}

/* class methods */
+ (id)animatedMediaWithQuotedAnimatedMediaMessageViewModel:(id)model;
+ (id)audioWithAudioMessageBubbleViewModel:(id)model;
+ (id)avatarStickerWithAvatarMessageBubbleViewModel:(id)model;
+ (id)expiredPlaceholderWithQuotedExpiredPlaceholderMessageViewModel:(id)model;
+ (id)giphySticker;
+ (id)hscrollXmaWithHscrollXmaViewModel:(id)model;
+ (id)layeredXmaWithLayeredXmaBubbleViewModel:(id)model;
+ (id)mediaPileWithQuotedMediaPileViewModel:(id)model;
+ (id)photoWithQuotedPhotoMessageBubbleViewModel:(id)model mediaType:(long long)type mediaId:(id)id;
+ (id)portraitXmaWithPortraitXmaBubbleViewModel:(id)model;
+ (id)postWithQuotedPhotoMessageBubbleViewModel:(id)model media:(id)media mediaType:(long long)type mediaId:(id)id postItemPk:(id)pk;
+ (id)selfieReactionWithQuotedContextReplyBubbleContentViewModel:(id)model media:(id)media;
+ (id)storyWithQuotedStoryMessageViewModel:(id)model;
+ (id)sundialWithQuotedSundialBubbleViewModel:(id)model;
+ (id)textWithTextMessageBubbleViewModel:(id)model;
+ (id)videoWithQuotedVideoMessageBubbleViewModel:(id)model mediaType:(long long)type mediaId:(id)id;
+ (id)visualMessagePreviewWithQuotedVisualMessagePreviewBubbleViewModel:(id)model unseenVisualMessages:(id)messages;
+ (id)visualMessageTombstoneWithVisualMessageTombstoneBubbleViewModel:(id)model unseenVisualMessages:(id)messages;

/* instance methods */
@end

#endif /* IGDirectQuotedReplyQuotedMessageViewModelContent_h */
