//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectMediaPileBubbleViewModelMatcher_h
#define IGDirectMediaPileBubbleViewModelMatcher_h
@import Foundation;

@interface IGDirectMediaPileBubbleViewModelMatcher : NSObject
/* class methods */
+ (id)match:(id)match photoBubbleViewModel:(id /* block */)model videoBubbleViewModel:(id /* block */)model textBubbleViewModel:(id /* block */)model xmaBubbleViewModel:(id /* block */)model;
@end

#endif /* IGDirectMediaPileBubbleViewModelMatcher_h */
