//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectMessageDisplayAnnouncementSectionController_h
#define IGDirectMessageDisplayAnnouncementSectionController_h
@import Foundation;

#include "IGListBindingSingleSectionController.h"
#include "IGDirectMessageViewModelProtocol-Protocol.h"
#include "IGListDisplayDelegate-Protocol.h"

@class NSString;
@protocol IGDirectMessageDisplayAnnouncementDelegate;

@interface IGDirectMessageDisplayAnnouncementSectionController : IGListBindingSingleSectionController<IGListDisplayDelegate> {
  /* instance variables */
  NSObject<IGDirectMessageDisplayAnnouncementDelegate> *_messageDisplayAnnouncementDelegate;
}

@property (retain, nonatomic) NSObject<IGDirectMessageViewModelProtocol> *viewModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller;
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller cell:(id)cell atIndex:(long long)index;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller cell:(id)cell atIndex:(long long)index;
@end

#endif /* IGDirectMessageDisplayAnnouncementSectionController_h */
