//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectActionChainingController_h
#define IGDirectActionChainingController_h
@import Foundation;

#include "IGDirectActionChainingViewModel.h"
#include "IGPartialModalSheetListener-Protocol.h"

@class IGActionableConfirmationToastPresenter, IGUserSession, NSString, UIViewController;
@protocol IGDirectActionChainingControllerDelegate;

@interface IGDirectActionChainingController : NSObject<IGPartialModalSheetListener> {
  /* instance variables */
  IGDirectActionChainingViewModel *_viewModel;
  IGUserSession *_userSession;
  UIViewController *_presentingViewController;
  id /* block */ _actionHandle;
  IGActionableConfirmationToastPresenter *_toastPresenter;
  unsigned long long _analyticsModuleType;
}

@property (weak, nonatomic) NSObject<IGDirectActionChainingControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithViewModel:(id)model userSession:(id)session hostViewController:(id)controller actionHandle:(id /* block */)handle analyticsModule:(long long)module;
- (void)didSelectActionChainItem:(id)item user:(id)user;
- (void)partialModalSheetDidDismiss:(id)dismiss;
- (void)partialModalSheet:(id)sheet didUpdateOffset:(double)offset presentationProgress:(double)progress;
- (void)partialModalSheet:(id)sheet willChangeState:(unsigned long long)state;
- (void)partialModalSheet:(id)sheet didChangeState:(unsigned long long)state;
@end

#endif /* IGDirectActionChainingController_h */
