//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectInboxHeaderSectionController_h
#define IGDirectInboxHeaderSectionController_h
@import Foundation;

#include "IGListBindingSingleSectionController.h"
#include "IGDirectInboxCellSelectCoordinator.h"
#include "IGDirectInboxConfig.h"
#include "IGDirectInboxHeaderCell.h"
#include "IGDirectInboxHeaderCellViewModel.h"
#include "NSObject-Protocol.h"

@class NSString;
@protocol IGDirectInboxHeaderSectionControllerDelegate;

@interface IGDirectInboxHeaderSectionController : IGListBindingSingleSectionController<NSObject> {
  /* instance variables */
  IGDirectInboxConfig *_inboxConfig;
  NSObject<IGDirectInboxHeaderSectionControllerDelegate> *_delegate;
  IGDirectInboxCellSelectCoordinator *_selectCoordinator;
  IGDirectInboxHeaderCell *_cell;
}

@property (readonly, nonatomic) IGDirectInboxHeaderCellViewModel *viewModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithInboxConfig:(id)config delegate:(id)delegate selectCoordinator:(id)coordinator;
- (void)dealloc;
- (Class)cellClass;
- (struct CGSize { double x0; double x1; })sizeForViewModel:(id)model;
- (void)configureCell:(id)cell withViewModel:(id)model;
- (void)didUpdateToObject:(id)object;
- (void)didTapHeaderActionButtonInDirectInboxHeaderCell:(id)cell viewModel:(id)model;
- (void)didTapHeaderIconButtonInDirectInboxHeaderCell:(id)cell viewModel:(id)model;
- (void)inboxHeaderCellDidTapTab:(id)tab;
- (void)inboxHeaderCellDidDissmisBusinessHighVolumeStateBanner:(id)banner;
- (void)inboxHeaderCellBusinessHighVolumeStateBannerDidTapActionButton:(id)button;
- (void)directInboxCellSelectStateDidUpdate:(long long)update;
- (void)directInboxCellSelectActionBarVisibilityDidUpdate;
- (void)directInboxCellSelectedCellsDidUpdate;
@end

#endif /* IGDirectInboxHeaderSectionController_h */
