//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectInboxEncryptedBackupsInboxLandingHandler_h
#define IGDirectInboxEncryptedBackupsInboxLandingHandler_h
@import Foundation;

#include "IGDirectEncryptedBackupsAutoRestoreManager.h"
#include "IGDirectEncryptedBackupsDynamicSetupFlowHandler.h"
#include "IGDirectEncryptedBackupsInboxPresentationHelper.h"
#include "IGScopedListener-Protocol.h"

@class IGUserSession, IGViewController, NSArray, NSString;
@protocol IGDirectInboxEncryptedBackupsInboxLandingHandlerDelegate;

@interface IGDirectInboxEncryptedBackupsInboxLandingHandler : NSObject<IGScopedListener> {
  /* instance variables */
  NSObject<IGDirectInboxEncryptedBackupsInboxLandingHandlerDelegate> *_delegate;
  IGUserSession *_userSession;
  IGViewController *_parentViewController;
  IGDirectEncryptedBackupsDynamicSetupFlowHandler *_hardBlockFlowHandler;
  IGDirectEncryptedBackupsAutoRestoreManager *_ebAutoRestoreManager;
  NSArray *_dismissedVC;
  IGDirectEncryptedBackupsInboxPresentationHelper *_presentationHelper;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDelegate:(id)delegate userSession:(id)session;
- (void)setupFlowDidTapBackFromHardBlock;
- (void)setupFlowDidTapBackFromSource:(long long)source;
- (void)setupFlowDidFinishFromHardBlockWithStatus:(long long)status source:(long long)source;
- (void)setupFlowDidTapTryAgainWithSource:(long long)source;
- (void)_handleHardBlockReleaseIndecision;
- (void)_startRestoreReengageToastMarker;
@end

#endif /* IGDirectInboxEncryptedBackupsInboxLandingHandler_h */
