//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectServicesCtaButtonHandler_h
#define IGDirectServicesCtaButtonHandler_h
@import Foundation;

#include "IGDirectXMACtaButtonHandling-Protocol.h"

@class IGUserSession, NSString;

@interface IGDirectServicesCtaButtonHandler : NSObject<IGDirectXMACtaButtonHandling> {
  /* instance variables */
  IGUserSession *_userSession;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session;
- (void)didTapCtaButtonWithViewModel:(id)model actionURL:(id)url postbackPayload:(id)payload actionTitle:(id)title indexId:(id)id sourceController:(id)controller adsContext:(id)context;
@end

#endif /* IGDirectServicesCtaButtonHandler_h */
