//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectThreadViewController_Initializers_h
#define IGDirectThreadViewController_Initializers_h
@import Foundation;

@interface IGDirectThreadViewController (Initializers)
/* instance methods */
- (id)initWithUserSession:(id)session thread:(id)thread entryPoint:(id)point adsContext:(id)context searchContext:(id)context messageIdToScrollTo:(id)to perfComponents:(id)components privateReplyPayload:(id)payload threadLoggingContext:(id)context messageIslandContext:(id)context initialParams:(id)params isThreadLockUnlocked:(BOOL)unlocked;
@end

#endif /* IGDirectThreadViewController_Initializers_h */
