//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectVisualMessageViewerPresentationManager_Protocol_h
#define IGDirectVisualMessageViewerPresentationManager_Protocol_h
@import Foundation;

@protocol IGDirectVisualMessageViewerPresentationManager <NSObject>
/* instance methods */
- (void)presentVisualMessageViewerForThreadKey:(id)key currentVisualMessage:(id)message visualMessagePresentationTarget:(id)target entryPoint:(long long)point threadTheme:(id)theme gradientBubbleTracker:(id)tracker sourceController:(id)controller contextIdentifier:(id)identifier contextDelegate:(id)delegate autoLoopingMode:(unsigned long long)mode messageReplyHandler:(id)handler analyticsModule:(id)module sendAttributionFactory:(id /* block */)factory lastSeenShhMessageInfoForCurrentUserWhenEnteringShhMode:(id)mode viewerConfiguration:(id)configuration dismissalDelegate:(id)delegate shouldHideComposerOnBlockedParticipant:(BOOL)participant isRecipientBlocked:(BOOL)blocked completion:(id /* block */)completion;
- (void)presentVisualMessageTimelineForThreadKey:(id)key currentVisualMessage:(id)message visualMessagePresentationTarget:(id)target entryPoint:(long long)point sourceController:(id)controller contextIdentifier:(id)identifier contextDelegate:(id)delegate autoLoopingMode:(unsigned long long)mode messageReplyHandler:(id)handler analyticsModule:(id)module sendAttributionFactory:(id /* block */)factory lastSeenShhMessageInfoForCurrentUserWhenEnteringShhMode:(id)mode userSession:(id)session recipient:(id)recipient openToCamera:(BOOL)camera shouldHideComposerOnBlockedParticipant:(BOOL)participant isRecipientBlocked:(BOOL)blocked completion:(id /* block */)completion;
- (void)cancelPresentationForContextDelegate:(id)delegate;
- (id)currentPreloadContextIdentifier;
- (long long)maxViewerLimit;
- (void)addListener:(id)listener;
- (void)removeListener:(id)listener;
@end

#endif /* IGDirectVisualMessageViewerPresentationManager_Protocol_h */
