//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectEncryptedBackupsPinResetFlowHandler_h
#define IGDirectEncryptedBackupsPinResetFlowHandler_h
@import Foundation;

#include "NSObject-Protocol.h"

@class IGNavigationController, IGUserSession, NSString, UIViewController;

@interface IGDirectEncryptedBackupsPinResetFlowHandler : NSObject<NSObject> {
  /* instance variables */
  UIViewController *_presentingController;
  IGNavigationController *_navigationController;
  IGUserSession *_userSession;
  unsigned long long _pinFlowType;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithPresentingController:(id)controller userSession:(id)session;
- (void)startPinResetFlow;
- (void)presentPinSetupConfirm:(id)confirm;
- (void)presentPinSetupConfirmFromSettings:(id)settings;
- (void)handlePinMismatch;
- (void)onPinRegister;
- (void)onPinRegisterSuccess;
- (void)onPinRegisterFailure;
- (void)onPinLoginSuccess;
- (void)onPinCancel;
- (void)showRetryToast;
- (void)enterOneTimeCodeFlow;
@end

#endif /* IGDirectEncryptedBackupsPinResetFlowHandler_h */
