//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectThreadEditHistoryViewModelInstructionsGenerator_h
#define IGDirectThreadEditHistoryViewModelInstructionsGenerator_h
@import Foundation;

#include "IGAPIClient-Protocol.h"
#include "IGDirectInteropFeatureGating-Protocol.h"
#include "IGDirectMsysMailboxProviding-Protocol.h"
#include "NSObject-Protocol.h"

@class IGDirectGenericShareOutgoingPreviewDataLocalCache, IGDirectInstamadilloEncryptedBackupsClientStateManager, IGDirectMessageCellContentStringStylesProvider, IGDirectMessageCellThemeProvider, IGDirectOutgoingPermanentMediaLocalCache, IGE2EEMediaManager, IGRingViewSpecFactory, IGUser, IGUserDefaults, IGUserStore, NSString;

@interface IGDirectThreadEditHistoryViewModelInstructionsGenerator : NSObject<NSObject> {
  /* instance variables */
  IGUserStore *_userStore;
  NSObject<IGDirectInteropFeatureGating> *_featureGating;
  IGUser *_currentUser;
  IGUserDefaults *_userDefaults;
  IGDirectMessageCellThemeProvider *_themeProvider;
  IGDirectMessageCellContentStringStylesProvider *_contentStringStylesProvider;
  IGRingViewSpecFactory *_ringViewSpecFactory;
  IGDirectGenericShareOutgoingPreviewDataLocalCache *_outgoingPreviewDataCache;
  IGDirectOutgoingPermanentMediaLocalCache *_directOutgoingPermanentMediaLocalCache;
  NSObject<IGDirectMsysMailboxProviding> *_mailboxProvider;
  NSObject<IGAPIClient> *_networker;
  IGDirectInstamadilloEncryptedBackupsClientStateManager *_EBClientStateManager;
  IGE2EEMediaManager *_e2eeMediaManager;
  NSString *_analyticsModule;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFeatureGating:(id)gating userStore:(id)store userDefaults:(id)defaults currentUser:(id)user themeProvider:(id)provider contentStringStylesProvider:(id)provider ringViewSpecFactor:(id)factor outgoingPreviewDataCache:(id)cache permanentMediaLocalCache:(id)cache mailboxProvider:(id)provider networker:(id)networker EBClientStateManager:(id)manager e2eeMediaManager:(id)manager analyticsModule:(id)module;
- (id)generateInstructionsForMessages:(id)messages generationInput:(id)input previousGenerationOutput:(id)output;
@end

#endif /* IGDirectThreadEditHistoryViewModelInstructionsGenerator_h */
