//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGDirectGroupsCreationSettingsStepController_h
#define IGDirectGroupsCreationSettingsStepController_h
@import Foundation;

#include "IGDirectChangeGroupIconActionManager.h"
#include "IGDirectGroupsCreationCoordinatorControlling-Protocol.h"
#include "IGDirectGroupsCreationFlowContext.h"
#include "IGDirectGroupsCreationSettingsViewController.h"
#include "NSObject-Protocol.h"

@class NSString;

@interface IGDirectGroupsCreationSettingsStepController : NSObject<NSObject> {
  /* instance variables */
  IGDirectGroupsCreationFlowContext *_context;
  IGDirectGroupsCreationSettingsViewController *_settingsViewController;
  IGDirectChangeGroupIconActionManager *_changeGroupIconActionManager;
  long long _profilePictureOption;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) NSObject<IGDirectGroupsCreationCoordinatorControlling> *coordinator;

/* class methods */
+ (BOOL)isValidForContext:(id)context;

/* instance methods */
- (id)initWithContext:(id)context;
- (id)viewController;
- (id)stepName;
- (long long)presentationStyle;
- (void)settingsViewController:(id)controller didTapCreateButtonWithCompletion:(id /* block */)completion;
- (void)settingsViewControllerDidTapBack:(id)back;
- (void)settingsViewControllerDidTapNext:(id)next;
- (void)settingsViewControllerViewDidRender:(id)render;
- (void)settingsViewController:(id)controller didUpdateGroupName:(id)name;
- (void)settingsViewController:(id)controller didUpdateGroupImage:(id)image fromOption:(long long)option;
- (void)settingsViewController:(id)controller didToggleSubscribers:(BOOL)subscribers;
- (void)settingsViewController:(id)controller didTogglePinToProfile:(BOOL)profile;
- (void)settingsViewController:(id)controller didTogglePinToInbox:(BOOL)inbox;
- (void)settingsViewController:(id)controller didSwitchToAudienceType:(long long)type;
- (void)settingsViewController:(id)controller didSelectChannelDurationOption:(id)option;
- (void)settingsViewController:(id)controller didToggleAddCommentControl:(BOOL)control;
@end

#endif /* IGDirectGroupsCreationSettingsStepController_h */
