//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGExternalLinkFriendshipPromoter_h
#define IGExternalLinkFriendshipPromoter_h
@import Foundation;

#include "FBCancelable-Protocol.h"
#include "IGExternalLinkSharingContext.h"
#include "IGFacepileDialogView.h"
#include "NSObject-Protocol.h"

@class IGFeaturedUserInfo, IGUserSession, NSString, UIViewController;
@protocol IGExternalLinkFriendshipPromoterDataSource, IGExternalLinkFriendshipPromoterDelegate;

@interface IGExternalLinkFriendshipPromoter : NSObject<NSObject> {
  /* instance variables */
  IGExternalLinkSharingContext *_context;
  IGUserSession *_userSession;
  UIViewController *_viewController;
  IGFacepileDialogView *_dialogView;
  BOOL _shouldScheduleToast;
  IGFeaturedUserInfo *_userInfo;
  NSObject<FBCancelable> *_scheduledLoad;
  NSString *_analyticsModule;
  NSString *_entryPoint;
}

@property (weak, nonatomic) NSObject<IGExternalLinkFriendshipPromoterDataSource> *dataSource;
@property (weak, nonatomic) NSObject<IGExternalLinkFriendshipPromoterDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)_handleResponse:(id)response;
- (void)facepileDialogView:(id)view didTapViewWithUserInfo:(id)info;
- (void)facepileDialogView:(id)view didTapPrimaryButtonWithUserInfo:(id)info;
- (void)facepileDialogView:(id)view didTapSecondaryButtonWithUserInfo:(id)info;
@end

#endif /* IGExternalLinkFriendshipPromoter_h */
