//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGFeedItemMediaCollectionScrollableThumbnailSectionController_h
#define IGFeedItemMediaCollectionScrollableThumbnailSectionController_h
@import Foundation;

#include "IGListSectionController.h"
#include "IGALLogContextModelProvider-Protocol.h"
#include "IGFeedConfigurationType-Protocol.h"
#include "IGFeedItemMediaCollectionThumbnailViewModel.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGListAdapterDelegate-Protocol.h"
#include "IGListDisplayDelegate-Protocol.h"
#include "UICollectionViewDelegateFlowLayout-Protocol.h"
#include "UIGestureRecognizerDelegate-Protocol.h"

@class IGListAdapter, NSString, UICollectionView;

@interface IGFeedItemMediaCollectionScrollableThumbnailSectionController : IGListSectionController<IGListDisplayDelegate, UIGestureRecognizerDelegate, IGALLogContextModelProvider, IGListAdapterDelegate, IGListAdapterDataSource, UICollectionViewDelegateFlowLayout> {
  /* instance variables */
  IGFeedItemMediaCollectionThumbnailViewModel *_viewModel;
  NSObject<IGFeedConfigurationType> *_feedConfiguration;
  UICollectionView *_collectionView;
  IGListAdapter *_adapter;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFeedConfiguration:(id)configuration;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)index;
- (id)cellForItemAtIndex:(long long)index;
- (void)didUpdateToObject:(id)object;
- (id)displayDelegate;
- (id)trackingModel;
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller;
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller cell:(id)cell atIndex:(long long)index;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller cell:(id)cell atIndex:(long long)index;
- (void)listAdapter:(id)adapter willDisplayObject:(id)object atIndex:(long long)index;
- (void)listAdapter:(id)adapter didEndDisplayingObject:(id)object atIndex:(long long)index;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (struct CGSize { double x0; double x1; })collectionView:(id)view layout:(id)layout sizeForItemAtIndexPath:(id)path;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })collectionView:(id)view layout:(id)layout insetForSectionAtIndex:(long long)index;
- (double)collectionView:(id)view layout:(id)layout minimumLineSpacingForSectionAtIndex:(long long)index;
@end

#endif /* IGFeedItemMediaCollectionScrollableThumbnailSectionController_h */
