//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGFeedItemSendActionHandler_h
#define IGFeedItemSendActionHandler_h
@import Foundation;

#include "IGFeedConfigurationType-Protocol.h"
#include "IGFeedItemPageCellState.h"
#include "IGFeedSectionControllerBloksDelegate-Protocol.h"
#include "IGFeedShareSheetHandler.h"
#include "IGPointer.h"

@class IGBloksAsyncActionHandler, IGMedia, IGUserSession;
@protocol IGFeedItemWithCarouselLoggingProviderDelegate><IGFeedItemDirectResponseLoggingProviderDelegate><IGFeedItemVideoLoggingProviderDelegate><IGFeedItemLoggingProviderDelegate;

@interface IGFeedItemSendActionHandler : NSObject {
  /* instance variables */
  NSObject<IGFeedConfigurationType> *_feedConfiguration;
  IGMedia *_media;
  IGFeedItemPageCellState *_pageCellState;
  IGUserSession *_userSession;
  NSObject<IGFeedItemWithCarouselLoggingProviderDelegate><IGFeedItemDirectResponseLoggingProviderDelegate><IGFeedItemVideoLoggingProviderDelegate><IGFeedItemLoggingProviderDelegate> *_loggingProvider;
  NSObject<IGFeedSectionControllerBloksDelegate> *_sectionControllerBloksDelegate;
  IGPointer *_sourceViewController;
  IGFeedShareSheetHandler *_shareSheetHandler;
  IGBloksAsyncActionHandler *_asyncActionHandler;
}

/* instance methods */
- (id)initWithFeedConfiguration:(id)configuration media:(id)media pageCellState:(id)state userSession:(id)session loggingProvider:(id)provider sectionControllerBloksDelegate:(id)delegate sourceViewController:(id)controller shareSheetHandler:(id)handler;
@end

#endif /* IGFeedItemSendActionHandler_h */
