//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGFloatingSocialContextViewModel_h
#define IGFloatingSocialContextViewModel_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"

@class IGMedia, IGUser, NSArray, NSString;

@interface IGFloatingSocialContextViewModel : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  NSString *_like_pk;
  IGUser *_like_user;
  IGMedia *_like_media;
  unsigned long long _like_likeBubbleStyle;
  NSString *_comment_pk;
  IGUser *_comment_user;
  IGMedia *_comment_media;
  NSString *_comment_comment;
  NSString *_comment_commentID;
  NSArray *_comment_carouselChildMentions;
  unsigned long long _comment_commentBubbleStyle;
}

/* class methods */
+ (id)commentWithPk:(id)pk user:(id)user media:(id)media comment:(id)comment commentID:(id)id carouselChildMentions:(id)mentions commentBubbleStyle:(unsigned long long)style;
+ (id)likeWithPk:(id)pk user:(id)user media:(id)media likeBubbleStyle:(unsigned long long)style;

/* instance methods */
@end

#endif /* IGFloatingSocialContextViewModel_h */
