//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGFocusStateManager_h
#define IGFocusStateManager_h
@import Foundation;

#include "NSObject-Protocol.h"

@class IGDirectBadgeService, IGUserDefaults, NSString;

@interface IGFocusStateManager : NSObject<NSObject> {
  /* instance variables */
  long long _focusState;
  IGDirectBadgeService *_badgeService;
  IGUserDefaults *_userDefaults;
  BOOL _hasMissedMessageInFocusMode;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithBadgeService:(id)service userDefaults:(id)defaults;
- (void)didUpdateDirectUnseenCount:(id)count;
@end

#endif /* IGFocusStateManager_h */
