//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGFundraiserMediaPickerPostItemSectionController_h
#define IGFundraiserMediaPickerPostItemSectionController_h
@import Foundation;

#include "IGListSectionController.h"
#include "IGListWorkingRangeDelegate-Protocol.h"
#include "IGPostItemProtocol-Protocol.h"

@class NSString;
@protocol IGFundraiserMediaPickerPostItemSectionControllerDelegate;

@interface IGFundraiserMediaPickerPostItemSectionController : IGListSectionController<IGListWorkingRangeDelegate> {
  /* instance variables */
  NSObject<IGPostItemProtocol> *_postItem;
  struct IGGridLayoutConfiguration { double interitemSpacing; struct UIEdgeInsets { double top; double left; double bottom; double right; } insets; double mediasPerRow; double aspectRatio; double cellCornerRadius; } _layoutConfig;
  NSString *_analyticsModule;
}

@property (weak, nonatomic) NSObject<IGFundraiserMediaPickerPostItemSectionControllerDelegate> *selectionDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAnalyticsModule:(id)module layoutConfig:(struct IGGridLayoutConfiguration { double x0; struct UIEdgeInsets { double x0; double x1; double x2; double x3; } x1; double x2; double x3; double x4; })config;
- (long long)numberOfItems;
- (id)cellForItemAtIndex:(long long)index;
- (void)didUpdateToObject:(id)object;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)index;
- (void)didSelectItemAtIndex:(long long)index;
- (void)listAdapter:(id)adapter sectionControllerWillEnterWorkingRange:(id)range;
- (void)listAdapter:(id)adapter sectionControllerDidExitWorkingRange:(id)range;
@end

#endif /* IGFundraiserMediaPickerPostItemSectionController_h */
