//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGGalleryPageCalculator_h
#define IGGalleryPageCalculator_h
@import Foundation;

@class UICollectionView;

@interface IGGalleryPageCalculator : NSObject {
  /* instance variables */
  UICollectionView *_collectionView;
}

@property (readonly, nonatomic) unsigned long long numberOfPages;

/* instance methods */
- (id)initWithCollectionView:(id)view;
@end

#endif /* IGGalleryPageCalculator_h */
