//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGGDPRConsentBottomButtonView_h
#define IGGDPRConsentBottomButtonView_h
@import Foundation;

#include "UIView.h"

@class UIButton, UILabel;
@protocol IGGDPRConsentBottomButtonViewDelegate;

@interface IGGDPRConsentBottomButtonView : UIView {
  /* instance variables */
  UILabel *_separatorLineLabel;
  UIButton *_primaryBottomButton;
  UIButton *_secondaryBottomButton;
  BOOL _isPrimaryButtonEnabled;
}

@property (weak, nonatomic) NSObject<IGGDPRConsentBottomButtonViewDelegate> *delegate;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)setPrimaryButtonEnabled:(BOOL)enabled;
- (void)_didTapOnPrimaryBottomButton;
- (void)_didTapOnSecondaryBottomButton;
@end

#endif /* IGGDPRConsentBottomButtonView_h */
