//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGGenericSearchBarTitleView_h
#define IGGenericSearchBarTitleView_h
@import Foundation;

#include "UIView.h"

@class IGSearchBar;

@interface IGGenericSearchBarTitleView : UIView

@property (readonly, nonatomic) IGSearchBar *searchBar;

/* instance methods */
- (id)initWithSearchBarConfig:(id)config;
- (void)layoutSubviews;
@end

#endif /* IGGenericSearchBarTitleView_h */
