//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGGuideAddProductSavedViewController_h
#define IGGuideAddProductSavedViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGProductTaggingSearchViewController.h"
#include "NSObject-Protocol.h"

@class IGUserSession, NSString;
@protocol IGGuideAddProductSavedViewControllerDelegate;

@interface IGGuideAddProductSavedViewController : IGViewController<NSObject> {
  /* instance variables */
  IGUserSession *_userSession;
  IGProductTaggingSearchViewController *_productPickerViewController;
}

@property (weak, nonatomic) NSObject<IGGuideAddProductSavedViewControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (long long)preferredStatusBarStyle;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })preferredContentInsets;
- (void)taggingSearchViewControllerDidCancel:(id)cancel;
- (void)taggingSearchViewController:(id)controller didSelectProductCollection:(id)collection;
- (void)taggingSearchViewController:(id)controller didSelectUser:(id)user addAsTagInstead:(BOOL)instead;
- (void)taggingSearchViewController:(id)controller didSelectProductItems:(id)items productSelectionBehavior:(id)behavior;
- (void)taggingSearchViewController:(id)controller didSelectFBUser:(id)fbuser IGUserResultShown:(id)shown searchingString:(id)string;
@end

#endif /* IGGuideAddProductSavedViewController_h */
