//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGHashtagFeedItemLogger_h
#define IGHashtagFeedItemLogger_h
@import Foundation;

#include "IGFeedItemLogger.h"
#include "IGContextualFeedLogger-Protocol.h"

@class IGHashtagFollowStatusStore, IGHashtagModel, NSString;

@interface IGHashtagFeedItemLogger : IGFeedItemLogger<IGContextualFeedLogger> {
  /* instance variables */
  IGHashtagFollowStatusStore *_hashtagFollowStatusStore;
  long long _hashtagFeedType;
}

@property (readonly, nonatomic) IGHashtagModel *hashtagModel;
@property (readonly, nonatomic) BOOL isSessionAlive;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithHashtagModel:(id)model hashtagFeedType:(long long)type userSession:(id)session;
- (id)extraDictionaryForMedia:(id)media;
- (id)extraDictionaryForMedia:(id)media directResponseInfo:(id)info;
- (id)extraVideoLoggingDictionaryForMedia:(id)media;
- (void)logSessionDidStartWithMedia:(id)media;
- (void)logSessionDidEndWithMedia:(id)media;
- (id)navigationExtras;
@end

#endif /* IGHashtagFeedItemLogger_h */
