//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGHiddenReasonListCellHeaderType_h
#define IGHiddenReasonListCellHeaderType_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"

@class NSString;

@interface IGHiddenReasonListCellHeaderType : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  NSString *_plain_title;
  long long _tombstone_type;
}

/* class methods */
+ (id)plainWithTitle:(id)title;
+ (id)tombstoneWithType:(long long)type;

/* instance methods */
@end

#endif /* IGHiddenReasonListCellHeaderType_h */
