//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGImmersiveNewPostsIndicatorController_h
#define IGImmersiveNewPostsIndicatorController_h
@import Foundation;

#include "IGNewPostsIndicatorPillView.h"
#include "NSObject-Protocol.h"

@class NSString, UIView, UIViewPropertyAnimator;
@protocol IGImmersiveNewPostsIndicatorControllerDelegate;

@interface IGImmersiveNewPostsIndicatorController : NSObject<NSObject> {
  /* instance variables */
  IGNewPostsIndicatorPillView *_newPostsIndicatorView;
  double _top;
  UIView *_containerView;
  UIView *_siblingView;
  double _topInsetAdjustment;
  long long _appearance;
  UIViewPropertyAnimator *_animator;
  BOOL _isDragInteractive;
  struct CGPoint { double x; double y; } _dragStartPoint;
  BOOL _shouldHideView;
  double _alphaOverride;
  BOOL _isShowingNewPostsIndicatorView;
}

@property (weak, nonatomic) NSObject<IGImmersiveNewPostsIndicatorControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContainerView:(id)view insertingBelowView:(id)view topInset:(double)inset hideView:(BOOL)view;
- (void)_didPan:(id)pan;
- (void)newPostsIndicatorPillViewWasTapped:(id)tapped;
@end

#endif /* IGImmersiveNewPostsIndicatorController_h */
