//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGLiveBroadcastShareToStoryStaticTemplateStickerView_h
#define IGLiveBroadcastShareToStoryStaticTemplateStickerView_h
@import Foundation;

#include "UIView.h"
#include "IGStickerViewType-Protocol.h"

@class IGStoryFacepileView, IGStoryStickerExportModel, NSString, UILabel, UIVisualEffectView;

@interface IGLiveBroadcastShareToStoryStaticTemplateStickerView : UIView<IGStickerViewType> {
  /* instance variables */
  UIVisualEffectView *_blurView;
  IGStoryFacepileView *_facepileView;
  UILabel *_titleLabel;
  UILabel *_subtitleLabel;
}

@property (readonly, nonatomic) IGStoryStickerExportModel *exportModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)newWithMetadata:(id)metadata resourceDirectory:(id)directory userSession:(id)session error:(id *)error;

/* instance methods */
- (id)initWithConfig:(struct IGLiveBroadcastShareToStoryStaticTemplateStickerViewConfig { id x0; id x1; unsigned long long x2; double x3; })config;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (id)stickerView;
- (id)tapModelsForCompositionSize:(struct CGSize { double x0; double x1; })size;
- (BOOL)isDraftSupported;
- (id)metadataForResourceDirectory:(id)directory userSession:(id)session error:(id *)error;
@end

#endif /* IGLiveBroadcastShareToStoryStaticTemplateStickerView_h */
