//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGLiveInteractivityService_h
#define IGLiveInteractivityService_h
@import Foundation;

@class IGUserSession, NSDictionary, NSMutableArray, NSString, PNPandoGraphQLService;
@protocol IGLiveInteractivityServiceDelegate;

@interface IGLiveInteractivityService : NSObject {
  /* instance variables */
  IGUserSession *_userSession;
  PNPandoGraphQLService *_pandoGraphQLService;
  NSString *_broadcastId;
  NSMutableArray *_qaPandoGraphQLTokens;
  NSMutableArray *_badgesPandoGraphQLTokens;
  NSMutableArray *_reactionPandoGraphQLTokens;
  NSMutableArray *_gamesPandoGraphQLTokens;
  NSMutableArray *_joinRequestsPandoGraphQLTokens;
  NSDictionary *_joinRequestStatusLookup;
}

@property (weak, nonatomic) NSObject<IGLiveInteractivityServiceDelegate> *delegate;

/* instance methods */
- (id)initWithBroadcastId:(id)id userSession:(id)session isMultiplePaymentsEnabled:(BOOL)enabled;
- (void)dealloc;
@end

#endif /* IGLiveInteractivityService_h */
