//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGMonetizationBrandedContentSettingsView_h
#define IGMonetizationBrandedContentSettingsView_h
@import Foundation;

#include "UIView.h"

@class IGListAdapter, UICollectionView;

@interface IGMonetizationBrandedContentSettingsView : UIView {
  /* instance variables */
  IGListAdapter *_listAdapter;
  UICollectionView *_collectionView;
}

@property (weak, nonatomic) id delegate;

/* instance methods */
- (id)initWithViewController:(id)controller;
- (void)layoutSubviews;
- (void)setDataSource:(id)source;
- (void)reload;
@end

#endif /* IGMonetizationBrandedContentSettingsView_h */
