//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGNonFeedHScrollCollectionCell_h
#define IGNonFeedHScrollCollectionCell_h
@import Foundation;

#include "UICollectionViewCell.h"
#include "IGNonFeedHScrollCollectionLayout.h"

@class NSArray, UICollectionView;

@interface IGNonFeedHScrollCollectionCell : UICollectionViewCell {
  /* instance variables */
  NSArray *_headerViews;
}

@property (readonly, nonatomic) UICollectionView *collectionView;
@property (readonly, nonatomic) IGNonFeedHScrollCollectionLayout *layout;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)setBackgroundColor:(id)color;
- (void)layoutSubviews;
@end

#endif /* IGNonFeedHScrollCollectionCell_h */
