//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGNuxButton_h
#define IGNuxButton_h
@import Foundation;

#include "IGTapButton.h"

@class NSString;

@interface IGNuxButton : IGTapButton {
  /* instance variables */
  BOOL _expanded;
  double _titleInset;
}

@property (nonatomic) double size;
@property (nonatomic) double maxWidth;
@property (nonatomic) double imageInset;
@property (readonly, nonatomic) BOOL isExpanded;
@property (retain, nonatomic) NSString *title;

/* instance methods */
- (void)removeAllAnimations;
- (void)setImage:(id)image forState:(unsigned long long)state;
- (void)sizeToFit;
@end

#endif /* IGNuxButton_h */
