//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGNUXContactImportStepController_h
#define IGNUXContactImportStepController_h
@import Foundation;

#include "IGNUXFindFriendsStepController.h"
#include "IGContactsFriendsHelper.h"
#include "IGFindFriendsHelperDelegate-Protocol.h"

@class NSString;

@interface IGNUXContactImportStepController : IGNUXFindFriendsStepController<IGFindFriendsHelperDelegate> {
  /* instance variables */
  IGContactsFriendsHelper *_contactsHelper;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContext:(id)context;
- (long long)mode;
- (id)stepName;
- (void)findFriendsControllerDidStartUserListFetch:(id)fetch;
- (void)findFriendsControllerDidTakePrimaryAction:(id)action entryPoint:(long long)point;
- (void)findFriendsController:(id)controller didLoadUsers:(id)users;
- (void)findFriendsHelper:(id)helper didAuthorizeWithDataRequest:(id)request;
- (void)findFriendsHelper:(id)helper didFailToAuthorizeWithMessage:(id)message;
- (void)findFriendsHelperSystemContactsPermissionDenied:(id)denied;
@end

#endif /* IGNUXContactImportStepController_h */
