//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGPayoutHubEditScreenLogging_h
#define IGPayoutHubEditScreenLogging_h
@import Foundation;

#include "FBAnalyticsLogging-Protocol.h"

@class NSString;

@interface IGPayoutHubEditScreenLogging : NSObject {
  /* instance variables */
  NSObject<FBAnalyticsLogging> *_logger;
  long long _productType;
  NSString *_module;
  NSString *_uplSessionId;
}

/* instance methods */
- (id)initWithUserSession:(id)session productType:(long long)type module:(id)module uplSessionId:(id)id;
@end

#endif /* IGPayoutHubEditScreenLogging_h */
