//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGProfileFollowRelationshipViewController_h
#define IGProfileFollowRelationshipViewController_h
@import Foundation;

#include "IGViewController.h"
#include "FBGNVGenericClickMetadataProvider-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"

@class IGFollowController, IGListAdapter, IGUser, IGUserSession, NSString, UICollectionView, UIViewController;

@interface IGProfileFollowRelationshipViewController : IGViewController<IGListAdapterDataSource, FBGNVGenericClickMetadataProvider> {
  /* instance variables */
  IGUser *_user;
  IGFollowController *_followController;
  UIViewController *_viewController;
  IGUserSession *_userSession;
  IGListAdapter *_listAdapter;
  UICollectionView *_collectionView;
  NSString *_fromCommentId;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUser:(id)user followController:(id)controller viewController:(id)controller fromCommentId:(id)id userSession:(id)session;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)appear;
- (struct CGSize { double x0; double x1; })preferredContentSize;
- (BOOL)prefersStatusBarHidden;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (id)analyticsModule;
- (id)contentMetadata;
@end

#endif /* IGProfileFollowRelationshipViewController_h */
