//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGPromoteNewFormBaseViewController_h
#define IGPromoteNewFormBaseViewController_h
@import Foundation;

#include "IGPromoteViewController.h"
#include "IGPromoteLeadGenAdvanceSettingsModel.h"
#include "IGPromoteTitleSubtitleViewModel.h"

@class IGDSHeadlineViewModel, IGListAdapter, IGUserSession, NSMutableArray, NSMutableSet, NSString, UICollectionView;

@interface IGPromoteNewFormBaseViewController : IGPromoteViewController {
  /* instance variables */
  IGUserSession *_userSession;
  UICollectionView *_contentView;
  IGListAdapter *_adapter;
  NSMutableSet *_selectedInfoQuestions;
  NSMutableArray *_customQuestions;
  IGDSHeadlineViewModel *_headlineViewModel;
  IGPromoteTitleSubtitleViewModel *_customQuestionsTitleSubtitleViewModel;
  IGPromoteTitleSubtitleViewModel *_addQuestionViewModel;
  NSMutableArray *_presetQuestionsViewModels;
  NSMutableArray *_allViewModels;
  IGPromoteLeadGenAdvanceSettingsModel *_advanceSettingViewModel;
  NSString *_newFormName;
  BOOL _shouldForceHideSeeAllButton;
}

@property (retain, nonatomic) NSString *entrypoint;

/* instance methods */
- (id)initWithSession:(id)session;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)setUpData;
- (void)setUpViewModels;
- (void)setUpNavigationBar;
- (void)setUpFooterView;
- (void)setUpContentView;
- (void)updateViewModels;
- (void)reloadView;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })contentInset;
- (void)discardForm;
- (unsigned long long)customQuestionCount;
- (id)formName;
- (void)showDiscardCreateFormConfirmationExitActionSheet;
- (BOOL)canCreateForm;
- (void)didTapLeftNavigationBarButton;
- (void)didTapRightNavigationBarButton;
@end

#endif /* IGPromoteNewFormBaseViewController_h */
