//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGQuickSnapDetailsViewController_h
#define IGQuickSnapDetailsViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGAlertHUDHandling-Protocol.h"
#include "IGQuickSnapDetailsViewControllerDelegate-Protocol.h"
#include "UICollectionViewDataSource-Protocol.h"

@class IGImageProgressView, IGMedia, IGTapButton, IGUserSession, NSArray, NSString, NSURL, UICollectionView, UILabel;

@interface IGQuickSnapDetailsViewController : IGViewController<UICollectionViewDataSource> {
  /* instance variables */
  IGMedia *_media;
  NSString *_mediaId;
  NSURL *_mediaImageURL;
  IGUserSession *_userSession;
  NSObject<IGAlertHUDHandling> *_alertHandler;
  IGImageProgressView *_mediaContentImageView;
  UILabel *_dateLabel;
  UILabel *_reactionsTitleLabel;
  UICollectionView *_reactionsCollectionView;
  NSArray *_reactions;
  BOOL _showCameraButton;
  IGTapButton *_cameraPresentationButton;
}

@property (weak, nonatomic) NSObject<IGQuickSnapDetailsViewControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session mediaId:(id)id mediaImageURL:(id)url showCameraButton:(BOOL)button;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)_setupNavigationBar;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredTabBarBehavior;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (void)_configureAudienceTitleLabel:(id)label;
- (void)_configureReactions;
- (void)_didTapToPresentCamera;
- (void)_didTapDismiss;
- (void)_didTapMore;
- (void)_deleteSnap;
- (void)_downloadSnap;
- (void)image:(id)image didFinishSavingWithError:(id)error contextInfo:(void *)info;
@end

#endif /* IGQuickSnapDetailsViewController_h */
