//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGReportingConfirmationViewController_h
#define IGReportingConfirmationViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGCoreTextLinkHandler-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGReportingConfirmationViewModel.h"
#include "IGReportingController.h"

@class IGCoreTextView, IGListAdapter, IGUserSession, NSString, UICollectionView, UIImageView, UILabel;
@protocol IGReportingPageDelegate;

@interface IGReportingConfirmationViewController : IGViewController<IGListAdapterDataSource, IGCoreTextLinkHandler> {
  /* instance variables */
  IGUserSession *_userSession;
  IGReportingController *_reportingController;
  IGReportingConfirmationViewModel *_viewModel;
  UIImageView *_checkmarkImageView;
  UILabel *_subtitleLabel;
  IGCoreTextView *_actionsTitleTextView;
  UICollectionView *_collectionView;
  IGListAdapter *_listAdapter;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL userInteractionEnabled;
@property (weak, nonatomic) NSObject<IGReportingPageDelegate> *delegate;

/* instance methods */
- (id)initWithUserSession:(id)session reportingController:(id)controller performanceListener:(id)listener;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (BOOL)prefersNavigationBarHidden;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (void)reportingConfirmationSectionController:(id)controller didSelectFollowup:(id)followup;
- (void)coreTextView:(id)view didTapOnString:(id)string URL:(id)url;
- (BOOL)isUserInteractionEnabled;
@end

#endif /* IGReportingConfirmationViewController_h */
