//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGRegistrationNUXFXLinkedAccountsViewController_h
#define IGRegistrationNUXFXLinkedAccountsViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGGestureHandler-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGListAdapterDelegate-Protocol.h"

@class IGBasicListViewController, NSArray, NSString;

@interface IGRegistrationNUXFXLinkedAccountsViewController : IGViewController<IGListAdapterDataSource, IGListAdapterDelegate, IGGestureHandler> {
  /* instance variables */
  NSArray *_accounts;
  IGBasicListViewController *_accountsListViewController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithAccounts:(id)accounts userSession:(id)session;
- (void)viewDidLoad;
- (BOOL)canRespondToGesture:(id)gesture;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (void)listAdapter:(id)adapter willDisplayObject:(id)object atIndex:(long long)index;
- (void)listAdapter:(id)adapter didEndDisplayingObject:(id)object atIndex:(long long)index;
@end

#endif /* IGRegistrationNUXFXLinkedAccountsViewController_h */
