//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGRegistrationFriendsListViewController_h
#define IGRegistrationFriendsListViewController_h
@import Foundation;

#include "UIViewController.h"
#include "IGUserListViewController.h"
#include "NSObject-Protocol.h"

@class IGTextButton, NSString, UIActivityIndicatorView, UILabel;
@protocol IGRegistrationFriendsListViewControllerDelegate;

@interface IGRegistrationFriendsListViewController : UIViewController<NSObject> {
  /* instance variables */
  long long _findFriendsMode;
  NSString *_step;
  IGUserListViewController *_userListViewController;
}

@property (retain, nonatomic) IGTextButton *followAllButton;
@property (retain, nonatomic) UIActivityIndicatorView *spinner;
@property (weak, nonatomic) NSObject<IGRegistrationFriendsListViewControllerDelegate> *delegate;
@property (readonly, nonatomic) UILabel *titleLabel;
@property (readonly, nonatomic) UILabel *subtitleLabel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithShouldShowFollowAllButton:(BOOL)button userSession:(id)session step:(id)step;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)fetchListWithRequest:(id)request;
- (void)userListViewController:(id)controller didLoadUsers:(id)users;
- (void)userListViewController:(id)controller didFailWithError:(id)error;
- (void)userListViewController:(id)controller didFollowUser:(id)user atIndex:(unsigned long long)index;
- (void)userListViewController:(id)controller didUnfollowUser:(id)user atIndex:(unsigned long long)index;
- (void)userListViewController:(id)controller didFollowAllUsersCount:(long long)count;
- (void)userListViewControllerDidFailToFollowAllUsers:(id)users;
- (void)userListViewController:(id)controller willDisplayUser:(id)user atIndex:(long long)index;
- (void)userListViewController:(id)controller followAllAttemptedWithUserIds:(id)ids;
- (void)_followAllButtonTapped:(id)tapped;
@end

#endif /* IGRegistrationFriendsListViewController_h */
