//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGShoppingMerchantLogger_h
#define IGShoppingMerchantLogger_h
@import Foundation;

@class IGMedia, IGSessionTracker, IGShoppingAdMetadata, IGShoppingHomeRankingInfo, IGShoppingNavigationAnalyticsContext, IGShoppingProductCollectionProperties, IGUserSession;

@interface IGShoppingMerchantLogger : NSObject {
  /* instance variables */
  IGUserSession *_userSession;
  IGShoppingProductCollectionProperties *_productCollectionInfo;
  IGMedia *_media;
  IGShoppingHomeRankingInfo *_rankingInfo;
}

@property (readonly, nonatomic) IGSessionTracker *shoppingSessionTracker;
@property (readonly, nonatomic) IGShoppingAdMetadata *adMetadata;
@property (readonly, nonatomic) IGShoppingNavigationAnalyticsContext *navigationInfo;

/* instance methods */
- (id)initWithUserSession:(id)session navigationInfo:(id)info media:(id)media productCollectionInfo:(id)info shoppingSessionTracker:(id)tracker adMetadata:(id)metadata rankingInfo:(id)info;
@end

#endif /* IGShoppingMerchantLogger_h */
