//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGShoppingMediaGridPlaceholderItem_h
#define IGShoppingMediaGridPlaceholderItem_h
@import Foundation;

#include "FBIvarBasedEqualityObject.h"
#include "IGShimmeringGridModel.h"
#include "IGShoppingMerchantCarouselPlaceholderViewModel.h"

@interface IGShoppingMediaGridPlaceholderItem : FBIvarBasedEqualityObject {
  /* instance variables */
  unsigned long long _subtype;
  IGShimmeringGridModel *_shimmeringGrid_model;
  IGShoppingMerchantCarouselPlaceholderViewModel *_merchantShopPreviewCarouselPlaceholder_carouselViewModel;
}

/* class methods */
+ (id)merchantShopPreviewCarouselPlaceholderWithCarouselViewModel:(id)model;
+ (id)shimmeringGridWithModel:(id)model;

/* instance methods */
@end

#endif /* IGShoppingMediaGridPlaceholderItem_h */
