//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGShoppingMerchantCardLogger_h
#define IGShoppingMerchantCardLogger_h
@import Foundation;

#include "NSObject-Protocol.h"

@class IGShoppingProductCollectionProperties, IGUserSession, NSString;

@interface IGShoppingMerchantCardLogger : NSObject<NSObject> {
  /* instance variables */
  IGUserSession *_userSession;
  IGShoppingProductCollectionProperties *_productCollectionInfo;
  NSString *_shoppingSessionId;
}

@property (readonly, copy, nonatomic) NSString *analyticsModule;
@property (readonly, copy, nonatomic) NSString *profileShopEntryPoint;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session analyticsModule:(id)module profileShopEntryPoint:(id)point productCollectionInfo:(id)info shoppingSessionTracker:(id)tracker;
- (void)logImpressionForMerchantCard:(id)card atPosition:(long long)position;
- (void)logTapForMerchantCard:(id)card atPosition:(long long)position;
@end

#endif /* IGShoppingMerchantCardLogger_h */
