//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSignalsAppleCoreMLPredictor_h
#define IGSignalsAppleCoreMLPredictor_h
@import Foundation;

#include "IGSignalsMLModelSource.h"
#include "IGSignalsPredictor-Protocol.h"
#include "IGSignalsPredictorMetadata.h"

@class MLModel, NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface IGSignalsAppleCoreMLPredictor : NSObject<IGSignalsPredictor> {
  /* instance variables */
  IGSignalsMLModelSource *_modelSource;
  NSString *_outputKey;
  NSDictionary *_featuresRemap;
  long long _state;
  MLModel *_appleCoreMLModel;
  NSObject<OS_dispatch_queue> *_workQueue;
}

@property (readonly, nonatomic) IGSignalsPredictorMetadata *metadata;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithModelSource:(id)source outputKey:(id)key featuresRemap:(id)remap;
- (void)prepare;
- (void)predictionForExample:(id)example completionBlock:(id /* block */)block;
@end

#endif /* IGSignalsAppleCoreMLPredictor_h */
