//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSSOAccountPickerSectionController_h
#define IGSSOAccountPickerSectionController_h
@import Foundation;

#include "IGListSectionController.h"

@class IGLoginAccount;
@protocol IGSSOAccountPickerSectionControllerDelegate;

@interface IGSSOAccountPickerSectionController : IGListSectionController {
  /* instance variables */
  IGLoginAccount *_account;
  NSObject<IGSSOAccountPickerSectionControllerDelegate> *_delegate;
}

/* instance methods */
- (id)initWithDelegate:(id)delegate;
- (long long)numberOfItems;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)index;
- (id)cellForItemAtIndex:(long long)index;
- (void)didUpdateToObject:(id)object;
- (void)didSelectItemAtIndex:(long long)index;
- (void)didHighlightItemAtIndex:(long long)index;
- (void)didUnhighlightItemAtIndex:(long long)index;
@end

#endif /* IGSSOAccountPickerSectionController_h */
