//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGStoryAdBaseView_h
#define IGStoryAdBaseView_h
@import Foundation;

#include "UIView.h"
#include "IGStoryPlayerMediaViewType-Protocol.h"
#include "IGVPVDImpressionHelper.h"

@class NSString;
@protocol IGStoryItemType><IGUnitItemInformationProviding, UIView<IGStoryPlayerMediaViewType;

@interface IGStoryAdBaseView : UIView<IGStoryPlayerMediaViewType>

@property (readonly, nonatomic) UIView<IGStoryPlayerMediaViewType> *mainMediaView;
@property (readonly, nonatomic) NSObject<IGStoryItemType><IGUnitItemInformationProviding> *item;
@property (retain, nonatomic) IGVPVDImpressionHelper *vpvdImpressionHelper;
@property (retain, nonatomic) IGVPVDImpressionHelper *merlinVpvdImpressionHelper;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame mediaView:(id)view;
- (void)layoutSubviews;
- (BOOL)requireMainViewAddedAsSubview;
- (void)configureWithItem:(id)item delegate:(id)delegate videoLogger:(id)logger videoLoggingConfig:(id)config userSession:(id)session module:(id)module;
- (void)retryLoadItem:(id)item currentLoadingError:(id)error;
- (void)play;
- (void)pauseWithReason:(long long)reason;
- (void)stopWithReason:(long long)reason pauseReasonDebugString:(id)string;
- (BOOL)isPlaying;
- (void)seekToBeginning;
- (void)seekToBeginningAndPause;
- (void)seekToTime:(double)time;
- (void)prepareForReuse;
- (void)setAudioEnabled:(BOOL)enabled reason:(long long)reason;
- (struct CGSize { double x0; double x1; })mediaSize;
- (double)mediaCurrentTime;
- (double)mediaCurrentFrameTime;
- (double)cellPlayTime;
- (BOOL)isViewFinishedLoading;
- (BOOL)isShowingContent;
@end

#endif /* IGStoryAdBaseView_h */
