//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGStoryCanvasCardsFormatViewController_h
#define IGStoryCanvasCardsFormatViewController_h
@import Foundation;

#include "UIViewController.h"
#include "IGCanvasControlsOverlayViewToolbarDelegate-Protocol.h"
#include "IGStoryCanvasCardCreationView.h"
#include "IGStoryCanvasFormatGradientHandler-Protocol.h"
#include "IGStoryCanvasToolbarConfig.h"

@class IGImageView, IGPerformanceNavigationLogger, IGUser, IGUserSession, METAStickerContainerView, NSArray, NSString;
@protocol IGStoryCanvasCompositionProvider, IGStoryCanvasFormatViewControllerDelegate, UIViewController<IGStoryPostCaptureEditingViewControllerType;

@interface IGStoryCanvasCardsFormatViewController : UIViewController<IGCanvasControlsOverlayViewToolbarDelegate, IGStoryCanvasFormatGradientHandler> {
  /* instance variables */
  IGUserSession *_userSession;
  NSArray *_models;
  struct UIEdgeInsets { double top; double left; double bottom; double right; } _contentInset;
  unsigned long long _currentIndex;
  IGPerformanceNavigationLogger *_performanceLogger;
  IGStoryCanvasCardCreationView *_creationView;
  IGImageView *_backgroundImageView;
  IGUser *_selectedUser;
  UIViewController<IGStoryPostCaptureEditingViewControllerType> *_postcaptureViewController;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) METAStickerContainerView *stickerContainerView;
@property (weak, nonatomic) NSObject<IGStoryCanvasFormatViewControllerDelegate> *delegate;
@property (weak, nonatomic) NSObject<IGStoryCanvasCompositionProvider> *compositionProvider;
@property (readonly, nonatomic) IGStoryCanvasToolbarConfig *toolbarConfig;
@property (readonly, nonatomic) long long presentationAnimationStyle;

/* instance methods */
- (id)initWithUserSession:(id)session cardModels:(id)models contentInset:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })inset performanceLogger:(id)logger;
- (void)viewWillAppear:(BOOL)appear;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)appear;
- (void)viewWillDisappear:(BOOL)disappear;
- (void)viewDidLayoutSubviews;
- (void)handleCapture;
- (void)restoreCompositionState;
- (id)createModeSubformatForLogging;
- (void)canvasControlsOverlayViewDidTapDiceButton:(id)button;
- (void)canvasControlsOverlayViewDidTapStickerButton:(id)button;
- (void)canvasControlsOverlayViewDidTapSeeAllButton:(id)button;
- (void)canvasControlsOverlayViewDidTapMusicButton:(id)button;
- (void)canvasCardCreationViewDidAttemptBeginEditing:(id)editing;
- (void)canvasCardCreationViewController:(id)controller didSelectUser:(id)user;
- (void)canvasCardCreationViewController:(id)controller willFinishEditingWithDismissalSource:(long long)source;
- (void)_presentCreationVC;
- (void)didTapAddButtonInMultiEditCompositionThumbnailTray:(id)tray;
- (void)cardsCompositionsSelectionViewController:(id)controller didLoadWithItemCount:(unsigned long long)count;
- (void)cardsCompositionsSelectionViewController:(id)controller didSelectFeedItem:(id)item atIndex:(long long)index;
- (void)cardsCompositionsSelectionViewController:(id)controller didDeselectFeedItem:(id)item atIndex:(long long)index;
- (void)handleGradientChange:(id)change;
@end

#endif /* IGStoryCanvasCardsFormatViewController_h */
