//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialCaptureControlsOverlayView_h
#define IGSundialCaptureControlsOverlayView_h
@import Foundation;

#include "IGPassthroughView.h"
#include "IGCameraToolsMenu.h"
#include "IGCameraToolsMenuMusicButton.h"
#include "IGCameraToolsMenuPickerButton.h"
#include "IGCameraToolsMenuTapButton.h"
#include "IGCameraToolsMenuToggleButton.h"
#include "IGEDRViewType-Protocol.h"
#include "IGStoryCameraHeaderPill.h"
#include "IGSundialRightChevronWithTextButton.h"
#include "_TtC22IGCameraUtilityToolbar35IGCameraUtilityToolbarContainerView.h"

@class IGSundialReactiveAudioInputModelDataSource, IGUserSession, NSArray, NSSet, NSString, UIControl;
@protocol IGSundialCaptureControlOverlayDataSource, IGSundialCaptureControlsOverlayViewDelegate;

@interface IGSundialCaptureControlsOverlayView : IGPassthroughView<IGEDRViewType> {
  /* instance variables */
  IGUserSession *_userSession;
  IGCameraToolsMenuPickerButton *_gridVideoLayoutButton;
  IGCameraToolsMenuToggleButton *_cropModeVideoLayoutButton;
  NSSet *_toolsAboveTheFold;
  BOOL _edr;
  BOOL _isGestureControlSupported;
  BOOL _musicButtonShouldAppearWashedOut;
  BOOL _reactiveAudioInputHidden;
  IGCameraToolsMenuPickerButton *_maxDurationPicker;
  IGCameraToolsMenuTapButton *_editClipButton;
  IGCameraToolsMenuTapButton *_addYoursButton;
  IGCameraToolsMenuPickerButton *_speedPicker;
  IGCameraToolsMenuPickerButton *_remixLayoutPicker;
  IGCameraToolsMenuToggleButton *_timerButton;
  IGCameraToolsMenuTapButton *_flashButton;
  IGCameraToolsMenuToggleButton *_effectsButton;
  IGCameraToolsMenuToggleButton *_greenScreenButton;
  IGCameraToolsMenuToggleButton *_ghostButton;
  IGCameraToolsMenuToggleButton *_dualButton;
  IGCameraToolsMenuToggleButton *_smartCaptureButton;
  IGStoryCameraHeaderPill *_suggestedPill;
  IGCameraToolsMenuToggleButton *_videoLayoutButton;
  UIControl *_deleteAllCapturesButton;
  NSArray *_recordingSpeedsV2;
  IGSundialReactiveAudioInputModelDataSource *_reactiveAudioInputModelDataSource;
  _TtC22IGCameraUtilityToolbar35IGCameraUtilityToolbarContainerView *_utilityToolbarContainerView;
  struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _captureButtonRegion;
  struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _cameraContentRegion;
}

@property (readonly, nonatomic) IGCameraToolsMenu *toolsMenu;
@property (readonly, nonatomic) IGCameraToolsMenuMusicButton *musicButton;
@property (readonly, nonatomic) IGSundialRightChevronWithTextButton *nextButton;
@property (weak, nonatomic) NSObject<IGSundialCaptureControlsOverlayViewDelegate> *delegate;
@property (weak, nonatomic) NSObject<IGSundialCaptureControlOverlayDataSource> *dataSource;
@property (readonly, nonatomic) BOOL wantsEDR;
@property (nonatomic) BOOL musicButtonHidden;
@property (nonatomic) BOOL addYoursButtonHidden;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithoutToolsUserSession:(id)session;
- (id)initWithUserSession:(id)session remixedVideo:(id)video hasPrepopulatedPromptSticker:(BOOL)sticker;
- (void)layoutSubviews;
- (void)_toolButtonTapped:(id)tapped;
- (void)hideSuggestedPill;
- (void)_didTapVideoLayoutButton;
- (void)_didTapVideoLayoutCropModeButton:(id)button;
- (void)_didTapDualButton;
- (void)_didTapSmartCaptureButton;
- (void)_didTapGreenScreenButton;
- (void)setEDR:(BOOL)edr;
- (void)pickerButtonDidExpandPicker:(id)picker;
- (void)pickerButtonDidCollapsePicker:(id)picker;
- (void)pickerButton:(id)button didSelectItemAtIndex:(unsigned long long)index;
- (void)toolsMenu:(id)menu didUpdateExpandedState:(BOOL)state;
- (void)toolsMenu:(id)menu willSelectTool:(id)tool;
- (void)toolsMenu:(id)menu didSelectTool:(id)tool;
@end

#endif /* IGSundialCaptureControlsOverlayView_h */
