//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialAdsMultiAdsSingleItemUserAttributionView_h
#define IGSundialAdsMultiAdsSingleItemUserAttributionView_h
@import Foundation;

#include "UIView.h"
#include "IGProfilePhotoViewDelegate-Protocol.h"

@class IGPillButton, IGProfilePhotoView, NSString, UIImageView, UILabel;
@protocol IGSundialAdsMultiAdsUserViewTypeDelegate;

@interface IGSundialAdsMultiAdsSingleItemUserAttributionView : UIView<IGProfilePhotoViewDelegate> {
  /* instance variables */
  UILabel *_usernameLabel;
  IGPillButton *_usernamePill;
  IGProfilePhotoView *_profilePhotoView;
  long long _layoutType;
  UIImageView *_verifiedBadgeImageView;
  long long _subtleCtaType;
  BOOL _shouldShowUsername;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) NSObject<IGSundialAdsMultiAdsUserViewTypeDelegate> *delegate;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)profilePhotoViewDidTapProfilePicture:(id)picture;
- (void)profilePhotoViewDidLongPressProfilePicture:(id)picture;
- (void)profilePhotoViewDidTapEmptyStoryBadge:(id)badge;
- (void)profilePhotoViewDidTapBirthdayBadge:(id)badge;
- (void)_didTapUsernameLabel:(id)label;
- (void)configureUserViewWithProfileURL:(id)url username:(id)username isVerified:(BOOL)verified shouldShowUsername:(BOOL)username ringViewSpecFactory:(id)factory subtleCtaType:(long long)type layoutType:(long long)type;
- (void)setAccessibilityIdentifier:(id)identifier;
@end

#endif /* IGSundialAdsMultiAdsSingleItemUserAttributionView_h */
