//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGSundialVoiceEffectsCell_h
#define IGSundialVoiceEffectsCell_h
@import Foundation;

#include "IGBouncyCollectionViewCell.h"
#include "IGSundialVoiceEffectsIconView.h"

@class UILabel;

@interface IGSundialVoiceEffectsCell : IGBouncyCollectionViewCell {
  /* instance variables */
  UILabel *_title;
  IGSundialVoiceEffectsIconView *_effectIcon;
}

@property (nonatomic) unsigned long long effectType;
@property (nonatomic) BOOL disabled;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (BOOL)isDisabled;
@end

#endif /* IGSundialVoiceEffectsCell_h */
