//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGTVSeenStateStore_h
#define IGTVSeenStateStore_h
@import Foundation;

#include "IGAPIClient-Protocol.h"

@class NSMutableDictionary, NSMutableSet;
@protocol IGTVSeenStateStoreAnnouncer;

@interface IGTVSeenStateStore : NSObject {
  /* instance variables */
  NSObject<IGAPIClient> *_networker;
  NSObject<IGTVSeenStateStoreAnnouncer> *_announcer;
  NSMutableDictionary *_maxDurations;
  NSMutableDictionary *_queuedImpressions;
  NSMutableDictionary *_queuedAutoplayImpressions;
  NSMutableSet *_queuedGridImpressions;
  long long _serverRequestToken;
}

/* instance methods */
- (id)initWithNetworker:(id)networker;
- (void)addListener:(id)listener;
- (void)removeListener:(id)listener;
- (void)_onApplicationWillResignActive:(id)active;
@end

#endif /* IGTVSeenStateStore_h */
