//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGUpdatesHubCalendarSectionController_h
#define IGUpdatesHubCalendarSectionController_h
@import Foundation;

#include "IGListSectionController.h"
#include "IGArchiveStoryPresenter.h"
#include "IGCalendarViewDataSource.h"
#include "IGListDisplayDelegate-Protocol.h"
#include "IGMediaDeletedListener-Protocol.h"
#include "IGMediaShellGalleryController.h"
#include "IGStoryDataControllerStoryItemListener-Protocol.h"
#include "IGStorySharePostListener-Protocol.h"
#include "IGStoryUploadListener-Protocol.h"

@class IGListAdapter, IGUserSession, NSArray, NSDate, NSIndexPath, NSMutableDictionary, NSMutableSet, NSString;

@interface IGUpdatesHubCalendarSectionController : IGListSectionController<IGStoryDataControllerStoryItemListener, IGMediaDeletedListener, IGStorySharePostListener, IGStoryUploadListener, IGListDisplayDelegate> {
  /* instance variables */
  IGUserSession *_userSession;
  NSString *_analyticsModule;
  IGCalendarViewDataSource *_calendarViewDataSource;
  IGMediaShellGalleryController *_shellController;
  IGListAdapter *_listAdapter;
  NSMutableDictionary *_reelDates;
  NSString *_launchReelPKAfterFetch;
  NSArray *_reelPksInViewer;
  NSDate *_viewerFocusedReelDate;
  NSMutableDictionary *_mediaIdToReelId;
  NSMutableSet *_reelPksWithDeletedMedia;
  NSMutableSet *_deletedMediaIds;
  NSIndexPath *_tappedDayCellIndexPath;
  BOOL _initialScroll;
  IGArchiveStoryPresenter *_archiveStoryPresenter;
  NSDate *_archiveEntryDate;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserSession:(id)session;
- (void)dealloc;
- (long long)numberOfItems;
- (id)cellForItemAtIndex:(long long)index;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)index;
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller;
- (void)listAdapter:(id)adapter willDisplaySectionController:(id)controller cell:(id)cell atIndex:(long long)index;
- (void)listAdapter:(id)adapter didEndDisplayingSectionController:(id)controller cell:(id)cell atIndex:(long long)index;
- (void)dayCellWasTapped:(id)tapped;
- (id)reuseIdentifierForModel:(id)model;
- (struct CGSize { double x0; double x1; })sizeForMonthHeader;
- (struct CGSize { double x0; double x1; })sizeForDayHeader;
- (struct CGSize { double x0; double x1; })sizeForSpacer;
- (struct CGSize { double x0; double x1; })sizeForDay;
- (void)bindMonthHeaderCell:(id)cell toModel:(id)model;
- (void)bindDayHeaderCell:(id)cell toModel:(id)model;
- (void)bindSpacerCell:(id)cell toModel:(id)model;
- (void)bindDayCell:(id)cell toModel:(id)model;
- (void)storyDataController:(id)controller didUpdateReel:(id)reel refreshType:(long long)type updateDuration:(double)duration;
- (void)storyDataController:(id)controller fetchItemsDidFailForReelPK:(id)pk error:(id)error refreshType:(long long)type updateDuration:(double)duration;
- (void)storyDataController:(id)controller didReturnNoStoryItemResultsForReelPK:(id)pk refreshType:(long long)type updateDuration:(double)duration;
- (void)mediaShellControllerDidInitiallyLoadGallery:(id)gallery;
- (void)mediaShellControllerDidUpdateGallery:(id)gallery;
- (void)mediaShellController:(id)controller loadingGalleryDidFailWithError:(id)error;
- (void)archiveStoryPresenter:(id)presenter didNavigateToStoryItem:(id)item;
- (void)archiveStoryPresenter:(id)presenter didFinishStoryViewer:(id)viewer;
- (void)archiveStoryPresenter:(id)presenter didFocusonReelWithPK:(id)pk forStoryViewer:(id)viewer;
- (void)archiveStoryPresenter:(id)presenter didPresentStoryItem:(id)item;
- (void)didDismissArchiveStoryPresenter:(id)presenter;
- (id)dismissingToViewForArchiveStoryPresenter:(id)presenter;
- (void)archiveStoryPresenter:(id)presenter didTapViewDayForStoryViewer:(id)viewer;
- (void)mediaItemDeleted:(id)deleted storyReelPK:(id)pk;
- (void)storyItemPosted:(id)posted videoFileURL:(id)url shareType:(long long)type mediaData:(id)data postId:(id)id postShareId:(id)id reelOwner:(id)owner reelPk:(id)pk;
- (void)storyUploadStartedWithCompositions:(id)compositions entryPoint:(long long)point;
- (void)storyUploadStartedWithReelOwner:(id)owner reelPK:(id)pk compositionId:(id)id shareType:(long long)type;
- (void)storyDidBeginUpload:(id)upload;
- (void)storyUpload:(id)upload removedFromReelOwner:(id)owner reelPK:(id)pk;
- (id)_storyGalleryConfiguration;
@end

#endif /* IGUpdatesHubCalendarSectionController_h */
