//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGURPMediaInteractivityExtensionBuilder_h
#define IGURPMediaInteractivityExtensionBuilder_h
@import Foundation;

#include "URPMediaContainerDependencyProviding-Protocol.h"

@class IGUserSession;

@interface IGURPMediaInteractivityExtensionBuilder : NSObject {
  /* instance variables */
  IGUserSession *_userSession;
  NSObject<URPMediaContainerDependencyProviding> *_dependencyProvider;
}

/* instance methods */
- (id)initWithUserSession:(id)session navigationController:(id)controller;
@end

#endif /* IGURPMediaInteractivityExtensionBuilder_h */
