//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGUsertagEditViewController_h
#define IGUsertagEditViewController_h
@import Foundation;

#include "IGViewController.h"
#include "IGAlertHUDHandling-Protocol.h"
#include "IGFeedNetworkSourceDelegate-Protocol.h"
#include "IGFeedStarterKit.h"
#include "IGLabelSectionControllerDelegate-Protocol.h"
#include "IGListAdapterDataSource-Protocol.h"
#include "IGMediaThumbnailSectionControllerSelectionDelegate-Protocol.h"
#include "IGScrollViewListener-Protocol.h"
#include "IGTitleAndActionSectionControllerDelegate-Protocol.h"
#include "IGTitleAndToggleCellDelegate-Protocol.h"
#include "UICollectionViewDelegate-Protocol.h"
#include "_TtC26IGUserTagEditLoggingHelper30IGBloksTagSettingLoggingHelper.h"

@class IGBottomActionBar, IGBottomActionBarButton, IGFeedNetworkSource, IGLabelItemViewModel, IGTitleAndActionItemViewModel, IGTitleAndToggleViewModel, IGUserSession, NSMutableSet, NSString, UIBarButtonItem;
@protocol IGUsertagEditViewControllerDelegate;

@interface IGUsertagEditViewController : IGViewController<UICollectionViewDelegate, IGFeedNetworkSourceDelegate, IGScrollViewListener, IGLabelSectionControllerDelegate, IGListAdapterDataSource, IGMediaThumbnailSectionControllerSelectionDelegate, IGTitleAndActionSectionControllerDelegate, IGTitleAndToggleCellDelegate> {
  /* instance variables */
  IGFeedStarterKit *_feed;
  IGFeedNetworkSource *_feedNetworkSource;
  UIBarButtonItem *_hideButton;
  UIBarButtonItem *_editButton;
  UIBarButtonItem *_editCancelButton;
  UIBarButtonItem *_doneButton;
  IGUserSession *_session;
  NSMutableSet *_workingFeedItems;
  BOOL _isEditing;
  IGBottomActionBar *_bottomActionBar;
  IGBottomActionBarButton *_addActionButton;
  IGBottomActionBarButton *_hideActionButton;
  IGBottomActionBarButton *_removeActionButton;
  BOOL _useDoneButton;
  long long _persistedAddToProfilePolicy;
  long long _selectedAddToProfilePolicy;
  BOOL _pendingTaggedPostsSettingsFetched;
  long long _viewType;
  IGTitleAndToggleViewModel *_manuallyApproveTagsRowViewModel;
  long long _pendingTagsCount;
  IGLabelItemViewModel *_pendingTagsRowViewModel;
  IGTitleAndActionItemViewModel *_taggedPostsSectionHeaderViewModel;
  NSObject<IGAlertHUDHandling> *_alertHandler;
  NSObject<IGUsertagEditViewControllerDelegate> *_delegate;
  _TtC26IGUserTagEditLoggingHelper30IGBloksTagSettingLoggingHelper *_tagSettingsLoggingHelper;
  NSString *_tagSettingsLoggingEntrypoint;
  BOOL _shouldLogEnterTaggedPostsScreen;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithSession:(id)session useDoneButton:(BOOL)button editViewType:(long long)type tagSettingsLoggingEntrypoint:(id)entrypoint;
- (void)viewDidLoad;
- (long long)preferredTabBarBehavior;
- (void)feedNetworkSource:(id)source didReceiveFeedResponse:(id)response forRequestConfig:(id)config;
- (void)feedNetworkSource:(id)source didFinishLoadingWithConfig:(id)config success:(BOOL)success error:(id)error httpResponse:(id)response;
- (void)feedNetworkSource:(id)source didChangeToObjects:(id)objects;
- (void)feedNetworkSource:(id)source didStartLoadingWithConfig:(id)config;
- (void)feedNetworkSource:(id)source didCancelRequestForRequestConfig:(id)config;
- (void)scrollViewWillScrollNearBottom:(id)bottom;
- (id)objectsForListAdapter:(id)adapter;
- (id)listAdapter:(id)adapter sectionControllerForObject:(id)object;
- (id)emptyViewForListAdapter:(id)adapter;
- (void)didSelectLabelSectionController:(id)controller;
- (id)accessibilityLabelForViewModel:(id)model;
- (id)accessibilityIdentifierForViewModel:(id)model;
- (void)titleAndToggleCell:(id)cell didSwitchValueTo:(BOOL)to;
- (void)titleAndToggleCell:(id)cell didTapOnString:(id)string URL:(id)url;
- (void)titleAndActionSectionController:(id)controller didSelectActionForViewModel:(id)model;
- (void)didSelectFeedItem:(id)item usingForceTouch:(BOOL)touch;
- (void)didTapSelectionOverlayWithFeedItem:(id)item;
- (void)usertagEditViewControllerDidPerformAction:(id)action;
- (void)_onAddTapped;
- (void)_onHideTapped;
- (void)_onRemoveTapped;
- (void)_doneButtonTapped;
- (void)_toggleEditMode;
- (void)_fetchUsertagReviewSettingsAndPendingPostCount;
@end

#endif /* IGUsertagEditViewController_h */
