//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGVideoCallFooterView_h
#define IGVideoCallFooterView_h
@import Foundation;

#include "UIView.h"
#include "NSObject-Protocol.h"

@class IGLabel, IGTapButton, IGTooltipView, IGUserSession, MPVolumeView, NSString, UIView;
@protocol IGVideoCallCaptureControlsViewDelegate, IGVideoCallFooterViewDelegate;

@interface IGVideoCallFooterView : UIView<NSObject> {
  /* instance variables */
  IGTooltipView *_nuxView;
  UIView *_buttonsStackView;
  IGTapButton *_mediaPickerButton;
  IGTapButton *_reactionButton;
  IGTapButton *_settingsButton;
  IGLabel *_e2eeCowatchDisclaimerLabel;
  IGTapButton *_videoButton;
  IGTapButton *_audioButton;
  IGTapButton *_audioRouteButton;
  IGTapButton *_speakerButton;
  IGTapButton *_switchCameraButton;
  BOOL _rearCameraEnabled;
  IGTapButton *_peopleButton;
  IGTapButton *_closeButton;
  BOOL _audioRouteSelectionEnabled;
  BOOL _isBluetoothConnected;
  BOOL _isEndCallButtonAtFooter;
  MPVolumeView *_mpVolumeView;
  IGUserSession *_userSession;
}

@property (weak, nonatomic) NSObject<IGVideoCallFooterViewDelegate> *delegate;
@property (readonly, weak, nonatomic) NSObject<IGVideoCallCaptureControlsViewDelegate> *captureControlsViewDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMediaPickerEnabled:(BOOL)enabled reactionButtonEnabled:(BOOL)enabled callType:(long long)type videoButtonInitialStateOff:(BOOL)off audioRouteSelectionEnabled:(BOOL)enabled isBluetoothConnected:(BOOL)connected isEndCallButtonAtFooter:(BOOL)footer userSession:(id)session captureControlsViewDelegate:(id)delegate delegate:(id)delegate;
- (BOOL)pointInside:(struct CGPoint { double x0; double x1; })inside withEvent:(id)event;
- (void)layoutSubviews;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)_mediaPickerButtonDidTap:(id)tap;
- (void)_peopleButtonDidTap:(id)tap;
- (void)_videoCallSettingsButtonDidTap:(id)tap;
- (void)_switchCameraButtonTapped:(id)tapped;
- (void)_videoButtonTapped:(id)tapped;
- (void)_audioButtonTapped:(id)tapped;
- (void)_speakerButtonTapped:(id)tapped;
- (void)_audioRouteButtonTapped:(id)tapped;
- (void)_closeButtonTapped:(id)tapped;
- (void)_reactionButtonDidTap:(id)tap;
- (void)updateAudioMutedState:(BOOL)state;
- (void)toggleCallControls:(BOOL)controls;
@end

#endif /* IGVideoCallFooterView_h */
