//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGVideoCallProfileImageContainerView_h
#define IGVideoCallProfileImageContainerView_h
@import Foundation;

#include "IGPassthroughView.h"

@class IGProfilePhotoView, IGStackedProfilePicture;

@interface IGVideoCallProfileImageContainerView : IGPassthroughView {
  /* instance variables */
  IGProfilePhotoView *_profileImageView;
  IGStackedProfilePicture *_stackedParticipantsView;
}

/* instance methods */
- (id)initWithUserProfileImages:(id)images ringViewSpecFactory:(id)factory module:(id)module;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
@end

#endif /* IGVideoCallProfileImageContainerView_h */
