//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef KFMOSDataController_h
#define KFMOSDataController_h
@import Foundation;

#include "KFDataControllerProtocol-Protocol.h"

@class BKContext, NSData, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface KFMOSDataController : NSObject<KFDataControllerProtocol> {
  /* instance variables */
  NSURL *_remoteURL;
  BKContext *_bkContext;
  NSData *_keyframesData;
  struct mutex { struct _opaque_pthread_mutex_t { long long __sig; char x[56] __opaque; } __m_; } _dataMutex;
  NSObject<OS_dispatch_queue> *_controllerQueue;
}

@property (readonly, nonatomic) NSData *data;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)newWithRemoteURL:(id)url bkContext:(id)context;

/* instance methods */
- (id)initWithRemoteURL:(id)url bkContext:(id)context;
- (void)prefetchDataWithCompletionQueue:(id)queue success:(id /* block */)success failure:(id /* block */)failure;
- (void)fetchDataWithCompletionQueue:(id)queue success:(id /* block */)success failure:(id /* block */)failure;
- (void)_fetchDataWithCompletionQueue:(id)queue downloadOptions:(struct { id x0; id x1; id x2; long long x3; unsigned long long x4; BOOL x5; BOOL x6; unsigned long long x7; unsigned long long x8; BOOL x9; unsigned long long x10; id x11; struct CGSize { double x0; double x1; } x12; struct CGSize { double x0; double x1; } x13; unsigned long long x14; id x15; id x16; BOOL x17; })options success:(id /* block */)success failure:(id /* block */)failure;
@end

#endif /* KFMOSDataController_h */
