//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef OCMComponentDefaultVideoCapture_h
#define OCMComponentDefaultVideoCapture_h
@import Foundation;

#include "OCMComponentVideoCaptureProtocol-Protocol.h"
#include "OCMControllerProtocol-Protocol.h"

@class NSString;

@interface OCMComponentDefaultVideoCapture : NSObject<OCMComponentVideoCaptureProtocol> {
  /* instance variables */
  NSObject<OCMControllerProtocol> *_context;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)componentID;
- (id)dependentComponentIDs;
- (long long)supportedControllerStates;
- (void)didAttachWithContext:(id)context;
- (void)willDetachWithContext:(id)context;
- (void)startRecordingWithCompletion:(id /* block */)completion;
- (void)cancelRecordingIfAny;
- (void)stopRecordingWithCompletion:(id /* block */)completion callbackQueue:(id)queue;
@end

#endif /* OCMComponentDefaultVideoCapture_h */
