//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef RCTBridgeModule_Protocol_h
#define RCTBridgeModule_Protocol_h
@import Foundation;

@protocol RCTBridgeModule <NSObject>

@optional
@property (weak, nonatomic) RCTModuleRegistry *moduleRegistry;
@optional
@property (weak, nonatomic) RCTViewRegistry *viewRegistry_DEPRECATED;
@optional
@property (weak, nonatomic) RCTBundleManager *bundleManager;
@optional
@property (weak, nonatomic) RCTCallableJSModules *callableJSModules;
@optional
@property (readonly, weak, nonatomic) RCTBridge *bridge;
@optional
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;

/* class methods */
+ (id)moduleName;
@optional
/* instance methods */
- (id)methodsToExport;
- (id)constantsToExport;
- (void)batchDidComplete;
- (void)partialBatchDidFlush;
@end

#endif /* RCTBridgeModule_Protocol_h */
