//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef SCPContextualFeedbackController_h
#define SCPContextualFeedbackController_h
@import Foundation;

#include "NSObject-Protocol.h"
#include "SCPContextualFeedbackViewController.h"

@class NSString, UIViewController;
@protocol SCPContextualFeedbackControllerDelegate;

@interface SCPContextualFeedbackController : NSObject<NSObject> {
  /* instance variables */
  SCPContextualFeedbackViewController *_feedbackViewController;
  UIViewController *_presentingViewController;
}

@property (weak, nonatomic) NSObject<SCPContextualFeedbackControllerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@optional
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMessageTitle:(id)title messageBody:(id)body okButtonTitle:(id)title uiTheme:(id)theme;
- (void)presentInViewController:(id)controller;
- (void)okButtonPressedInContextualFeedbackViewController:(id)controller;
@end

#endif /* SCPContextualFeedbackController_h */
