//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef ShowreelPlayerCache_h
#define ShowreelPlayerCache_h
@import Foundation;

#include "_TtP13ShowreelCache21ShowreelPlayerCaching_-Protocol.h"

@interface ShowreelPlayerCache : NSObject<_TtP13ShowreelCache21ShowreelPlayerCaching_> { // (Swift)
  /* instance variables */
   playerCache;
}

/* instance methods */
- (void)addDependentItems:(id)items;
- (id)getItem:(id)item;
- (id)loadItem:(id)item;
- (id)init;
@end

#endif /* ShowreelPlayerCache_h */
