//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef UIView_React_h
#define UIView_React_h
@import Foundation;

@interface UIView (React) <RCTComponent>
/* instance methods */
- (id)reactTag;
- (void)setReactTag:(id)tag;
- (id)rootTag;
- (void)setRootTag:(id)tag;
- (id)nativeID;
- (void)setNativeID:(id)id;
- (BOOL)shouldAccessibilityIgnoresInvertColors;
- (void)setShouldAccessibilityIgnoresInvertColors:(BOOL)colors;
- (BOOL)isReactRootView;
- (id)reactTagAtPoint:(struct CGPoint { double x0; double x1; })point;
- (id)reactSubviews;
- (id)reactSuperview;
- (void)insertReactSubview:(id)subview atIndex:(long long)index;
- (void)removeReactSubview:(id)subview;
- (int)reactDisplay;
- (void)setReactDisplay:(int)display;
- (long long)reactLayoutDirection;
- (void)setReactLayoutDirection:(long long)direction;
- (long long)reactZIndex;
- (void)setReactZIndex:(long long)zindex;
- (id)reactZIndexSortedSubviews;
- (void)didUpdateReactSubviews;
- (void)didSetProps:(id)props;
- (void)reactSetFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (struct CATransform3D { double x0; double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; double x10; double x11; double x12; double x13; double x14; double x15; })reactTransform;
- (void)setReactTransform:(struct CATransform3D { double x0; double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; double x10; double x11; double x12; double x13; double x14; double x15; })transform;
- (struct { struct YGValue { float x0; int x1; } x0; struct YGValue { float x0; int x1; } x1; double x2; })reactTransformOrigin;
- (void)setReactTransformOrigin:(struct { struct YGValue { float x0; int x1; } x0; struct YGValue { float x0; int x1; } x1; double x2; })origin;
- (id)reactViewController;
- (void)reactAddControllerToClosestParent:(id)parent;
- (BOOL)reactIsFocusNeeded;
- (void)setReactIsFocusNeeded:(BOOL)needed;
- (void)reactFocus;
- (void)reactFocusIfNeeded;
- (void)reactBlur;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })reactBorderInsets;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })reactPaddingInsets;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })reactCompoundInsets;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })reactContentFrame;
- (id)reactAccessibilityElement;
- (id)accessibilityActions;
- (void)setAccessibilityActions:(id)actions;
- (id)accessibilityLanguage;
- (void)setAccessibilityLanguage:(id)language;
- (id)accessibilityRole;
- (void)setAccessibilityRole:(id)role;
- (id)role;
- (void)setRole:(id)role;
- (id)accessibilityState;
- (void)setAccessibilityState:(id)state;
- (id)accessibilityValueInternal;
- (void)setAccessibilityValueInternal:(id)internal;
- (unsigned long long)accessibilityRoleTraits;
- (void)setAccessibilityRoleTraits:(unsigned long long)traits;
- (unsigned long long)roleTraits;
- (void)setRoleTraits:(unsigned long long)traits;
- (void)react_addRecursiveDescriptionToString:(id)string atLevel:(unsigned long long)level;
- (id)react_recursiveDescription;
@end

#endif /* UIView_React_h */
