//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.468, BuildCommit: a1243d3a18f9b0e29af55a12ad74ccd2cd1f0abc)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 15.0, SDK: 17.4, Tool: ld (16.0)
//    - LC_SOURCE_VERSION: 
//
#ifndef IGAPITextEntity_h
#define IGAPITextEntity_h
@import Foundation;

#include "IGAPIValueObject.h"

@interface IGAPITextEntity : IGAPIValueObject
/* class methods */
+ (const struct IGAPIValueObjectSchema *)APIValueObjectSchema;
+ (id)valueWithDisplayText:(id)text entityType:(id)type graphQLID:(id)qlid url:(id)url;
@end

#endif /* IGAPITextEntity_h */
